### ISSUE TITLE
iOS App Features and Screens / Table Of Contents

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/ios-app#1]
This issue tracks the planned features for the iOS app rewrite, where to find them - and how to get there.

## List Of Servers (Screen)
<img width="796" alt="bildschirmfoto 2018-03-07 um 15 39 29" src="https://user-images.githubusercontent.com/639669/37098274-cea9f19e-221d-11e8-942f-ee91f03791b3.png">

#### Features
- List Of Server Bookmarks
- Remove Server Bookmark
- Save last used Bookmark and re-connect automatically upon app termination / relaunch

#### Linked Screens
- Add / Edit Server Bookmark
- Server View
- Settings
- About / Help

## Add / Edit Server Bookmark (Screen)
<img width="1224" alt="bildschirmfoto 2018-03-07 um 15 40 44" src="https://user-images.githubusercontent.com/639669/37098345-f8605c4e-221d-11e8-9602-e992d726c4bf.png">

#### Features
- Enter / Edit Server Address
- Choose Authentication Method (auto-discovery if OC server supports it)
- Enter Passphrase (where applicable)
- Reset/Remove auth token (where applicable)

#### Linked Screens
- List Of Server Bookmarks
- Server Certificate Detail View

#### Features
- Show Certificate Details like Fingerprint, Common Name, Issuer, Serial and Expiration Date

#### Linked Screen
- Add / Edit Server Bookmark

## Server View (Screen)
![filelist](https://user-images.githubusercontent.com/639669/36067115-0d798ce2-0eb7-11e8-87c3-889a55b7d6f7.png)
![bildschirmfoto 2018-02-22 um 21 59 22](https://user-images.githubusercontent.com/639669/36563886-c922e8d6-181b-11e8-9095-6232a451678b.png)
#### Features
- File Browser Tab
  - Search
  - Sort (inspired by Files app)
  - Item Detail View
  - Grid / List / Slide View
  - Preview File
  - Drag & Drop
  - Thumbnails (where supported by Server)
- Shares Tab
  - List Of Shares
  - Delete Shares
- Network Activity Indication Tab
  - Currently running up-/download/sync activities
  - Option to cancel network activities

#### Linked Screens
- Item Detail View

## Item Detail View (Screen)
![actionshare](https://user-images.githubusercontent.com/639669/36067109-f74c6110-0eb6-11e8-97d9-31da95173de8.png)
#### Features
- Add, Remove and List Shares per item
- File metadata (size, last modified)
- Download status
  - Make available Offline
  - Delete Offline Copy
- Actions
  - Open with
  - Rename
  - Move
  - Preview
  - Delete

#### Linked Screens
- Server View / File Browser Tab

#### Features
- Paginated PDF viewing (+ annotations if supported by iOS out-of-the-box)
- Video preview (for downloaded files, and possibly streaming)
- Text file preview / basic editing

#### Linked Screens
- Server View / File Browser Tab
- Item Detail View

#### Features
- Background Uploads / Downloads
- Account to upload photos to
- Passcode Lock
- Touch ID Lock
- Clear Caches

#### Linked Screens
- List Of Servers
- User-Approved Certificates

#### Features
- List User-Approved Certificates
- Delete User-Approved Certificates

#### Linked Screens
- Server Certificate Detail View
- Settings

#### Features
- Help
- Version Information
- License Information (on included third-party libraries such as OpenSSL)

#### Linked Screens
- List Of Servers

## Other features
- Migration URL (change of server URL via MDM)
- iOS 11+ only
- Share Extension
  - Share to ownCloud folder
- File Provider Extension (Files app integration)
- Layout adapts to iPhone and iPad respectively
  - Support for iPad multitasking (split screen + slide over)
  - Portrait and Lanscape support throughout the app
- Branding Options

**Comment by jesmrec** [comment]
Let's analyse a bit all this nice stuff:

Regarding this one:

### Add / Edit Server Bookmark (Screen)

is this the entry point for the user who clicks the app icon for the first time after installing? if it is, user is given the option to input the server URL and depending the authentication method (currently we are detecting it using the header `www-authentication` that the server sends with Basic / Bearer info), either inputs basic auth credentials (will we support this @michaelstingl?) or is redirect to OAuth2 webview that handles the authentication.

For this consideration (OAuth2) , and regarding security issues, very important: https://github.com/owncloud/ios/issues/942 . 

This feature:

> Reset/Remove auth token (where applicable)

would need core support (API for that?), that is not currently available. 

I think these two options should be clearly differentiated:

- Add a new bookmark
- Edit an existing bookmark

Although in both cases the view will be similar for the user, the logic to handle is not the same (does it means different views as well?). For example: 

- User adds a new server (bookmark) -> input URL, and credentials -> user authorized by core. Until first authorization is not granted

> #### Linked Screens
> - List Of Server Bookmarks

should not be reachable.

- User edits an existing server (bookmark) -> user wants to edit his credentials, but not the URL. Changing URL means migration and not edition, imo. Also, in this case:

> #### Linked Screens
> - List Of Server Bookmarks

should be always available.

Regarding `List of Servers`:

> ## List Of Servers (Screen)
> #### Features
> - List Of Server Bookmarks
> - Remove Server Bookmark
> - Save last used Bookmark and re-connect automatically upon app termination / relaunch

I miss in the the list the feature to add / edit a bookmark, that points a few lines below to its linked screen:

> - Add / Edit Server Bookmark

only an small tweak, you know.

**Comment by felix-schwarz** [comment]
> Regarding this one:
> 
> ### Add / Edit Server Bookmark (Screen)
> 
> is this the entry point for the user who clicks the app icon for the first time after installing? 

No. The entry point is the List Of Servers, from where users can also access Settings and Help. If no server has been added yet (which should be the case on first launch, too, of course), a message with a call to action "Add server" is shown to the user:

![bildschirmfoto 2018-02-22 um 21 58 41](https://user-images.githubusercontent.com/639669/36563851-b415b180-181b-11e8-9368-1ec435f64551.png)

> if it is, user is given the option to input the server URL and depending the authentication method (currently we are detecting it using the header `www-authentication` that the server sends with Basic / Bearer info), either inputs basic auth credentials (will we support this @michaelstingl?) or is redirect to OAuth2 webview that handles the authentication.

I imagine adding a server to be a two-step process:
- *Step 1*: the user enters a name and the server's URL, then taps "Continue"
- The App can now query the server for the authentication methods it offers and also grab a copy of the server's certificate (if any)
- The App subsequently presents the available authentication methods to the user (defaulting to OAuth2 where available) and also adds a "Show Certificate Details" button below the URL the user entered.
- *Step 2*: (assuming OAuth2) the user taps "Connect" and finishes authentication

Regarding supported authentication methods: I don't know since when OAuth2 is supported by ownCloud servers - or whether it is safe to assume it's always available on recent installs. I would suggest to start OAuth2-only, but keep the door open for other authentication methods if they're needed (I can see this, f.ex. on tvOS, where no web views are available).

> For this consideration (OAuth2) , and regarding security issues, very important: https://github.com/owncloud/ios/issues/942 . 

Thanks!

> This feature:
> 
> > Reset/Remove auth token (where applicable)
> 
> would need core support (API for that?), that is not currently available. 

This can be achieved by setting the respective OCBookmark's authenticationData to nil. Setting it to nil deletes the data from the keychain.

> I think these two options should be clearly differentiated:
> 
> - Add a new bookmark
> - Edit an existing bookmark
> 
> Although in both cases the view will be similar for the user, the logic to handle is not the same (does it means different views as well?). For example: 

The logic should be so similar that I would actually realize both in one view controller. Here are the scenarios I have in mind:

1) User changes name
- No difference

2) User changes server address
- Add: view controller starts with all rows below the address hidden. 
- Edit: view controller hides all rows below the address.
- Common: user taps on "Continue" for the client to fetch available auth methods + certificate.

3) User changes auth method
- Common: the interface adapts accordingly to show/hide f.ex. user/pass fields.

4) User enters user/pass or changes user/pass fields
- Common: that data is sent to the OCAuthenticationMethod's `-generateBookmarkAuthenticationDataWithConnection:..` in a dictionary when the user taps "Connect". If the authentication succeeds, the app can update the bookmark with the returned authenticationData.

5) User completes action (either Add or Edit) by tapping "Connect"
- Common: authentication is attempted and the user is prompted if either no auth data exists ("Delete Authentication Data") or it is no longer valid

I can't think of any other scenarios right now. Please let me know if I overlooked any.

> - User edits an existing server (bookmark) -> user wants to edit his credentials, but not the URL. Changing URL means migration and not edition, imo. 

Other than changing the base path of the 

> Regarding `List of Servers`:
> 
> > ## List Of Servers (Screen)
> > #### Features
> > - List Of Server Bookmarks
> > - Remove Server Bookmark
> > - Save last used Bookmark and re-connect automatically upon app termination / relaunch
> 
> I miss in the the list the feature to add / edit a bookmark, that points a few lines below to its linked screen:
> 
> > - Add / Edit Server Bookmark
> 
> only an small tweak, you know.

If a feature is actually implemented in a different place and turns up in "Linked Screens", I tried to avoid to also list it under "Features", too, so it's clear what's actually implemented in which place. The thought behind that was that if something is a "Linked Screen", the Screen that it is linked to from must provide access to it in some way.

**Comment by hurradieweltgehtunter** [comment]
I was asked to have a look here regarding ownCloud CI and layout. I think it's awesome that you guys make this extra effort. By rewriting the app, we should definitely be correct on CI and styles.
I'm not quite sure how much I need to tell you about styles etc. so i'm just writing down what comes to my mind. If it's too basic, just ignore it.
Here it goes:

### Colors
Primary color: #1D293B (oc dark blue)
Secondary color: #468CC8 (oc light blue)
We do not use any gradients on any surfaces.

### Logo
Please use the correct logo -> https://owncloud.org/trademark/
The text "ownCloud" must not be removed from the cloud.
The most correct use would be a white logo on a oc dark blue background (like in the top menu bar). If it's possible, please implement like this.
The logo in the screenshots is a mix from community and enterprise logo which doesn't exist in this way.
Also, no grey logo, no gradient and no oc enterprise orange.

### Icons
Please use clean, monochrome icons without shadow or 3d effects. See FontAwesome for example.
Icons can be very useful if used in a meaningful way but not every element needs an icon. It should provide a real advantage for every new and recurring user.

### Buttons, Preview Images etc.
Please do not use rounded corners. 

### Font
ownClouds main font is OpenSans Light and Bold (no semi-bold, regular, ...)

### Example
1) correct color in head bar
2) correct logo in head bar
3) removed all rounded corners on buttons, file icon and dialog overlay

![image](https://user-images.githubusercontent.com/16665512/36623734-9f1ff5b4-1907-11e8-9c75-70252aa7610d.png)

If you need any help regarding CI, I'm always happy to help.

**Comment by felix-schwarz** [comment]
I added a screen for User-Approved Certificates that's accessible via the Settings.

Users should be able to see which certificates they approved and revoke their approval on an individual basis.
