### ISSUE TITLE
(local) fastlane ==> (internal) TestFlight

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#10]
@ChrisEdS please set this up. What's missing?

- [x] App Icon
- [ ] gitea access
- [ ] … what else?
- [ ] …

**Comment by michaelstingl** [comment]
@ChrisEdS Here you can find the beta icon we use for Android: https://f-droid.org/en/packages/com.owncloud.android.beta/

**Comment by ChrisEdS** [comment]
Already up and running. PR here: [#36](https://github.com/owncloud/ios-app/pull/36)

**Comment by ChrisEdS** [comment]
[](https://github.com/owncloud/ios-app/pull/36)
