### ISSUE TITLE
[BUG] Onboarding-Section not always available

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#1007]
## If you found a bug:
In the branded login, the onboarding section is missing, if the parameter `can-add-account` is `false`.

### Steps to reproduce
1. set up a branded build via `Branding.plist`
2. set parameter `branding.can-add-account` to `false`
3. include all needed parameters for the onboarding section: `branding.profile-help-button-label` `branding.profile-help-url` `branding.profile-open-help-message`
4. start app with no account

### Expected behavior
Onboarding section should be visible on the bottom

### Actual behavior
Onboarding section is only available if the parameter `can-add-account` is set to `true`.

### Client
**ownCloud app version:**
11.6

**Comment by hosy** [comment]
Hotfix is available and should be merged into the `master` branch, without releasing a new app version. //cc @michaelstingl

**Comment by michaelstingl** [comment]
👍 

Also 11.7?

**Comment by jesmrec** [comment]
Fields involved:

`canConfigureURL` 
`promptForHelpURL`
`helpURLButtonString`
`helpURL`

Branding profile from: [owncloud online](https://github.com/owncloud/ios-app/blob/master/ownCloud/Resources/Theming/Branding-owncloud-online.plist)

**Test 1:**

`canConfigureURL`  = `false`

In this case,  url is not setup-able and comes from key `url` . User is prompted to enter credentials (in the app itself or in browser)

Onboarding section is correct with values included in `promptForHelpURL`, `helpURLButtonString`, `helpURL`

In the previous version (`milestone/11.7`), both sections onboarding and prompt to login were missed. So, this is fixed.

Result: ✅ 


**Test 2:**

`canConfigureURL`  = `true` 

In this case,  url is setup-able and user must enter it in the app . 

Onboarding section is correct with values included in `promptForHelpURL`, `helpURLButtonString`, `helpURL`

In the previous version (`milestone/11.7`), both sections onboarding and prompt to login were correct.

Result: ✅ 


This is approved on my side. 

More testing is pending in terms of branding/MDM to avoid this problems.

**Comment by jesmrec** [comment]
Done! Ready to 11.7
