### ISSUE TITLE
[BUG] Markup on iOS 15 not working as expected

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#1012]
## If you found a bug:

Markup on iOS 15 is not working as expected:
- Edit will not be enabled automatically 
- `Done` does not close the Markup view and does not save the edited file back

### Steps to reproduce
1. Use a device on iOS 15
2. Markup a PDF file
3. Edit is not automatically enabled
4. Done does not do anything

### Expected behavior
- Edit mode will be auto enabled
- Done shows the alert and close the view

### Actual behavior
Tell us what happens instead

### Client
**iOS version:**
iOS 15 beta 4

**ownCloud app version:**
11.7

**Device model:**
iPad 12,9 3 gen

**Comment by jesmrec** [comment]
Done. Ready to 11.7.1
