### ISSUE TITLE
[FEATURE REQUEST] Compact Account List (one Account)

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#1014]
In my opinion the app could look much nicer, when we using the compact account list, if only one account exists in the app.

We using this compact view already for `ownCloud online` and branded clients (if `canAddAccount` is disabled)

It would be great to uses this compact layout for the regular app too.

- [ ] Add Account Button is missing on this view

Here is a comparison:

| Current Single Account                                                                                                                                                              | Compact Single Account                                                                                                                                       |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-07-30 at 10 16 14](https://user-images.githubusercontent.com/736109/127623386-322a43c6-05cd-4042-ba4c-51ce011627e4.png) | ![iPhone SE (2nd generation)-11_ios_accounts_list_demo](https://user-images.githubusercontent.com/736109/127622957-af2b11ad-3431-48f5-93cc-0bdd2e0faf94.png) |

**Comment by michaelstingl** [comment]
Nice idea 👍 Majority of users only use one account at all.

**Comment by michaelstingl** [comment]
Implemented in 11.8
