### ISSUE TITLE
[BUG] [iOS15] Camera uploads not working

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#1025]
### Steps to reproduce
1. In `Settings` enable camera uploads for videos/pictures. 
2. Take some pictures or videos with the camera

### Actual behavior
Nothing is uploaded after opening the app. After waiting some minutes, nothing is uploaded

### Expected behavior
Pictures uploaded after opening the app

I caught some logs... i hope they help:

[ownCloud_25_Aug_2021_at_14_09_28.log.txt](https://github.com/owncloud/ios-app/files/7046960/ownCloud_25_Aug_2021_at_14_09_28.log.txt)

iPadPro iOS15.0
Release 11.7 from AppStore

**Comment by hosy** [comment]
@jesmrec are you sure this bug only related to iOS 15?

**Comment by jesmrec** [comment]
I managed to reproduce it in iOS15 and not in other version. I can recheck as soon as i recover the iOS15 device.

**Comment by jesmrec** [comment]
I've just repeated the test with two devices over the same commit `683cc4c9` (current one in App Store)

iOS14 (iPhone XR): Camera uploads work. Taking pictures with camera and then opening the app, triggers the uploads correctly

iOS15 (iPhone Xs): Camera uploads does not work. Taking pictures with camera and then opening the app, nothing happens. Pictures not uploaded

I can't assure that the problem was iOS15, but such different behaviours point to that. In the upper message i attached some logs, if any other test could help, just ping me.

**Comment by hosy** [comment]
Is it working with the latest `milestone/11.7.1` commit.
Maybe this fix is related to the issue: https://github.com/owncloud/ios-app/pull/1017

**Comment by jesmrec** [comment]
will check again with that

**Comment by jesmrec** [comment]
I rechecked with commit `c138070e` and same result. These logs were caught:

[ownCloud_17_Sep_2021_at_11_28_17.log.txt](https://github.com/owncloud/ios-app/files/7184538/ownCloud_17_Sep_2021_at_11_28_17.log.txt)

**Comment by jesmrec** [comment]
Last iOS15 upgrade (15.0 from 2021/09/20) made camera uploads work again
