### ISSUE TITLE
[BUG] Opening Private Link in Branded Build

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#1031]
## If you found a bug:

If the iOS app is branded (e.g. ownCloud.online) a private link cannot be opened in detail view.

### Steps to reproduce
1. Build a branded client (e.g. ownCloud.online)
2. Open a file with `owncloud://demo.owncloud/f/39` (please add the demo server as account before and be sure the file id exists)
3. App will be opened, but not the account and detail view

### Expected behavior
File will be opened in detail view

### Actual behavior
App will be opened but does not change the view

### Client
**ownCloud app version:**
11.7.0

**Comment by jesmrec** [comment]
Done. Ready to 11.7.1
