### ISSUE TITLE
[BUG] In pdf preview, Go to Page don't take user to last page

### ISSUE THREAD

**Issue by itsaboutcode** [owncloud/ios-app#1033]
### Steps to reproduce
1. Open PDF
2. Select "Go to page" action
3. Enter last page# and it will show you an error saying "The entered page number doesn't exist"

### Expected behavior
It should take the user to the last page of the PDF.

### Actual behavior
It's giving an error "The entered page number doesn't exist"

### Client
**iOS version:** 14.5

**ownCloud app version:** 11.7.0

**Device model:** Simulator

### Server configuration
**Web server:** NA

**Database:** NA

**PHP version:** NA

**ownCloud version:** NA

**Storage backend (external storage):** NA

#### Web server error log
```
NA
```

#### ownCloud log (data/owncloud.log)
```
NA
```

**Comment by jesmrec** [comment]
Done. Ready to 11.7.1
