### ISSUE TITLE
[FEATURE REQUEST] - Branded folder color = corporate color

### ISSUE THREAD

**Issue by NannaBarz** [owncloud/ios-app#1069]
The folder color should be the corporate color when we brand an iOS-App.

Actual we have an advanced parameter for this:

`<key>branding.theme-definitions$[0].Colors.Icon.folderFillColor</key>`

I think it looks better when the folder color is the corporate color. For the case we need another folder color, we can use the advanced parameter to change it. 

@hosy @michaelstingl

**Comment by jesmrec** [comment]
Done! Ready for 11.8.2
