### ISSUE TITLE
[MDM] move ios_mdm_tables.adoc to doc/CONFIGURATION.adoc

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#1070]
@hosy please adjust GH action to move the [`docs/modules/ROOT/pages/ios_mdm_tables.adoc`](https://github.com/owncloud/ios-app/blob/master/docs/modules/ROOT/pages/ios_mdm_tables.adoc) to `doc/CONFIGURATION.adoc`

**Comment by mmattel** [comment]
I will wait to include the mdm file until it has been moved to its final location.

See also the PR I created to fix a rendering issue #1073 (Update ios_mdm_tables.adoc.tmpl) and #1074 (Update CONFIGURATION.json) which might be merged upfront moving.
