### ISSUE TITLE
[BUG] Update CONFIGURATION.json (incomplete links)

### ISSUE THREAD

**Issue by mmattel** [owncloud/ios-app#1075]
## Found a bug:
Found while working on: https://github.com/owncloud/ios-app/pull/1073 (Update ios_mdm_tables.adoc.tmpl)
Fixes: https://github.com/owncloud/ios-app/pull/1074 (Update CONFIGURATION.json)

The content in `CONFIGURATION.json` needs an update, see the refefenced PR which got closed, the file is created dynamically as @michaelstingl pointed in that PR. Therefore the change needs to be made in the source that creates the file.

It is not a big thing, three links to documents in this repo are not created as links because the full URI was not used. The .json file is used to generate the mdm table automatically and that file is used in the documentation - the content is visible on the web and the URI used should therefore be correct.

Note that I did not deleted the branch in the closed PR which makes it easier to check the changes made. When a new PR has been created fixing this issue, the branch in the closed PR can safely be deleted.

### Expected behavior
Correct clickable link

### Actual behavior
Link = text and incomplete not pointing to the source and therefore unfindable.

@michaelstingl @hosy @felix-schwarz @jesmrec

**Comment by hosy** [comment]
@mmattel please can you point me which line needs an update in the adoc file and how it should looks like?
