### ISSUE TITLE
Error messages to be improved (better UX)

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#109]
Currently, the app is displayed errors retrieved by the SDK in a non-human-readable way.

List of errors: 

- [X] Create Folder with already existing name
- [X] File is renamed with existing name
- [X] File is move to a target with other item with the same name
- [X] File that does not exist (was removed in other client or in the web UI) is renamed
- [ ] File fails to upload: https://github.com/owncloud/ios-app/issues/109#issuecomment-469601308

One example:

<img width="360" alt="screen shot 2018-08-23 at 10 48 04" src="https://user-images.githubusercontent.com/14894746/44515134-0aceee80-a6c2-11e8-91cd-723fafaeef2b.png">

such error happens when a folder is created with an already existing name. 

Which mecanisms can be developed to translate core/SDK errors to a human-readable format? 

CC @pablocarmu @michaelstingl @felix-schwarz

**Comment by michaelstingl** [comment]
Release version needs human-readable messages. I've seen some error messages already are better, but other ones still have the technical error. @jesmrec Could you have another look?

**Comment by jesmrec** [comment]
https://github.com/owncloud/ios-app/issues/220#issuecomment-454831255 is not fixed yet

I will take a look for more non-final-user-readable errors.

**Comment by michaelstingl** [comment]
Also an error-message regression in the Files app?
https://github.com/owncloud/ios-app/issues/221#issuecomment-461246527

**Comment by jesmrec** [comment]
Error message above happens when (Files App):

- folder with existing name is created
- file is renamed with existing name
- file is move to a target with other item with the same name
- file that does not exist (was removed in other client or in the web UI) is renamed

**Comment by jesmrec** [comment]
I uploaded a bunch of files, and a couple of the returned the following message:

![screen shot 2019-03-05 at 10 12 39](https://user-images.githubusercontent.com/14894746/53793986-4f6bfa00-3f2f-11e9-833d-511da1ae1ba6.png)

**Comment by hosy** [comment]
The question is, what are better error messages? Some error messages are technical and gives more context for our support with debugging context.

For me, this error message is technical, but all users can understand (I asked  my wife ;) ):
![](https://user-images.githubusercontent.com/14894746/53793986-4f6bfa00-3f2f-11e9-833d-511da1ae1ba6.png)

### What is the context of the error message?
Couldn't upload file (this is what a user should understand, if dealing with a file app)

### What is the reason for that?
- The operation couldn't be completed. (this is what a user should understand, if dealing with a file app)
- OCHTTPStatusErrorDomain error 412 (this will help our support with more context)

**Comment by jesmrec** [comment]
what i mean, is that no technicals like `OCHTTPStatusErrorDomain` should be displayed to final users. Of course it can help in terms of debugging, but for this aim @felix-schwarz developed a logging feature. Such messages are confusing since is not understandable for everyone. 

Other apps shows the readable message and a `Details` for further info (only as idea).

**Comment by michaelstingl** [comment]
Error messages should be actionable when possible. Even if users can't fix the problem, they maybe can workaround it.

**Comment by hosy** [comment]
Here is maybe a better UI (draft) for this:

<img width="302" alt="bildschirmfoto 2019-03-06 um 12 02 22" src="https://user-images.githubusercontent.com/736109/53876816-ee642500-4007-11e9-8f49-025b81496ba9.png">
<img width="317" alt="bildschirmfoto 2019-03-06 um 12 03 49" src="https://user-images.githubusercontent.com/736109/53876818-eefcbb80-4007-11e9-8f5f-67f8e8634459.png">

**Comment by hosy** [comment]
> Error messages should be actionable when possible. Even if users can't fix the problem, they maybe can workaround it.

Don't know what you exactly mean.

**Comment by hosy** [comment]
Or maybe this solution:

<img width="326" alt="bildschirmfoto 2019-03-06 um 12 06 32" src="https://user-images.githubusercontent.com/736109/53876998-531f7f80-4008-11e9-8e47-1b36f5e0e683.png">

**Comment by michaelstingl** [comment]
> Don't know what you exactly mean.

I create a folder "New Folder". Then I create another folder "New Folder". This is the error I get:

![2019-03-06_12_06_53](https://user-images.githubusercontent.com/214010/53877257-f96b8500-4008-11e9-9562-bc506865682c.png)

An "actionable" error message would help users to understand, the identical name causes the problem.

**Comment by hosy** [comment]
Error messages will be improved by @felix-schwarz in the SDK. If we want add a `Show more` button, this needs more investigation on the SDK side and this should be done in the next milestone.

But all error messages mentioned above are at this moment human readable and already improved.

**Comment by jesmrec** [comment]
these errors:

> Create Folder with already existing name
 File is renamed with existing name
 File is move to a target with other item with the same name
 File that does not exist (was removed in other client or in the web UI) is renamed

are fixed, now showed in readable language. 

In case new errors arise, individual issues will be created, if you agree.
