### ISSUE TITLE
[BUG] Shortcuts: EMM version throwing Pro Feature Unlock Error

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#1114]
The EMM Shortcuts actions throwing an error that this feature is not unlocked. 

 
 
### Steps to reproduce
1. Add an EMM action in Shortcuts app
2. Run 

### Expected behavior

EMM does include all features and need no extra unlock. 

### Actual behavior
Error message and execution stops

### Client
**iOS version:**
15.5
**ownCloud app version:**

11.9.0

![image](https://user-images.githubusercontent.com/736109/160153812-e01ad68f-d500-476f-8117-40e054e8a68d.jpeg)

**Comment by jesmrec** [comment]
Fixed!!
