### ISSUE TITLE
[BUG] Shortcuts: Action Delete Path Item is missing Accounts

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#1123]
## If you found a bug:
It's related the Delete Path Item operation. It has two parameters Path and Account . The Account parameter does not list the available ownCloud accounts to choose one. Other available operations with Account parameter work fine in this regard.

### Steps to reproduce
1. Select `Delete Path Item` action
2. Try to select an configured account
3. No account available

### Expected behavior
Show all configured accounts

### Client
**ownCloud app version:**
11.9.1

**Comment by jesmrec** [comment]
Fixed!!
