### ISSUE TITLE
[BUG] Av. offline badge is there after making unav. offline

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#1128]
### Steps to reproduce

1. Set any file as available offline -> badge displayed in file list and `Available offline` option in card (check https://github.com/owncloud/ios-app/issues/1065)
2. Set the file as unavailable offline 

### Actual behavior
Av. offline badge is not gone. Sometimes, the option in card/contextual menu is `Available Offline`

### Expected behavior
Av. offline badge is gone because file is not available offline. Option displayed in card/contextual menu is `Make Available Offline`

https://user-images.githubusercontent.com/14894746/173338438-794e18d6-f0f4-49a8-b57c-b990f6895ecd.MP4

**iOS version:** 15.4.1

**ownCloud app version:** `11.10.0` and `12.0 build 223`

**Device model:** iPhone XR

**Comment by michaelstingl** [comment]
@jesmrec still an issue?

**Comment by jesmrec** [comment]
Still an issue. Switching off the av. offline toggle, the indicator is still there. Tested in `feature/account-wizard` commit `5a374568` :

https://github.com/owncloud/ios-app/assets/14894746/8ae012d8-f3a0-481d-a56d-1cdd4328f7ba

**Comment by felix-schwarz** [comment]
@jesmrec @michaelstingl This should be fixed as of https://github.com/owncloud/ios-app/commit/a27068d6f6f3cdf20f3ccdcfbec60d2c0f4f0d5b in #1274.

**Comment by jesmrec** [comment]
Fixed. That's right, UI does not change at the moment but after a short time it happens and is correct.
