### ISSUE TITLE
iOS App: Offline folders not working correctly

### ISSUE THREAD

**Issue by MarSan2021** [owncloud/ios-app#1130]
The folder structure is not synced for Offline Mode.

Steps to reproduce:
* go online with the app
* mark a folder as "available offline", wait for the initial download to complete
* stop the app
* turn flight mode on and wlan off
* restart the app

now the following behaviour occurs:
* the folder is displayed in the section "Available Offline" but
* if you click the folder the following screen is empty - no files displayed.

However if you select "all Files" the files are listed (sorted by name but not structured).

We really like the app but this is a little annoying.

**Comment by jesmrec** [comment]
Done! Available in 11.10.1
