### ISSUE TITLE
[iOS16 / iPadOS16] Beta testing & reports

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#1141]
iPadOS https://github.com/owncloud/ios-app/issues/1141#issuecomment-1223936734

Reports:

- iPadOS 1
- iPadOS 2
- iPadOS 3
- iPadOS 4
- StageM 1
- StageM 2

iOS https://github.com/owncloud/ios-app/issues/1141#issuecomment-1224289367

Reports

- iOS 1: Markup mode [FIXED]
- iOS 2: Thumbnails blinking
- iOS 3: Controls in video player are missing [FIXED]

Testing is done with the latest stable version in Apple Store: `11.10.1 build 226 (3043ae7c, 57729a6)`

**Comment by jesmrec** [comment]
# iOS16 [TO DO]

**Comment by jesmrec** [comment]
# iOS16 [TO DO]

**Comment by felix-schwarz** [comment]
@jesmrec `iOS 3` is fixed by https://github.com/owncloud/ios-app/pull/1157

**Comment by jesmrec** [comment]
Everything fixed or addressed to other issues. Support for iOS/iPadOS 16 completed. From now on, regular work with our internal releases.
