### ISSUE TITLE
[BUG] Public Links entries in Quick Access have no feedback

### ISSUE THREAD

**Issue by j-c-cook** [owncloud/ios-app#1144]
### Steps to reproduce
1. Create a public link
2. Go to the "Quick Access" tab, then select the "Public Links" folder
3. Click on the public link and observe no response 

### Expected behavior

When pressed, the link should open. When long pressed, the link should be copied. Pressing the 3 dots on the right side should show a pop up menu. 

### Actual behavior

There is no response when pressing on the folder. 
### Client
**iOS version:**

15.6.1

**ownCloud app version:**

ownCloud release version 11.10.1 build 226
(app: 3043ae7, sdk: 57729a6)

**Device model:**
iPhone 13 mini

**Comment by jesmrec** [comment]
Not reproducible on my side. 

Just a clarification. Expected behaviour when long pressing on the link from quick access is showing the contextual menu, not copying the link.

Will try to check with another devices.

Thanks a lot for reporting

**Comment by j-c-cook** [comment]
Strangely, I have just checked again and it is working now. I am unsure of why the behavior changed on my end. The app version is still the same. Perhaps I restarted the phone one time and that let the app take full effect.
