### ISSUE TITLE
Manual Upload to files list

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#115]
_As user, i want  to upload files manually to the folder structure_ 

easy iteration to get the first use case about upload manually files from camera roll.

AC:

- In the files view, will be an option to select `Upload`
- Album list displayed 
- One or more files can be selected, and they will be uploaded to the current folder 
- Failed uploads will be displayed (bottom of the screen?)

### Mockups:

1- On the navigation view we have a "..."

<kbd>

![uploads 1](https://user-images.githubusercontent.com/1815050/46023666-63d8da80-c0e5-11e8-8c6e-fbff03599cbd.png)

</kbd>

2- Pressing the button "..." open an Action Sheet to choose between "Uploads" or "Multiseleccion".

<kbd>

![uploads 2](https://user-images.githubusercontent.com/1815050/46023604-4441b200-c0e5-11e8-9b13-6e46a7d66a6d.png)

</kbd>

3- Tapping "Uploads" we can now choose between upload an image/video (from camera roll) or "Upload a file" from Document Providers (Files App)

<kbd>

![uploads 3](https://user-images.githubusercontent.com/1815050/46023605-4441b200-c0e5-11e8-8337-3f38c2a3934a.png)

</kbd>

4- Once selected "Upload photos/videos" we see the list of our "albums" in order to select where are the images

<kbd>

![uploads 4](https://user-images.githubusercontent.com/1815050/46024714-adc2c000-c0e7-11e8-887f-279414b2f918.png)

</kbd>

5- The list of the images as a grid with the possibility to select one or more than one.

<kbd>

![uploads 5](https://user-images.githubusercontent.com/1815050/46025005-35103380-c0e8-11e8-9173-cfddf6a69b73.png)

</kbd>

**Comment by javiergonzper** [comment]
Updated the firtst comment with the mockups.

Questions:

- The multiselection will be implemented? If not we can change the "..." of the file list for a "+" button
- The 2 and 3 could be merge in a same Action Sheet. What do you think? It improve the usability reducing 1 tap

cc: @michaelstingl @jesmrec @mneuwert @pablocarmu

**Comment by jesmrec** [comment]
> The multiselection will be implemented? If not we can change the "..." of the file list for a "+" button

yes, it will be. Better keeping the three-dot-button

> The 2 and 3 could be merge in a same Action Sheet. What do you think? It improve the usability reducing 1 tap

I agree with merging to have all actions together in the same sheet.

**Comment by michaelstingl** [comment]
I like the way it's presented when you hit a upload feature on a website in iOS 12 Safari:
![2018-10-17 23 35 28](https://user-images.githubusercontent.com/214010/47118015-520ed100-d266-11e8-89e0-c9c7e5a8d613.png)

Is there something from the system that could be used directly?

Klicking `Browse …` opens [`UIDocumentPickerViewController`](https://developer.apple.com/documentation/uikit/uidocumentpickerviewcontroller) I think, so users could upload from everywhere very easily.

**Comment by pablocarmu** [comment]
This action sheet with images in the right side it's possible only with Apple's private APIs so if you want something like this, we're going to make it ourselves.

**Comment by michaelstingl** [comment]
Not sure if the images are really needed. Should be okay without images.
