### ISSUE TITLE
[BUG] App Lock Interval in Share Extension

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#1154]
### Steps to reproduce
- Passcode is enabled and the app lock interval is not set to `immediately` (try 1 minute)
- App is locked
- Open the share sheet (e.g. from Safari) > pin code view will be shown
- unlock the share extension with pin code or biometrical unlock
- close the share sheet
- open share sheet again (in less than a minute)
- pin code view will be shown again
- should not happens, when opened in less than a minute again.

App lock interval only works after opening the app again.

### Expected behavior
If the share sheet will be shown the app lock interval should be respected and not be shown every time.

**Comment by jesmrec** [comment]
Fixed
