### ISSUE TITLE
Instant uploads 

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#116]
_As user, i want that the content taken for the camera is upload directly to a selected folder, so i do not have to take care of uploading them manually_

Mock already defined and available in [WIP] in the app

![screen shot 2018-09-25 at 10 54 36](https://user-images.githubusercontent.com/14894746/46003801-9ec11b00-c0b1-11e8-98d2-28a383654dd0.png)

AC:

- Pics and videos handled separately
- Under 4G only if option "only wifi" is not selected. 
- Target folder selected. If it does not exist (because it was removed before or other reasons), it is created again and the content uploaded into. Folder displayed below the option name
- Only is uploaded the content taken while the option is enabled (videos/pics separately). If it is disabled, no content upload anymore
- Possibility to upload in background, needed location services in such case. If not, content will be uploaded when the app comes to foreground. Option is displayed when (at least) one of pics/videos is enabled.

**Comment by michaelstingl** [comment]
> Please consider to implement a default sync profile when you have more than one sync profiles present.

@mmattel Could you elaborate? What are the characteristics of such a sync profile? How/when to change them?

**Comment by mmattel** [comment]
Imagine having accounts on three different ownclouds. Lets say one private and two business.
Now you of course want to define which account will be the one defined as target for you automated picture upload. Independent of which account you currently have activated, the pictures should only go into the defined one and not the active one. Not waiting that the defined one gets activated, upload in the background to the defined while working with the activated !

**Comment by jesmrec** [comment]
you mean, a default account to upload to, not the active one. This needs to think about. 

I'd go for different stages to be developed separately/incrementally

1. instant uploads to the selected folder
2. instant uploads with only wifi
3. instant uploads with background support
4. option to set a default account or the active one

more ideas welcome!
