### ISSUE TITLE
[FEATURE REQUEST] Make OIDC prompt parameter configurable via branding/MDM

### ISSUE THREAD

**Issue by d7oc** [owncloud/ios-app#1180]
**Is your feature request related to a problem? Please describe.**
Depending on the IDP it might be required to adjust the OIDC prompt parameter in the app. Right now the prompt for iOS cannot be modified, this is only possible in the desktop app.

**Describe the solution you'd like**
Add a parameter similar to `authentication-oauth2.oidc-scope` in https://doc.owncloud.com/ios-app/11.11/appendices/mdm.html#openid-connect-oidc-parameters, e.g. `authentication-oauth2.oidc-prompt` which allows the modification of the OIDC prompt parameter of the app.

**Describe alternatives you've considered**
None

**Additional context**
Was just found during a cross check of the OIDC branding capabilities of iOS/Desktop and Android app.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by michaelstingl** [comment]
@felix-schwarz should be a simple thing? (would need a backport to a tmp branch from [`v11.11.1`](https://github.com/owncloud/ios-app/releases/tag/v11.11.1))

**Comment by michaelstingl** [comment]
[`authentication-oauth2.oidc-prompt`](https://github.com/owncloud/ios-app/blob/v12.0/doc/configuration.adoc) available in [`v12.0`](https://github.com/owncloud/ios-app/releases/tag/v12.0) ✅
