### ISSUE TITLE
[BUG] Navigating to a folder shows the "No contents" screen for a while

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#1190]
### Steps to reproduce
1. Setup new account
2. Navigate a few folders deep
3.

### Expected behavior
Navigating to a new folder, and content isn't discovered yet, app should display discovery status (spinner?) instead of "No contents" screen

### Actual behavior
Navigating to a folder shows the "No contents" screen for a while

### Client
**iOS version:**
16.3.1

**ownCloud app version:**
```
ownCloud beta version 12.0 build 250
(app: de4381b5, sdk: 359d9c4)
```

**Device model:**
iPad Pro (12.9-inch) (3rd generation)

### Server configuration
**Web server:**

**Database:**

**PHP version:**

**ownCloud version:**
`{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.11.0.6","versionstring":"10.11.0","edition":"Enterprise","productname":"ownCloud","product":"ownCloud"}`

![CleanShot 2023-03-09 at 14 36 02](https://user-images.githubusercontent.com/214010/224039236-02b7c52e-13c5-458c-ac61-57e205f4a532.png)

**Comment by jesmrec** [comment]
Not reproducible anymore in the latest builds.
