### ISSUE TITLE
[BUG] [oC10] Can't navigate to accepted folder

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#1192]
![CleanShot 2023-03-21 at 16 25 15](https://user-images.githubusercontent.com/214010/226655678-4345bf17-ddc2-4065-8b18-c35b23d0dbcf.png) | ![CleanShot 2023-03-21 at 16 25 09](https://user-images.githubusercontent.com/214010/226655723-555bdbfb-dcf6-429b-8580-5776adb849e8.png)
-- | --
Shared with me ⚠️ | Shared by me 👍 

### Client

**ownCloud app version:**

```
ownCloud beta version 12.0 build 252
(app: 1e87b9ed, sdk: 3010676)
```

@felix-schwarz @jesmrec

**Comment by jesmrec** [comment]
Done within https://github.com/owncloud/ios-app/pull/1162#issuecomment-1531146105 (fix no. 48)
