### ISSUE TITLE
[BUG] Cannot add other accounts, cannot authenticate with other user

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/ios-app#1199]
Using a clean, fresh install.

### Steps to reproduce
1. Open app, add account, authenticate via OIDC
2. hit "+" icon again to add another account, follow steps

### Expected behavior
At some point, I want to authenticate as another user to be able to add this account 

### Actual behavior
The integrated browser tab opening the instance login form closes immediately because I am still authenticated with the first account. It is not ale to add the other account, even after closing the app entirely.

### Client
**iOS version:** Beta 12.0 build 255

**Comment by NannaBarz** [comment]
Can be fixed with branding parameter

**Comment by michaelstingl** [comment]
Known limitation with Keycloak setups. Nothing can be done in the iOS app:

- https://github.com/owncloud/enterprise/issues/5678

Those screenshots illustrate the problem:
- https://github.com/owncloud/docs-server/issues/938#issuecomment-1508523827
