### ISSUE TITLE
[BUG] Unshare an incoming share?

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/ios-app#1204]
### Steps to reproduce
1. Make sure to have an accepted, incoming share
2. Go to Shares -> Shared with me
3. Tap on three dots menu icon of accepted share

There is an option to un-share this file. While this is an incoming share, why am I able to un-share this file? Either this is a bug (I cannot un-share an incoming share) or it needs to be renamed to "Decline share"

**Comment by hurradieweltgehtunter** [comment]
Add: Tapping on it moves the share into section "Declined shares". Therefore my guess is, it needs to be renamed to "Decline share" ("Freigabe ablehnen")

**Comment by michaelstingl** [comment]
@tbsbdr what is the correct wording? How does it look in latest web UI?

/cc @jesmrec

**Comment by hurradieweltgehtunter** [comment]
![grafik](https://user-images.githubusercontent.com/16665512/236168213-4665dbe5-b8ea-4723-a7bb-e7ddfcfe0d3a.png)

**Comment by jesmrec** [comment]
@hurradieweltgehtunter this is how the latest build looks like:

<img width="340" alt="Screenshot 2023-05-23 at 13 24 15" src="https://github.com/owncloud/ios-app/assets/14894746/014f1025-2c39-4de6-82a7-28f9dccb6da5">

is this ok?
