### ISSUE TITLE
[FEATURE REQUEST] - Shortcuts Path Parameter is Selectable

### ISSUE THREAD

**Issue by monotok** [owncloud/ios-app#1209]
**Is your feature request related to a problem? Please describe.**
When using the shortcuts application, I am struggling to get it to work with the owncloud app that is connected to my OCIS instance. I can select the account but I can't get the path correct. I have tried various paths such as '/', 'Personal' etc. As the path field is just text it is hard to know the correct value.

**Describe the solution you'd like**
I would like the path parameter to act like the 'account' parameter in the 'Directory listing' action. I would like to select the correct path rather than free form text.

**Describe alternatives you've considered**
None.

**Additional context**
None.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
Pending to fix: https://github.com/owncloud/ios-app/pull/1162#issuecomment-1403340083
