### ISSUE TITLE
[BUG] Space: show loading feedback while loading

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/ios-app#1210]
branded customer client Beta version 12.0 build 255
(app: 51536de3, sdk: 5d81d1e0)

### Steps to reproduce
1. Make sure to have a slow internet connection
2. Go to spaces, select a space
3. Tap on three dots icon or + icon on top right

### Expected behavior
Buttons react to tapping 

OR

Some form of indicator present, that the space is still loading

### Actual behavior
Buttons do not react, no visible feedback, that space still loads

I was confused, because the screen made the impression, the space was fully loaded (space description + image was visible) and I could interact with it. But buttons did not react and file list was empty. I was not able to determine, that the space was still loading.
While I was waiting a little longer, the files suddenly appeared. Then, the buttons and everything were working as expected.

**Comment by jesmrec** [comment]
Which build did you test? we had a [report](https://github.com/owncloud/ios-app/pull/1162#issuecomment-1410298361) (already fixed) in which, if the user does not have permissions (`Viewer`), some options like `+` were displayed with no action. Maybe related with your finding.

About the bad network performance, i've simulated with the "Network link conditioner" and i could not reproduce such problems, beyond the latency.

I used build 257 with `9f741369`

Are that the one on your side?

**Comment by hurradieweltgehtunter** [comment]
branded customer build Beta version 12.0 build 255
(app: 51536de3, sdk: 5d81d1e0)

**Comment by hurradieweltgehtunter** [comment]
Clicking on the + icon showed "Loading..."

**Comment by felix-schwarz** [comment]
Please re-try with the latest TestFlight build:

The old sharing UI sent a request to the server each time you open this menu, to determine the number of links and shares for an element. The new sharing UI only sends a request when you select "Sharing".

**Comment by michaelstingl** [comment]
@hurradieweltgehtunter could you re-check?

**Comment by hurradieweltgehtunter** [comment]
TestFlight is still showing the 12.0 build (255)

**Comment by michaelstingl** [comment]
> TestFlight is still showing the 12.0 build (255)

No, we're in public App Store now:

https://apps.apple.com/app/id1669248219

```
ByCS-Drive beta version 12.0 build 1389 (Thu Jun  1 12:59:40 UTC 2023)
(app:  - experimental/12.0@7563cac, sdk: v12.0-beta.1-7-g45ba1f3 - @45ba1f3)
```

**Comment by hurradieweltgehtunter** [comment]
Thx @michaelstingl 

@felix-schwarz works! Looks very nice
