### ISSUE TITLE
[BUG] Sidebar menu blocked by keyboard

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/ios-app#1212]
### Steps to reproduce
1. Go to personal space
2. Tap on search bar (keyboard opens)
3. Tap on sidebar icon to open the sidebar

### Expected behavior
keyboard gets closed, sidebar is fully visible

### Actual behavior
![IMG_A6508E3F893D-1](https://user-images.githubusercontent.com/16665512/236431784-417c22f7-f233-4523-8551-60feaaa0dc2d.jpeg)

ownCloud  Beta version 12.0 build 258
(app: 9f741369, sdk: aeb1516)

**Comment by jesmrec** [comment]
Related: https://github.com/owncloud/ios-app/pull/1162#issuecomment-1380055033
