### ISSUE TITLE
[BUG] Can't open Owncloud files using iPad OS Files app

### ISSUE THREAD

**Issue by lucastherondel** [owncloud/ios-app#1223]
### Steps to reproduce
1. Open the Files app on iPad
2. Go to ownCloud on the left panel
3. Access to the files on the right panel

### Expected behavior
Files and folders should be appearing on the right, and we would be able to open them.

### Actual behavior
No files or folders are appearing, instead this error message (translated from French) :

"Content unavailable"
"Can't display folder content because of an unknown error"
"Retry"

![owncloud_ipad_error](https://github.com/owncloud/ios-app/assets/125285185/67a390a8-f787-4507-9a74-c2c8b5e253ef)

### Client
**iOS version:**
iPadOS 16.3.1

**ownCloud app version:**
12.0

**Device model:**
iPad Pro 11" 2nd gen

**Comment by felix-schwarz** [comment]
@lucastherondel Thanks for filing this issue and providing logs.

Could you please install [TestFlight build 269](https://testflight.apple.com/join/MaKmwsqZ) and check if the issue is solved?

**Comment by webzit** [comment]
> Could you please install [TestFlight build 269](https://testflight.apple.com/join/MaKmwsqZ) and check if the issue is solved?
Latest TestFlight build seems to be 266. Perhaps 269 hasn‘t been pushed or still in review?

**Comment by lucastherondel** [comment]
> > Could you please install [TestFlight build 269](https://testflight.apple.com/join/MaKmwsqZ) and check if the issue is solved?
> 
> Latest TestFlight build seems to be 266. Perhaps 269 hasn‘t been pushed or still in review?

Hi, just installed build 269 (12.0.2) and **it seems to work fine**, I can open Powerpoint, Excel, Word and .pdf files like before the bug. I'm not getting any error message.

**Comment by felix-schwarz** [comment]
@lucastherondel Thanks for testing and giving such quick feedback!

@webzit The build wasn't made available for all TestFlight groups until a few minutes ago.
