### ISSUE TITLE
[FEATURE REQUEST] Recent files view

### ISSUE THREAD

**Issue by gennaios** [owncloud/ios-app#1225]
**Is your feature request related to a problem? Please describe.*
Many apps such as iOS Files or Nextcloud offer a view for recently modified files. Deleted files plus emptying trash would be nice too. 

**Describe the solution you'd like**
I plus likely many store a large amount of files. A recent view to either share, access, or other i think is really necessary. 

**Describe alternatives you've considered**

**Additional context**
Files app, Nextcloud, and many apps offer some bottom tabbed toolbar. Perhaps recent, file, favorites, photos, and config or something  similar would make such more frequently used views more easily accessible. 

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by michaelstingl** [comment]
Regression in the 12.0?

![CleanShot 2023-06-19 at 09 47 48](https://github.com/owncloud/ios-app/assets/214010/0d03e795-4447-4ad0-903b-f18c56953b23)

(it used to be in the "Quick Access" section

**Comment by gennaios** [comment]
It's also missing on OCIS but perhaps that's known and planned.

**Comment by michaelstingl** [comment]
fixed in 12.0.2 release
