### ISSUE TITLE
[BUG] Resource name on top abbreviated/too short

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/ios-app#1229]
### Steps to reproduce
1. Go to any folder/space

### Expected behavior
The resource name in the topbar is a help to find your way around the app

### Actual behavior
The resource name is abbreviated in a way, that I do not know, which resource I'm currently in. It's useless in this way

![IMG_8636](https://github.com/owncloud/ios-app/assets/16665512/3ca9d52e-4f15-49d8-83f4-67033077a5c1)

### Client
**iOS version:** branded customer Beta version 12.0 build 1389 (Thu Jun  1 12:59:40 UTC 2023)
(app:  - experimental/12.0@7563cac, sdk: v12.0-beta.1-7-g45ba1f3 - @45ba1f3)

### Tell us what could be improved:
Since the resource name is shown in the footer, remove it from the top bar
OR
Make more room in the top bar - but this seems not practicable

**Comment by michaelstingl** [comment]
> It's useless in this way

Useful on bigger devices or in landscape mode. Ugly on small devices.

You can also see the full name of the resource in the "more" menu on the top-right.

**Comment by hurradieweltgehtunter** [comment]
> > It's useless in this way
> 
> Useful on bigger devices or in landscape mode. Ugly on small devices.

Ok, good point. I tested on iPhone
