### ISSUE TITLE
[BUG] Can't open Folder using iOS Files app (iPhone)

### ISSUE THREAD

**Issue by webzit** [owncloud/ios-app#1237]
### Steps to reproduce
1. Open the Files app on iPhone
2. Go to ownCloud on the left panel
3. Browse to a specific folder containing 93 Audio files (*.m4a) on the right panel

### Expected behavior
93 audio files should be appearing on the right, and I would be able to open them.

(A separate folder containing 93 video files works fine. The audio folder contains the audios extracted from these videos.)

### Actual behavior
No files or folders are appearing, instead this error message (translated from German) :

"_Content Unavailable.
The folder contents could not be displayed because of an unknown error.
Try Again_"

![IMG_E42F8649D8CF-1](https://github.com/owncloud/ios-app/assets/79612125/92dc508a-f4f4-4790-9b3f-7d4661f59d83)

### Client
**iOS version: 16.5.1**

**ownCloud app version: 12.0.2 build 270**

**Device model: iPhone 13**

### Server configuration
**Web server: Nginx Proxy Manger (v 2.10.3)**

**ownCloud version: 3.1.0-next.2+038520778 Web-Client-Version 7.0.1**

### Logs
ownCloud log sent to: 
<img width="161" alt="Bildschirmfoto 2023-07-02 um 23 10 27" src="https://github.com/owncloud/ios-app/assets/79612125/72c80c17-d0c8-4c11-92c4-89e9f75ddefd">

**Comment by michaelstingl** [comment]
> ### Logs
> ownCloud log sent to: <img alt="Bildschirmfoto 2023-07-02 um 23 10 27" width="161" src="https://user-images.githubusercontent.com/79612125/250401018-72c80c17-d0c8-4c11-92c4-89e9f75ddefd.png">

Thanks a lot!

ownCloud team can access it here:
- https://cloud.owncloud.com/f/6025334

**Comment by michaelstingl** [comment]
Sounds like a similar problem reported in central.owncloud.org:
- https://central.owncloud.org/t/files-app-on-ios-is-stuck-on-loading-for-owncloud/44201

**Comment by webzit** [comment]
Thank you very much. In comparison to the bug report posted on the forum, I don't see "_loading spinner and never anything else_" but the above mentioned error message ("_Content Unavailable. The folder contents could not be displayed because of an unknown error. Try Again_")

**Comment by felix-schwarz** [comment]
Thanks for the log file. Unfortunately it doesn't cover the time period shown in the screenshot and the log ends before the only `PROPFIND` request sent by the File Provider in that log file completes.

`Content Unavailable. The folder contents could not be displayed because of an unknown error. Try Again` can be an indication of
- an error in client/host communication (=> _could_ be related to nginx configuration also)
- the File Provider process crashing or being terminated (f.ex. because it consumed more memory than allowed by iOS)

**Comment by webzit** [comment]
Thank you Felix for your comment. I provided 
![](https://user-images.githubusercontent.com/79612125/250401018-72c80c17-d0c8-4c11-92c4-89e9f75ddefd.png)
 with more detailed log files.

**Comment by marcomasser** [comment]
Hi, I’m the one who wrote that forum post @michaelstingl [mentioned above](https://github.com/owncloud/ios-app/issues/1237#issuecomment-1617644160) and just wanted to mention that what I’m seeing is not restricted to a specific folder. Instead, it seemingly has to do with how many times I navigate into a folder.

And as @webzit mentioned: I have not seen an error message like the one in the original post. It just spins for me.

Just FYI 🙂

**Comment by felix-schwarz** [comment]
@marcomasser Thanks for the info. Let's continue the discussion over at central.owncloud.org then.

**Comment by michaelstingl** [comment]
@marcomasser @webzit seems mixing-up the issues wasn't the best idea. I opened 2 new issues to follow-up individually:
- https://github.com/owncloud/ios-app/issues/1239
- https://github.com/owncloud/ios-app/issues/1240

**Comment by felix-schwarz** [comment]
Closing this issue as discussion continues in #1245.
