### ISSUE TITLE
[BUG] 12.0.2 (270) “recents” folder lists 300 items in alphabetical order

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#1243]
(Ticket#202307047000126)

---

User feedback:

> the “recents” folder lists 300 items in alphabetical order, which is useless… if I rearrange by date this affects all other folders too, which is rather annoying: recents should be arranged by date by default, independently of other folders arrangement.

@jesmrec could you verify?

**Comment by jesmrec** [comment]
that's right, `Recents` section is sorted alphabetically, so we need here a change of behaviour.

**Comment by michaelstingl** [comment]
@hosy @felix-schwarz 12.0.3 doable?
