### ISSUE TITLE
[BUG] Sebastian's issue issue with iOS Files app

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#1245]
(Ticket#202306297000217)

---

Sebastian reported:

> I would like to take this opportunity to report that the OwnCloud app works great, but often in the Files app is displayed "Content not available", although they were saved for offline. After several folder changes, the files sometimes appear again.
> 
> ![image0](https://github.com/owncloud/ios-app/assets/214010/0d39dd6b-a83a-4f31-91f3-58dbf958c4ee)

Sebastian, please help us better understand your problem by uploading app debug logs (including HTTP) and screen recording from the same time here:
- ~~https://cloud.owncloud.com/s/C3vFcdgzDKc3vDJ~~
- https://cloud.owncloud.com/s/mzWYgusX30n2ywN

Here you can find more information:
- https://doc.owncloud.com/ios-app/12.0/appendices/troubleshooting.html#capturing-app-debug-logs

ownCloud team can access internally here:
- https://cloud.owncloud.com/f/6030163

**Comment by webzit** [comment]
Thank you very much, I have uploaded in accordance with your email, a screen recording video, the logs of OCIS (Client), OCIS (Server) as well as nginx proxy manager.

**Comment by felix-schwarz** [comment]
@webzit Thanks for help. Please try the new [TestFlight](https://testflight.apple.com/join/MaKmwsqZ) build 273 and let me know if it fixes the issue for you.

**Comment by webzit** [comment]
> @webzit Thanks for your help. Please try the new [TestFlight](https://testflight.apple.com/join/MaKmwsqZ) build 273 and let me know if it fixes the issue for you.

Unfortunately not. I have already uploaded new logfiles using build 273.

**Comment by webzit** [comment]
Minor update: With the latest TestFlight beta (v274) the problem still persists. Also, owncloud iOS app crashes as soon as you start an audio or video file within the app with v274.

**Comment by michaelstingl** [comment]
> Minor update: With the latest TestFlight beta (v274) the problem still persists. Also, owncloud iOS app crashes as soon as you start an audio or video file within the app with v274.

Please upload v274 screen recording + logs

**Comment by webzit** [comment]
> Please upload v274 screen recording + logs (including the crash)

I have uploaded a v274 screen recording + logs (including the crash). Please make sure to delete the screen recordings and logs once this issue is solved.

**Comment by felix-schwarz** [comment]
@webzit Thanks for the logs and screen recording. I have addressed the issue that the contained crash log for the app pointed to and it should no longer occur in build 275.

I'm still looking into the FileProvider issue.

**Comment by felix-schwarz** [comment]
@webzit Please have a look at (iOS) `Einstellungen > Datenschutz & Sicherheit > Analyse & Verbesserungen > Analysedaten`, if there is any file starting with `ownCloud File Provider-` (f.ex. `ownCloud File Provider-2023-08-04-123456.ips`). It appears the File Provider is crashing on your device - and that crash log file should allow us to pinpoint the location of the crash in the code.

If you find such a crash log file on your device, please upload it here:
- https://cloud.owncloud.com/s/C3vFcdgzDKc3vDJ

**Comment by webzit** [comment]
Thank you, Felix. Unfortunately the link you provided returns an 404 error page.

(It seems that the issue also persists in V276.)

**Comment by michaelstingl** [comment]
> Unfortunately the link you provided returns an 404 error page.

Upload link expired. Here is a new one:
- https://cloud.owncloud.com/s/mzWYgusX30n2ywN

**Comment by felix-schwarz** [comment]
@webzit Thanks for the log file! I took a look and noticed it is still with build 275, showing the crash that build 276 should fix. Did you get any more recent crash logs for File Provider, with build 276?

**Comment by webzit** [comment]
Unfortunately FileProvider keeps crashing with build 276. Please let me know if I should provide further log files. Many thanks.

**Comment by webzit** [comment]
> @webzit Thanks for the log file! I took a look and noticed it is still with build 275, showing the crash that build 276 should fix. Did you get any more recent crash logs for File Provider, with build 276?

Thank you Felix. It seems as no new logfile has been created with v276. The latest is „OwnCloud FileProvider-2023-08-03-…“ (v275). Or do you want me to upload a logfile from within the OwnCloud-App itself?

**Comment by michaelstingl** [comment]
> Thank you Felix. It seems as no new logfile has been created with v276. The latest is „OwnCloud FileProvider-2023-08-03-…“ (v275).

This is good news! 🎉 Means it didn't crash with 276. Unfortunately, we never managed to add FileProvider crashlogs in the apps debug log, similar as we do with the app crash logs…

Did you ever experience again the "stuck" behaviour with 276?

**Comment by webzit** [comment]
That‘s great news! Unfortunately the „stuck“ behavior remains with 276.

**Comment by webzit** [comment]
Unfortunately, two new FileProvider logfiles have been written. I have uploaded them.

**Comment by felix-schwarz** [comment]
Thanks for the logs @webzit!

The crash on 31.08.2023 seems to have happened due to the File Provider running out of memory (iOS only allows File Providers to use a few megabytes - and terminates them if they request more). This can happen if a folder contains so many items that the File Provider can't fit their metadata anymore. Do you have folders in that account with >800-1000 files?

The crash on 25.08.2023 points to an as-of-yet unknown issue I'm looking into further.

**Comment by webzit** [comment]
Thank you. No, I don't have a folder with that many files.
