### ISSUE TITLE
Folder view is pushed multiple times onto navigation stack if user taps too fast on the folder item

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#126]
### Steps to reproduce
1. Login 
2. Locate a folder in the list of files / folders
3. Tap fast multiple times on the folder item

### Expected behaviour
New view with folder contents is shown once.

### Actual behaviour
For every tap, new instance of the folder view is created and pushed. Then you have to click button multiple times to return to the top-level view you came from

### Client
iOS12

**ownCloud app version:** latest master

**Device model:** iPhone 8

**Comment by pablocarmu** [comment]
Someone was able to reproduce it? @jesmrec @mneuwert @felix-schwarz @javiergonzper @michaelstingl

**Comment by jesmrec** [comment]
not reproducible in my side. @mneuwert is it still reproducible with the latest `master`?

**Comment by mneuwert** [comment]
@jesmrec @pablocarmu not reproducible for me either.

**Comment by jesmrec** [comment]
let's close then... will reopened if someone reproduce it again
