### ISSUE TITLE
[BUG] Unable to access files from "Files" app

### ISSUE THREAD

**Issue by lucastherondel** [owncloud/ios-app#1262]
Hello, I've just tried the Testflight build 273. I'm unable to access my Owncloud files using the Ipad native "Files" app.

### Steps to reproduce
1. Open the Files app
2. Go to Owncloud location on the left column

### Expected behavior
My files and folders should be displayed on the right.

### Actual behavior
My files and folders are sometimes displayed on the right, but it only lasts a couple of minutes. If I open another app, go to another location on the left pane like "On my iPad" or just let the iPad go idle, when I go back to the Files app, my files are gone even if I'm on the Owncloud location on the left column.

### Client
**iOS version:**
16.5.1
**OwnCloud app version:**
12.0.2 and I tried Testflight build 273
**Device model:**
iPad Air 3rd gen, I also have the same issue on iPad Pro 11" 2nd gen
### Server configuration
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7
**ownCloud version:**
10.1.0.4

[ownCloud_24_juil._2023_à_10_25_38.log.txt](https://github.com/owncloud/ios-app/files/12143555/ownCloud_24_juil._2023_a_10_25_38.log.txt)

Thank you for your help.

**Comment by beatemaria** [comment]
Hello,

I'm not sure if it's the same problem: I can access the files via the Files-App from iOS, but after a while (about 15-30 minutes) opening a file or even a folder becomes very slow. Sometimes it stops. 
When I create a new account in the ownCloud-App, everything is fast again in the Files-App, but it will slow down. 

I'm using the newest version of iOS (16.6) and the newest available version of the ownCloud-App (12.0.2). I have an IPad Pro 11'' 4th Gen.

Best wishes and thank you for your help!

**Comment by michaelstingl** [comment]
@beatemaria please open an individual issue

**Comment by michaelstingl** [comment]
@lucastherondel please help us better understand your problem by uploading app debug logs (including HTTP) and screen recording from the same time here:
- https://cloud.owncloud.com/s/NKJ3QuPNhqVPF5P

Here you can find more information:
- https://doc.owncloud.com/ios-app/12.0/appendices/troubleshooting.html#capturing-app-debug-logs

ownCloud team can access internally here:
- https://cloud.owncloud.com/f/6047606

**Comment by michaelstingl** [comment]
@lucastherondel BTW please test with TestFlight build 274:
- https://testflight.apple.com/join/MaKmwsqZ

**Comment by lucastherondel** [comment]
Hello I just uploaded the log files from when I was running Testflight build 273. Afterwards I tested the 274 build and the bug seems to have disappeared for now. I'll let you know if I encounter the problem again

**Comment by felix-schwarz** [comment]
Thanks for your help. Happy build 274 fixed the issue for you. If that changes again, please re-open the issue. I'm closing it for now.
