### ISSUE TITLE
[BUG] Crash in ownCloud File Provider

### ISSUE THREAD

**Issue by marcomasser** [owncloud/ios-app#1266]
I noticed a crash in the file provider extension because Files.app showed an error about content not being available (sorry, I forgot to take a screenshot and don’t remember the exact wording). I haven’t come across this before, so I looked into the analytics section of Settings.app and found one crash log: [ownCloud File Provider-2023-08-01-221518.ips.zip](https://github.com/owncloud/ios-app/files/12247919/ownCloud.File.Provider-2023-08-01-221518.ips.zip)

### Steps to reproduce
Unknown. This only happened once so far and it’s not clear what triggered it.

### Client
**iOS version:** 16.5.1 (iPadOS, actually)

**ownCloud app version:** 12.0.3 (274)

**Device model:** iPad 8th generation (iPad11,6)

**Comment by michaelstingl** [comment]
> **ownCloud app version:** 12.0.3 (274)

Another? crash was fixed in the 275 build:
- https://github.com/owncloud/ios-app/issues/1245#issuecomment-1659684841

Maybe it solves your crash too?

**Comment by marcomasser** [comment]
Thanks for the hint, I will make sure that build is installed and report back in case this comes up again. But as I don’t know how to reproduce the crash, it might just not happen again. Feel free to close this issue and I’ll reopen it if necessary.

**Comment by felix-schwarz** [comment]
Thanks for sharing the crash log. It pointed to a strange issue where iOS invokes a FileProvider method with a `nil` parameter for which `nil` values aren't allowed, leading to an exception in another system call that doesn't allow a `nil` parameter.

In build 276 (currently processing in App Store Connect, should be available within an hour via TestFlight), I added a mitigation for that case, so iOS using a `nil` parameter where it shouldn't should no longer lead to a crash.

**Comment by marcomasser** [comment]
Oh nice, thanks!
