### ISSUE TITLE
[FEATURE REQUEST] access calender and contact book via iOS app

### ISSUE THREAD

**Issue by nemethstarproductions** [owncloud/ios-app#1268]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A new tab or menu options to access the calender and contact book of a user via the iOS app. For both users on a community edition server and Infinite Scale.

**Comment by michaelstingl** [comment]
> A new tab or menu options to access the calender and contact book of a user via the iOS app.

Works nicely in the system apps:
- https://doc.owncloud.com/webui/next/classic_ui/pim/sync_ios.html

Add a hint on the settings screen or iOS docs?

**Comment by michaelstingl** [comment]
> and Infinite Scale.

Discussions about CalDAV (Calendars) / CardDAV (Contacts) in Infinite Scale:
- https://github.com/owncloud/ocis/issues/6504
- https://central.owncloud.org/t/owncloud-infinite-scale-and-caldav-calendars-carddav-contacts/29794
