### ISSUE TITLE
[QA] opening PDF via 'open-with-Collabora` fails with "unsupported URL"

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ios-app#1271]
Seen with server core 10.3.0 and rchdocuments 4.0.0-rc.3 and iOS app 12.0.2 at @cdamken iphone

The server has the richdocuments URL fix added via patch https://patch-diff.githubusercontent.com/raw/owncloud/core/pull/40958.diff
The server is configured with /app/list having
```
{
  "mime-types": [
    {
      "mime_type": "application/pdf",
      "app_providers": [
        {
          "name": "Collabora",
          "icon": "https://www.collaboraoffice.com/wp-content/uploads/2019/01/CP-icon.png"
        }
      ],
      "ext": "pdf",
      "name": "PDF",
      "description": "PDF document",
      "default_application": "Collabora"
    },
    {
      "mime_type": "application/vnd.oasis.opendocument.text",
...
```
* Connect iPhone to ownCloud server with normal user login
* Navigate to the 'Learn more about ownCloud`folder
* Click open te 3 dots menu of one of the PDFs.
* Click on the (very large) collarboa icon near `Ope...` (OKayish?)
![grafik](https://github.com/owncloud/ios-app/assets/1108546/b758f118-bff4-4139-859d-95770cd04ab5)
----
* An error message appears "unsupported URL":
![grafik](https://github.com/owncloud/ios-app/assets/1108546/1abaf341-854a-4529-b4bf-293e68952b10)
----

The error is only seen with iOS, desktop client and android can open PDFs via web just fine with Collabora on this test instance.

Server log:
```
{"reqId":"ZPBzp1Ca59M9YmADKjSaygAAAAM","level":1,"time":"2023-08-31T11:04:08+00:00","remoteAddr":"87.128.78.100","user":"--","app":"OC\\User\\Session::loginInOwnCloud","method":"POST","url":
"\/login?redirect_url=%252Findex.php%252Fapps%252Foauth2%252Fauthorize%253Fresponse_type%253Dcode%2526redirect_uri%253Doc%253A%252F%252Fios.owncloud.com%2526client_id%253Dmxd5OQDk6es5LzOzRvi
dJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1%2526state%253D37295FFF-157B-4644-AE3E-7A6DFC66266B","message":"login bob using \"password\" login type"}
{"reqId":"ZPBzqVCa59M9YmADKjSa0QAAAAM","level":1,"time":"2023-08-31T11:04:10+00:00","remoteAddr":"87.128.78.100","user":"bob","app":"oauth2","method":"POST","url":"\/index.php\/apps\/oauth2\/authorize?response_type=code&redirect_uri=oc:\/\/ios.owncloud.com&client_id=mxd5OQDk6es5LzOzRvidJNfXLUZS2oN3oUFeXPP8LpPrhx3UroJFduGEYIBOxkY1&state=37295FFF-157B-4644-AE3E-7A6DFC66266B","message":"An authorization code has been issued for the client \"iOS\"."}
{"reqId":"93D8B2A9-738C-4131-97FB-449676BA3278","level":1,"time":"2023-08-31T11:04:10+00:00","remoteAddr":"87.128.78.100","user":"--","app":"oauth2","method":"POST","url":"\/index.php\/apps\/oauth2\/api\/v1\/token","message":"An authorization code has been used by the client \"iOS\" to request an access token."}
{"reqId":"7A8F0B7F-233E-4DE1-B0B6-CC1FDD18FB8A","level":1,"time":"2023-08-31T11:04:10+00:00","remoteAddr":"87.128.78.100","user":"--","app":"OC\\User\\Session::loginInOwnCloud","method":"GET","url":"\/ocs\/v2.php\/cloud\/capabilities?format=json","message":"login bob using \"OCA\\OAuth2\\AuthModule\" login type"}
{"reqId":"5617ECEE-E3CB-4D24-8748-54CC1DE32056","level":1,"time":"2023-08-31T11:04:11+00:00","remoteAddr":"87.128.78.100","user":"--","app":"OC\\User\\Session::loginInOwnCloud","method":"GET","url":"\/ocs\/v2.php\/cloud\/capabilities?format=json","message":"login bob using \"OCA\\OAuth2\\AuthModule\" login type"}
{"reqId":"5007224B-BFE5-436D-B306-FE0DC8D79654","level":1,"time":"2023-08-31T11:04:17+00:00","remoteAddr":"87.128.78.100","user":"--","app":"OC\\User\\Session::loginInOwnCloud","method":"GET","url":"\/ocs\/v2.php\/cloud\/capabilities?format=json","message":"login bob using \"OCA\\OAuth2\\AuthModule\" login type"}
{"reqId":"MKBWQKTB0lMslI9qc3WP","level":1,"time":"2023-08-31T11:05:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"--","url":"--","message":"Invalidating tokens older than 2023-08-31T10:45:01+00:00"}
```

**Comment by jnweiger** [comment]
@cdamken can you grab logging from your iPhone? 
https://doc.owncloud.com/ios-app/next/appendices/troubleshooting.html#capturing-app-debug-logs

**Comment by michaelstingl** [comment]
Please make sure you use the latest 12.0.3 TestFlight:
- https://owncloud.com/beta-testing/#ios

Or the final 12.0.3 when it arrives in the public App Store later today…
- https://apps.apple.com/app/id1359583808

**Comment by michaelstingl** [comment]
@jnweiger test server with credentials ?

**Comment by michaelstingl** [comment]
> The server has the richdocuments URL fix added via patch https://patch-diff.githubusercontent.com/raw/owncloud/core/pull/40958.diff

- https://github.com/owncloud/core/pull/40958
- https://github.com/owncloud/enterprise/issues/5994

**Comment by jnweiger** [comment]
> @jnweiger test server with credentials ?

sent in chat

**Comment by michaelstingl** [comment]
Works fine in `12.0.3`, available in the App Store ✅ 

![Simulator Screenshot - iPhone SE (3rd generation, iOS 16 4) - 2023-09-01 at 15 33 35](https://github.com/owncloud/ios-app/assets/214010/62ee061a-b5ce-41e1-a5ba-af092e8cce54) | ![Simulator Screenshot - iPhone SE (3rd generation, iOS 16 4) - 2023-09-01 at 15 34 07](https://github.com/owncloud/ios-app/assets/214010/62f42747-b795-4e06-a1b4-302f7feba667) | ![Simulator Screenshot - iPhone SE (3rd generation, iOS 16 4) - 2023-09-01 at 15 35 20](https://github.com/owncloud/ios-app/assets/214010/ada0a8bb-f1e5-494c-8d24-48b3a8ba679d)
-- | -- | --

```
ownCloud release version 12.0.3 build 282 (Tue Aug 29 16:54:13 CEST 2023)
(app: v12.0.3 - milestone/12.0.3@40dfc92f, sdk: v12.0.3 - develop@740b63e)
```
