### ISSUE TITLE
App crashes when adding second bookmark in the same server

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#129]
### Steps to reproduce
1. Install the app
2. Add a bookmark
3. Add another bookmark (same server as 2.)
4. Click in the second bookmark

### Expected behaviour
Browsing into 2nd bookmark

### Actual behaviour
App crashes

### Client
**iOS version:** 12.0

**ownCloud app version:** 10.0.10

**Device model:** iPhoneX

**Comment by felix-schwarz** [comment]
Thanks! I've not been able to reproduce this issue with the latest version in `feature/fileprovider`. Can you reproduce it with that version?

**Comment by jesmrec** [comment]
Checked and fixed. Thanks @felix-schwarz
