### ISSUE TITLE
[FEATURE REQUEST] Preserve file extension when creating new files (Document Scanner, App Provider etc)

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#1292]
**Is your feature request related to a problem? Please describe.**
We received user feedback, that users changed the file extension when creating new files (Document Scanner, App Provider etc), so they experienced issues later when they tried to work with this files.

**Describe the solution you'd like**
In cases, where users create new files of a specific file type, the input field should not allow to change or remove the file extension. Advanced users could always change the file extension later with the "Rename" file action.

**Describe alternatives you've considered**
n.a.

**Additional context**
![IMG_0216](https://github.com/owncloud/ios-app/assets/214010/e0f43b72-0040-4f12-baf9-0675b707b053) | ![IMG_0218](https://github.com/owncloud/ios-app/assets/214010/8e0283bd-37e5-483f-9c6c-47a5e33c70f0)
-- | --
➕ > `New document` | ➕ > `Scan document`

```
ownCloud release version 12.0.3 build 282 (Tue Aug 29 16:54:13 CEST 2023)
(app: v12.0.3 - milestone/12.0.3@40dfc92f, sdk: v12.0.3 - develop@740b63e)
```

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by michaelstingl** [comment]
> **Describe alternatives you've considered**
> n.a.

@felix-schwarz proposed a simpler implementation, and only display a warning message that asks for user confirmation.

…and make document scanner filename pre-selected, similar as the "New document" behavior.

**Comment by felix-schwarz** [comment]
I eventually ended up implementing a re-usable `UITextField` subclass that can directly enforce a file extension by dropping all changes and selection to the file extension portion: https://github.com/owncloud/ios-app/pull/1298

**Comment by jesmrec** [comment]
JFYI: as was commented, using a notification when process ends could be a solution, but, notifications are not enabled by default. For example, check the following scenario out:

1. Copy a file in root inside a folder
2. Repeat the same process, that means, the file will try to be copied into a folder that contains another file with the same name

Then...

![Screenshot 2023-11-20 at 09 39 33](https://github.com/owncloud/ios-app/assets/14894746/384865e1-6ccb-467e-b52e-899f1a80322e)

errors in the same track will trigger the same notification.

**Comment by jesmrec** [comment]
Done. Ready to 12.1
