### ISSUE TITLE
[FEATURE REQUEST] "Save to ownCloud" action in iOS Share Sheet

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#1293]
**Is your feature request related to a problem? Please describe.**
We received user feedback about difficulties to find the ownCloud app in the iOS Share Sheet.

**Describe the solution you'd like**
Could we add a "Save to ownCloud" action in iOS Share Sheet?

**Describe alternatives you've considered**
N.a.

**Additional context**

![IMG_0220](https://github.com/owncloud/ios-app/assets/214010/3579c9a7-b387-4e1d-907b-aa4cc0a6fe41)

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by michaelstingl** [comment]
> * [ ] Research (if needed)

@hosy could you qualify?

**Comment by mybuntu-git2** [comment]
Not sure how much user feedback you got but one can order apps in the share sheet and also the files integration makes it extremely easy to have quick actions sharing to specific OC folders.
My suggestion would be to make a small manual on how to handle files integration and share sheet, even if this is not exactly “working on OwnCloud”

**Comment by michaelstingl** [comment]
> sheet, even if this is not exactly “working on OwnCloud”z

Great feedback – thanks! 👍 I'd love to add same Shortcuts examples to the app. I'll open a separate issue for tracking…

**Comment by michaelstingl** [comment]
@hosy what would be your proposal? Estimation?

**Comment by hosy** [comment]
added my estimation: 3M
