### ISSUE TITLE
[File Preview] Send a file to other applications

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#130]
I like the way it's done in the iOS Files app viewer:

| File list | Preview | Send … |
|---|---|---|
| ![2018-10-17 23 57 27](https://user-images.githubusercontent.com/214010/47119070-ceef7a00-d269-11e8-825b-59d13567f4bc.png) | ![2018-10-17 23 57 37](https://user-images.githubusercontent.com/214010/47119071-ceef7a00-d269-11e8-9bc6-689b34ea42e5.png) | ![2018-10-17 23 57 59](https://user-images.githubusercontent.com/214010/47119072-ceef7a00-d269-11e8-9a8a-0e8283428a57.png) |

I also like the clean way it looks in the default "Quick Look" feature:
- https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/quick-look/
- https://developer.apple.com/documentation/quicklook

I think @felix-schwarz said a simple implementation shouldn't be that much effort? (few lines of code?) Is there something available in the system that could be used here easily?

This is part of the epic https://github.com/owncloud/ios-app/issues/68 (File Preview)

**Comment by pablocarmu** [comment]
I think this _open in action sheet_ should be shown in two different ways:

1. Tapping on the 3 dots in the file list view: by doing this, the _more card view_ should show up and then there should be a new action called _open in_. When you tap in this new action, the file should start the download process and once the download finishes, the _open in action sheet_ appears.

2. We should code a new `UIToolbar` in the file's preview view controller and there a new button with the same flow than tapping in the _open in_ action.

**Comment by michaelstingl** [comment]
Yeah, triggering _more card view_ in both cases sounds good 👍 

What would be the effort to add this to the file preview view controller? Would a lightweight "3-dot-only" solution make sense as a first implementation?

**Comment by michaelstingl** [comment]
@pablocarmu awesome 😍 !!

**Comment by jesmrec** [comment]
Done. 

Check improvements here: 

https://github.com/owncloud/ios-app/issues/178
https://github.com/owncloud/ios-app/issues/179
