### ISSUE TITLE
[BUG] Uploads not proceeding - spinning forever

### ISSUE THREAD

**Issue by rmk-ch** [owncloud/ios-app#1323]
Hi
I am having issues with the owncloud IOS app and uploading many files to an OCIS server.

### Steps to reproduce
1. Selecting many files (e.g. 50) in the Iphone Photo app or in the owncloud client (select upload files)
2. Wait
3. Few files are uploaded
4. Upload stops, all files left (under status) are just spinning and show "ausstehend" in the German app (probably something like awaiting in English)
5. Restart app, .... nothing helps

### Expected behavior
Upload would not stop, all files will be uploaded eventually

### Actual behavior
Upload stops, files are not uploaded. No idea, how to continue.

### Client
**iOS version:**
17.2.1
[ownCloud_29.01.2024__21_24_02.log.txt](https://github.com/owncloud/ios-app/files/14145190/ownCloud_29.01.2024__21_24_02.log.txt)

**ownCloud app version:**
Release 12.0.3 Build 282

**Device model:**
Iphone 13 mini

### Server configuration
**ownCloud version:** OCIS 4.0.5
Dockerized under Linux

**Storage backend (external storage):** Local

# Client log highlight

2024-01-29 21:24:53.470000+0100 ownCloud[62527:3809818] [dbug] | [CORE, SyncEngine] processing sync records on lane <OCSyncLane: 0x281b66140, identifier: 1744, tags: {(\n    B4EDA4B131A7428F8390A18DC612E83D,\n    "/Natelbilder/folder/IMG_6188.JPG"\n)}> [OCCore+SyncEngine.m:722|FULL]
2024-01-29 21:24:53.471000+0100 ownCloud[62527:3809818] [dbug] | [CORE, SyncEngine] Budget limit of 3 reached for action category: upload [OCCore+SyncEngine.m:691|FULL]
2024-01-29 21:24:53.471000+0100 ownCloud[62527:3809818] [dbug] | [CORE, SyncEngine] Skipping processing sync record 2068 due to lack of available budget in (\n    all,\n    transfer,\n    upload,\n    "upload-cellular-and-wifi"\n) [OCCore+SyncEngine.m:771|FULL]

**What does this mean? Where is this budget limit coming from?**

**Comment by rmk-ch** [comment]
Hi
Any chance for a comment or a fix? 
What does this upload budget limit mean and how can I change it?

**Comment by rmk-ch** [comment]
@felix-schwarz It seems you have been working on this. Is this expecting to fix the issue? Could we have a release soon? The bug is really annoying.
Welcoming any response! Thanks a lot

**Comment by felix-schwarz** [comment]
@rmk-ch You can check if it fixes your issue by running the [latest TestFlight build](https://testflight.apple.com/join/MaKmwsqZ) containing these changes.

Feedback welcome!

**Comment by felix-schwarz** [comment]
@rmk-ch Did you try the TestFlight build? If yes, did it fix your issue?

**Comment by rmk-ch** [comment]
@felix-schwarz thanks a lot. I have just installed the test flight app on my colleagues device. Testing will follow soon. I'll let you know!

**Comment by rmk-ch** [comment]
Hey @felix-schwarz . First tests were successful! Hundrets of files were uploaded without any issues.
Thank you so much for fixing this!
BR

**Comment by felix-schwarz** [comment]
@rmk-ch Thanks for taking the time to test this build and provide feedback!
