### ISSUE TITLE
[a11y] 11.1.4.1 Use of color

### ISSUE THREAD

**Issue by tschiebel** [owncloud/ios-app#1333]
audit: https://infinite.owncloud.com/s/qSvYucPltEYUhhc

https://github.com/BIK-BITV/BIK-App-Test/tree/main/Pr%C3%BCfschritte/de
https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf

### Menu

- [x] The status of the user is only shown by colored dots. There is
no other option is offered to recognize the status, for example
through a text alternative.
![image](https://github.com/owncloud/ios-app/assets/132444655/e3bce190-1e3d-4df2-8ec9-b5f51796b083)

**Comment by jesmrec** [comment]
Done
