### ISSUE TITLE
[a11y] 11.2.5.3 Label in the name

### ISSUE THREAD

**Issue by tschiebel** [owncloud/ios-app#1340]
audit: https://infinite.owncloud.com/s/qSvYucPltEYUhhc

https://github.com/BIK-BITV/BIK-App-Test/tree/main/Pr%C3%BCfschritte/de
https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf

### Shared with me

- [x] The visual labels of the "Accept" and "Reject" buttons are not included in the accessible
accessible name, as the accessible name is displayed in English.
is output in English.
![image](https://github.com/owncloud/ios-app/assets/132444655/4dda0849-2522-465a-a451-b9f6ea73e6d0)

**Comment by jesmrec** [comment]
done
