### ISSUE TITLE
[BUG] Audio Issues

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#1363]
Bug Report via E-Mail:

Hi, I am consistently having major issues when playing audio files. After leaving the app and reopening to continue playing often multiple files of the current folder are played at the same time which results in an awful mixture. Please consider fixing this bug. 

**ownCloud app version:**
12.2.1 (291)

**Device model:**
iPhone

**Comment by jesmrec** [comment]
@hosy Not able to reproduce. Tried some different scenarios but i couldn't reproduce.
