### ISSUE TITLE
[BUG] Action availability for file in shared folder: Unshare instead of Delete

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/ios-app#1379]
### Steps to reproduce
1. Navigate to a shared folder
2. Upload a file into the shared folder
3. Tap `...`  next to the item

### Expected behavior
The action `Delete` is shown.

### Actual behavior
The action `Delete` is not shown. Instead, `Unshare` is shown, which is not really applicable here.

### Client configuration
Version 12.3, but other releases should be similarly affected.

### Server configuration
ocis, `demo.owncloud.com`

### Cause
A bug in ocis (https://github.com/owncloud/ocis/issues/9933, https://github.com/owncloud/ocis/issues/8455) breaks the client's internal chain of item IDs, so items inside shared folders erroneously are seen as "root" shared items themselves, leading to side effects like the wrong actions being shown to the user. F.ex. `Unshare` (which of course fails) is shown, but `Delete` (which would work and be useful) is not.

### Resolution
This problem should no longer occur as soon as https://github.com/owncloud/ocis/issues/9933 is fixed.

This issue was filed to document the issue and its cause.

**Comment by felix-schwarz** [comment]
Fixed by https://github.com/owncloud/ocis/pull/10172 (verified on https://ocis.ocis.master.owncloud.works/ with `Infinite Scale 6.5.0+fdc61d043 Community`).

**Comment by jesmrec** [comment]
@felix-schwarz if `Delete` option is expected in items inside a share folder, i miss it. I caught the following video from `demo.owncloud.com` and same result in ` https://ocis.ocis.master.owncloud.works/ `:

https://github.com/user-attachments/assets/c2feb2fb-fc20-4869-b2b7-6f3e48371b6d

is something missing?

iPhone XR iOS18.0
v12.3.1

**Comment by felix-schwarz** [comment]
@jesmrec This looks like the folder was shared read-only. Did you share that folder to Katherine with full permissions?

**Comment by jesmrec** [comment]
yeah, that was the permissions... i set the default ones expecting to be granted those ones. 

That's OK for me
