### ISSUE TITLE
File list: portrait mode thumbnails escape cell

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#140]
![2018-10-30 20 36 09](https://user-images.githubusercontent.com/214010/47745652-72865480-dc84-11e8-9b3c-35892ed353b4.png)

---

- https://github.com/owncloud/ios-app/commit/a03260ea7a92640f1df2dd2e008f07a3856e6003 on iPhone 7 Plus running iOS 12.1
- ownCloud 10.0.10

**Comment by michaelstingl** [comment]
Related? https://github.com/owncloud/core/issues/31268

**Comment by pablocarmu** [comment]
addressed here -> https://github.com/owncloud/ios-app/pull/157

**Comment by jesmrec** [comment]
Fixed and merged
