### ISSUE TITLE
Rename: thumbnail glitches

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#141]
| ![2018-10-30 20 36 18](https://user-images.githubusercontent.com/214010/47745897-0bb56b00-dc85-11e8-8713-d695fa79de3d.png) | ![2018-10-30 20 38 53](https://user-images.githubusercontent.com/214010/47745898-0c4e0180-dc85-11e8-9069-66297a083611.png) |
|---|---|
| distorted thumbnail (before view/download) |  no thumbnail (after view/download) | 

---

- https://github.com/owncloud/ios-app/commit/a03260ea7a92640f1df2dd2e008f07a3856e6003 on iPhone 7 Plus running iOS 12.1
- ownCloud 10.0.10

**Comment by michaelstingl** [comment]
Related? https://github.com/owncloud/core/issues/31268

**Comment by pablocarmu** [comment]
I've been looking at this and:
1. The distorted image is because the `contentMode` of the `imageView` was not set to `scaleAspectFit`
2. The no thumbnail is because this method is returning false
```obj-c
- (BOOL)requestImageForSize:(CGSize)requestedMaximumSizeInPoints scale:(CGFloat)scale withCompletionHandler:(void(^)(OCItemThumbnail *thumbnail, NSError *error, CGSize maximumSizeInPoints, UIImage *image))completionHandler
```
So there is no thumbnail image for this image. Also, I've taken a look at the implementation and the `error` in the `withCompletionHandler` is always hardcoded to nil.

this is the call sequence the app does to get the thumbnail from the SDK: 
```Swift
			if item.thumbnailAvailability != .none {
				_ = core!.retrieveThumbnail(for: item, maximumSize: self.thumbnailSize, scale: 0, retrieveHandler: { (error, _, _, thumbnail, _, _) in
					_ = thumbnail?.requestImage(for: self.thumbnailSize, scale: 0, withCompletionHandler: { [weak self] (thumbnail, error, _, image) in
						if error == nil,
							image != nil,
							item.itemVersionIdentifier == thumbnail?.itemVersionIdentifier {
							OnMainThread {
								self?.thumbnailImageView.image = image
							}
						}
					})
				})
			}
```

`image` is nil so it never set up the image.

I've checked if there is some `error` in
```Swift
core!.retrieveThumbnail(for: item, maximumSize: self.thumbnailSize, scale: 0, retrieveHandler: { (error, _, _, thumbnail, _, _) in
```

and there is no signal of error, even the thumbnail is not nil. I'm missing something here or doing the wrong calls @felix-schwarz ?

**Comment by michaelstingl** [comment]
Maybe related: I've seen old iOS app and Android app show thumbnail of already downloaded `*.HEIC`. (of course no thumbnail for remote-only `*.HEIC`) But new iOS app can display downloaded `*.HEIC`, but doesn't display a thumbnail when already downloaded.

**Comment by felix-schwarz** [comment]
Fixed from the SDK side as of 
https://github.com/owncloud/ios-sdk/commit/acc16d7b1ab4b32081f0944857b077b8e8654f64

**Comment by felix-schwarz** [comment]
Just fixed the aspect ratio in the app, too: 
https://github.com/owncloud/ios-app/commit/1a8ddd177b7e1093c3c866a65ce8bd3ba7aaab44

**Comment by pablocarmu** [comment]
Tested with the latest App's master and SDK's develop branches and it's fixed.
@jesmrec when you have time please check it so we can close this

**Comment by jesmrec** [comment]
Current `ios-app/master` :  b73453359c557e74d6bd51254d9de7c2c6ddcac1
Current `ios-sdk/develop` : b36850e8d274a45416080560eec6ad37aede1d41

not compiling together

![screen shot 2019-01-08 at 18 35 16](https://user-images.githubusercontent.com/14894746/50848309-381bf080-1374-11e9-836b-f8eedd9a81d2.png)

**Comment by michaelstingl** [comment]
@felix-schwarz what should be used? `ios-sdk/develop` or `ios-sdk/master` ?
(https://github.com/owncloud/ios-sdk/network)

**Comment by felix-schwarz** [comment]
@jesmrec Yes, the develop branch contains breaking changes as of a few hours ago. If you want to test against the current `ios-app/master`, you should check out `ios-sdk/develop` at `1c597883a824b876a71a5f6caf13aa4d6a99255f`.

Alternatively, you can try with `ios-app/fp-series-2`, which uses the latest from `ios-sdk/develop`. Once the changes from `ios-sdk/develop` have made it to `ios-sdk/master`, I'll extract non-FP-related changes into a separate `ios-app/fix/sdkUpdates` PR.

**Comment by jesmrec** [comment]
Fixed in `features/fp-series-2`
