### ISSUE TITLE
[FEATURE REQUEST] 

### ISSUE THREAD

**Issue by adamrm95** [owncloud/ios-app#1423]
**Is your feature request related to a problem? Please describe.**

Integration of OwnCloud on MacOS finder does not work (Sequoia).

**Describe the solution you'd like**

Seamless integration of OwnCloud into Finder. 

**Describe alternatives you've considered**

**Additional context**

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by hosy** [comment]
If you intend to use ownCloud with macOS Finder, it’s recommended to utilize the desktop application:

https://owncloud.com/desktop-app/
