### ISSUE TITLE
Hint for deleted file stays forever

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios-app#145]
### Steps to reproduce
1. Delete a file/folder on the server
2. Try to view the file/folder in the app

### Expected behaviour
The app tells me the file/folder is deleted. This hint stays a couple of seconds.

### Actual behaviour
This hint stays "forever". Neither a reconnect to the server will cause the hint to disappear.

![img_1700 png](https://user-images.githubusercontent.com/33026403/48089199-29924b00-e204-11e8-9420-80385aac959c.jpg)

### Client
**iOS version:**
12.1
**ownCloud app version:**
Beta Build 79
**Device model:**
iPhone SE

### Server configuration
**ownCloud version:**
10.0.10

**Comment by jesmrec** [comment]
Fixed after 0.4.0
