### ISSUE TITLE
Server non supported - lack of feedback

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#153]
### Steps to reproduce
1. Type an URL of a non-supported server (an ownCloud 8, f. ex)
2. Continue

### Expected behaviour
Error message

### Actual behaviour
No feedback, no message

**Comment by michaelstingl** [comment]
Use similar server check as for the desktop sync client?

https://github.com/owncloud/client/blob/v2.5.1/src/libsync/account.cpp#L463-L471

**Comment by felix-schwarz** [comment]
> I think the SDK should take care of this and return an issue saying that the server is not supported or that there are no auth methods available. @felix-schwarz what do you think?

Thanks for looking into this @pablocarmu. I added:
- a version check to the auto-detection phase that now brings up an error when trying to add an unsupported server version
- a check for the case that no auth methods can be detected, which now brings up an error

**Comment by felix-schwarz** [comment]
> Use similar server check as for the desktop sync client?
> 
> https://github.com/owncloud/client/blob/v2.5.1/src/libsync/account.cpp#L463-L471

The SDK currently only checks the version number. That check was previously only performed when connecting to an existing server bookmark. Now it's also checked during the creation of a new bookmark.
