### ISSUE TITLE
Rename not completed

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#155]
### Steps to reproduce
1. Rename an item with a correct name

### Expected behaviour
File list is refreshed after submitting the new item name

### Actual behaviour
You need to pull2refresh to display the new name

commit: 943565f
iOS12

**Comment by pablocarmu** [comment]
I've made a quick debug session on this and the SDK it's returning the previous name in the query results right after the operation is performed, If we ask (through a swipe down to refresh) for new results, then the SDK provides the item with the new name. 

@felix-schwarz when you find a free spot take a look at this behavior.
