### ISSUE TITLE
Maintenance mode

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#158]
ownCloud server has the choice to set a maintenance mode, so the admin team can deal with different actions by restricting the user access. 

App should deal with such mode correctly

To enable/disable maintenance mode:

```
occ maintenance:mode --on
occ maintenance:mode --off

```
A server in maintenance mode will return the following response against any client request:

```
<?xml version='1.0' encoding='utf-8'?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\ServiceUnavailable</s:exception>
  <s:message>System in maintenance mode.</s:message>
</d:error>
```

inside a  `503 Service Unavailable`

Currently, app is not displaying anything when the server is in maintenance mode, in login stage.
Inside the app, cached content is shown
Download content fails with a non-user-readable message
Files App should support this

**Comment by felix-schwarz** [comment]
Fixed as of https://github.com/owncloud/ios-sdk/pull/35/commits/9b9ca60007dbc77ec11a8a2f8b500b3767aed4a8 and https://github.com/owncloud/ios-app/pull/167/commits/d4ce438f384a26596aad99661fd787cfe5281807:

- While adding bookmarks:
![bildschirmfoto 2018-12-06 um 16 47 12](https://user-images.githubusercontent.com/639669/49594653-aab13f00-f976-11e8-8313-3273a97a9b28.png)

- Logging in to an existing bookmark:
![bildschirmfoto 2018-12-06 um 16 47 19](https://user-images.githubusercontent.com/639669/49594654-aab13f00-f976-11e8-9a6f-63ae6391465d.png)

- While connected:
![bildschirmfoto 2018-12-06 um 16 47 22](https://user-images.githubusercontent.com/639669/49594655-ab49d580-f976-11e8-84d0-9ff44a169b85.png)

**Comment by jesmrec** [comment]
Some comments regarding operations in maintenance mode:

- i noticed that several operations are enqueued (like in offline mode): rename, duplicate, move, to be pushed once maintenance mode is off. Other ones are directly forbidden-503 like delete, create folder and upload. We should unify criteria and make all run with the same behaviour. 

- `Move` operation under maintenance mode, shows the bottom status bar empty

![dec-10-2018 12-44-41](https://user-images.githubusercontent.com/14894746/49730681-6923db00-fc79-11e8-839e-f7e9eb1366c3.gif)

other operations also behaves sometimes in this way, but `Move` is straightforward to reproduce.

**Comment by michaelstingl** [comment]
bottom status bar looks like the "broken state" I also reported in https://github.com/owncloud/ios-app/issues/182 and https://github.com/owncloud/ios-app/issues/179#issuecomment-443499786

**Comment by felix-schwarz** [comment]
@michaelstingl @jesmrec As of the 0d6463b, the status bar should now always show a description for actions. Previously, descriptions were only shown once an action had actually been started.

**Comment by jesmrec** [comment]
Pending stuff:

- Create folder in maintenance mode fails the first time
- Move item with empty message
- "No network" in downloads
- Uploads are not done after disabling maintenance mode 

More details: https://github.com/owncloud/ios-app/pull/190#issuecomment-448588662

**Comment by felix-schwarz** [comment]
@jesmrec These issues are SDK-related and should be addressed by the Sync Engine improvements I'm currently working on:

> * Create folder in maintenance mode fails the first time
> * Move item with empty message
> * Uploads are not done after disabling maintenance mode

This issue is in the app itself:
> * "No network" in downloads

As soon as the SDK API suggested in https://github.com/owncloud/ios-app/issues/179#issuecomment-451407888 is available, this can be addressed for both viewing and Open In in a consistent manner.

In the error case outlined there, the text could then show "Network unavailable" or "Server unavailable" depending on the value of `OCCore.connectionStatus` at the time.

Both the viewer and Open In should also observe the value of `OCCore.connectionStatus` then and retry downloading when the status changes to `online`.

/cc @pablocarmu

**Comment by jesmrec** [comment]
After a review with

app: `ios-app:feature/fp-series-2' : 9a1f808c15cf34dce0f998d82948660afe56808b
sdk: pointed by the app commit above (67bd30c8d3e45a083ce4538e3b66840b5fdb3e07)

> Create folder in maintenance mode fails the first time

Fixed

> Move item with empty message

Fixed

> Uploads are not done after disabling maintenance mode

Fixed 

> "No network" in downloads

Pending to be checked with the improvements regarding network availability https://github.com/owncloud/ios-app/issues/158#issuecomment-451410099

I detected the following behaviour: 

#### Maintenance mode starts with a pull down

1. Set the maintenance mode in core
2. With no refresh in the app, perform any action (create a folder, f.ex.)

Current:  Alert error displayed  and the action will not be recovered when the maintenance mode turns off.

Maintenance status is not detected in the app until a manual refresh by pulling down is done. If some action is done during this time, the current behaviour mentioned above happens.

Expected: First action will trigger maintenance mode and recovers after maintenance mode turns off.

#### Uploads during maintenance mode

1. Upload a bunch of files 
2. While files are being uploaded, turn maintenance mode on

Current: An error alert will be displayed for each file pending to upload. If the number opf pending files is huge, it will bother the user (workaround: kill the app). After disabling maintenance mode, the uploads resume but no status message appears on the bottom.

Expected: A single error or similar to notify the issue. When maintenance mode is turned off, uploads resume and status message on the bottom is there to notify what's going on.

**Comment by felix-schwarz** [comment]
These should all be fixed with the latest commit in #167.

**Comment by jesmrec** [comment]
> Maintenance mode starts with a pull down 

Fixed 

>Uploads during maintenance mode 

Fixed 

The behaviour in maintenance mode is pretty optimal. The latest minor issue i detect is related to the "There is no network" message in preview.

**Comment by jesmrec** [comment]
All stuff fixed an merged, so maintenance mode already supported.
