### ISSUE TITLE
Orientation switch, small glitch

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#160]
To get better the glitch, the ownCloud Classic theme is more appropiate

In file list, switch from portrait to landscape, and switch again to portrait

Empty bar between `Sorting` and list of files:

![screen shot 2018-11-19 at 13 31 25](https://user-images.githubusercontent.com/14894746/48707341-719b6f80-ebff-11e8-940b-f43c0693a0d2.png)

**Comment by pablocarmu** [comment]
Cannot reproduce it in the simulator (tried iPhone X-layout and not-X-layout and iPad). Will try tomorrow in a real device.

Which version of iOS was the device in which you found this?

**Comment by jesmrec** [comment]
the same device i reproduced it was updated to 12.1. Not it is not reproducible anymore.

Closing, if it appears again, will be reopened.
