### ISSUE TITLE
Footer bar for navigation (tab bar)

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#164]
The footer bar in the files view is important, so users have shortcuts to different places avoiding browsing through the app

Currently we have the option to browse to the root folder of the current bookmark

![screen shot 2018-11-22 at 14 47 48](https://user-images.githubusercontent.com/14894746/48906703-a3157480-ee65-11e8-88c7-fe45e80f8304.png)

Which additional options should be included here? I'd go for:

- Link to Settings
- Link to Uploads (when it is done)
- Link to Shares (when it is done)

also, i'd change the name of the existing "browse" for "root" or similar.

more ideas welcome

**Comment by hosy** [comment]
My proposal would be to hide the `UITabBar` as long as we don't have any other views. We could should it again, if we have more content for that. 
In my opinion Settings is not the correct place in the `UITabBar`.

**Comment by michaelstingl** [comment]
We could do a PR for the 1st release that hides all the things that are not needed (yet).

**Comment by michaelstingl** [comment]
I made the title more precise. This issue is about switching different screens/views ([`tab bar`](https://developer.apple.com/design/human-interface-guidelines/ios/bars/tab-bars/)), not the [`toolbar`](https://developer.apple.com/design/human-interface-guidelines/ios/bars/toolbars/) that appears with multi-selection for example.

See https://github.com/owncloud/ios-app/issues/79 for multi-selection.

**Comment by wuenschedesign** [comment]
Shall the tab bar depend on if I am in the default screen of my ownCloud accounts or in the default screen of one of my ownCloud accounts? I need further information on this topic. Additional a further screen how it could look like: 

![tab-bar-01](https://user-images.githubusercontent.com/40062503/51641163-a0f69180-1f4c-11e9-811c-d4a0323ef3a8.png)

**Comment by michaelstingl** [comment]
Latest discussion was, @felix-schwarz wants to add a "Uploads" screen, which would require a footer tab bar with 2 items.

We have no "Sharing" yet, and maybe open "Settings" from another screen.

**Comment by wuenschedesign** [comment]
> Latest discussion was, @felix-schwarz wants to add a "Uploads" screen, which would require a footer tab bar with 2 items.
> 
> We have no "Sharing" yet, and maybe open "Settings" from another screen.

What does the Upload Screen do?

**Comment by wuenschedesign** [comment]
Suggestion for the tab navigation, depending on which screen you are currently. (If there’s just „Browse“ than it should be abandoned completely.)

File List | Server/Accounts/Bookmarks
-- | --
![tab-bar-account-01](https://user-images.githubusercontent.com/40062503/51868470-46d34300-2335-11e9-863a-0190fc253991.png) | ![tab-bar-server-list-01](https://user-images.githubusercontent.com/40062503/51868471-476bd980-2335-11e9-84c3-0637ca2e251d.png)

**Comment by michaelstingl** [comment]
We have a working 1st version and we'll need more specific issues for further improvements…
