### ISSUE TITLE
Glitch after "Move" operation

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#171]
Steps:

Move a file to other location

Current: Current folder is shown including the moved file. You have to refresh to get the correct file list

Expected: When "Move" operation is finished, file is automatically removed (automatic refresh) from list view, so user is not confused about the  operation result

Tested with master: `68d46065ed1459107bf32593e3a850040af7a28f`

iOS12

**Comment by felix-schwarz** [comment]
Fixed in `fp-series-2` branch as of https://github.com/owncloud/ios-app/pull/167/commits/4fe6430e051b382b0f053d147d5e057edecbba52

**Comment by jesmrec** [comment]
Fixed
