### ISSUE TITLE
The menu does not return to the starting position. 

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios-app#181]
### Steps to reproduce
1. Tap the three dots in Files View
2. **On a folder** swipe the menu up

### Expected behaviour
The menu returns to the position before

### Actual behaviour
The menu is cut off

![menu_ios-beta 2018-11-30 19_36_40](https://user-images.githubusercontent.com/33026403/49308037-58d06b00-f4d7-11e8-855f-6b57cc3daf72.gif)

### Client
**iOS version:**
12.1
**ownCloud app version:**
Build 85
**Device model:**
iPhone SE

**Comment by jesmrec** [comment]
Fixed in #183
