### ISSUE TITLE
Update DisplayViewController to track its item via a single-item OCQuery

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/ios-app#191]
Since `DisplayViewController` needs to track changes and is also the basis for launching actions on an item, it's necessary to ensure that the `item` always holds the latest version of an `OCItem` to prevent issues like:
- previously downloaded files or local modifications not being visible to actions (#178) 
- the title in the navigation bar not matching the latest name after a rename
- the viewed file not being updated after the content changed (via f.ex. the File Provider or on the server)

**Comment by felix-schwarz** [comment]
From #225:
> Since there are so many merge conflicts and there's not much new code in this PR, I decided to start over and implemented this feature in f5e1784. /cc @pablocarmu @mneuwert @hosy @jesmrec

**Comment by jesmrec** [comment]
Works even with files renaming. Fixed in #253
