### ISSUE TITLE
iOS file list colour scheme inconsistent

### ISSUE THREAD

**Issue by wuenschedesign** [owncloud/ios-app#192]
### Steps to reproduce
1. Switch to ownCloud Classic Theme
2. Open File List
3. Turn smartphone to landscape mode

### Expected behaviour
- Better colour contrast
- consistent colour scheme, same blue for icon and tab navigation

### Actual behaviour
- background colour of tab navigation (blue) has too little contrast to the background of the header (ownCloud Dark Grey)
- colour scheme not consistent (different shades of blue) depending on ownCloud theme.
- colour scheme not consistent (different colour of text in the tab) depending on ownCloud theme.
- colour scheme not consistent concerning different screen modes (landscape mode vs. portrait mode)

### Client
**iOS version:**
12.0.1

**ownCloud app version:**
1.0 build 85

**Device model:**
iPhone 7

### Screenshots:

Portrait | Landscape
-- | --
![bildschirmfoto 2018-12-20 um 10 52 22](https://user-images.githubusercontent.com/40062503/50278871-83637300-0448-11e9-9b2f-2b5e3d211bec.png) | ![bildschirmfoto 2018-12-20 um 10 52 01](https://user-images.githubusercontent.com/40062503/50278870-82cadc80-0448-11e9-8f6d-4628970e955d.png)
![bildschirmfoto 2018-12-20 um 10 56 21](https://user-images.githubusercontent.com/40062503/50278873-83637300-0448-11e9-98cc-2cae94a5e03d.png) | ![bildschirmfoto 2018-12-20 um 10 56 30](https://user-images.githubusercontent.com/40062503/50278874-83637300-0448-11e9-9826-6b74c66c0051.png)
![bildschirmfoto 2018-12-20 um 10 56 57](https://user-images.githubusercontent.com/40062503/50278875-83637300-0448-11e9-90eb-006bf0e2d37f.png) | ![bildschirmfoto 2018-12-20 um 10 57 04](https://user-images.githubusercontent.com/40062503/50278876-83fc0980-0448-11e9-987b-fb76508c5bc6.png)

 
### Tell us what could be improved:
Lighten colour of icon in the header, use same colour for the tab navigation

**Comment by michaelstingl** [comment]
It looks like sorting UI in landscape mode doesn't use theming? It uses fixed color from the light theme.

**Comment by jesmrec** [comment]
Done in #206
