### ISSUE TITLE
Cannot fetch directories and app crashes on top-level files when extra trailing slash in server URL.

### ISSUE THREAD

**Issue by risacher** [owncloud/ios-app#193]
### Steps to reproduce
1. Connect app to server with extra trailing slash in the URL - ie. "https://FQDN/owncloud//"
2. Try to fetch any directory or file
3.

### Expected behaviour
Tell us what should happen

Show directory content or file

### Actual behaviour
Tell us what happens instead

All directories show "Folder Removed" error, "This folder no longer exists on the server." 

Inspection of network traffic indicates that the app is attempting to GET the following path: "/owncloud//remote.php/dav/files/dan/owncloud/remote.php/dav/files/dan/documents/"

Attempting to open a file from the root directory crashes the app.

### Client
**iOS version:**

12.0.1

**ownCloud app version:**

Beta 1.0 Build 85

**Device model:**

iPhone S

### Server configuration
**Web server:**

Apache2 behind custom reverse-proxy

**Database:**
sqlite3

**PHP version:**

7.0, I think

**ownCloud version:**

10.0.9.5

**Storage backend (external storage):**

n/a

#### Web server error log
```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by risacher** [comment]
Alternatively, the iOS app should either delete the extra slash or give error message.  But it connects and can fetch the top-level directory okay, which made it hard to figure out why it wasn't working.

**Comment by felix-schwarz** [comment]
Thanks for reporting this issue @risacher!

The issue should be fixed as of 
https://github.com/owncloud/ios-app/pull/167/commits/3266cfa7acc89ad5676497b24fb7fec814500d82 (and in an upcoming TestFlight build that will be part of).

**Comment by jesmrec** [comment]
@risacher did you check with a newer build?

**Comment by michaelstingl** [comment]
> @risacher did you check with a newer build?

didn't published a new build on TestFlight. sorry

**Comment by jesmrec** [comment]
ok, i will try to get a server with double slash... with subfolder is easy to build, i will check other options.

**Comment by jesmrec** [comment]
The fix is already merged inside https://github.com/owncloud/ios-app/pull/167. Let's wait for additional feedback before closing.

**Comment by risacher** [comment]
I just tested with TestFlight build and seems fixed to me.  

https://myserver.org/owncloud// is changed to https://myserver.org/owncloud/ and then works.

interestingly, extra slashes internally (e.g. https://myserver.org//owncloud/) just "work". (Unsurprisingly, since the web server ignores these.)
