### ISSUE TITLE
[UX] Improve accessibility

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#196]
I played a bit with [VoiceOver](https://www.apple.com/accessibility/iphone/vision/):

![2019-01-04 09 15 22](https://user-images.githubusercontent.com/214010/50681358-84310300-100b-11e9-9133-ee176888837e.jpg)

I think we can improve in different places. Apple provides great resources for this topic:

- https://developer.apple.com/accessibility/ios/
- https://developer.apple.com/documentation/uikit/accessibility/
- https://developer.apple.com/videos/frameworks/accessibility/

@pablocarmu Would you like work on this a few days in the next milestone? (to achieve some quick wins)

### Client
**iOS version:**
iOS 12.1.2 (16C101)

**ownCloud app version:**
ownCloud beta version 1.0 build 85 (https://github.com/owncloud/ios-app/commit/5df9764c4975f28c21eb7cb24eb133f67e6b7a59) 

**Device model:**
Model: iPhone XS Max

**Comment by felix-schwarz** [comment]
@pablocarmu @michaelstingl The relevant APIs here are `accessibilityLabel` and `accessibilityHint`, which can be used to add VoiceOver specific descriptions to any UI element:
- https://developer.apple.com/documentation/objectivec/nsobject/1615181-accessibilitylabel
- https://developer.apple.com/documentation/objectivec/nsobject/1615093-accessibilityhint

This f.ex. should be all it takes to fix the issue for the create folder button:

```swift
createFolderButton.accessibilityLabel = "Create folder"
```

The greater difficulty here is to follow the guidelines provided for those two APIs to provide the "right" string.

There also is Apple's Accessibility Inspector app, which can perform an automatic audit of the app's currently visible UI and identify and report common issues.

**Comment by pablocarmu** [comment]
I guess that we could localize this accessibility hint the same way that other strings using our `.localize` API.

We can start adding this accessibility hint to the current features. Should we create new `.string`filet to write down the hints and localize them?

**Comment by felix-schwarz** [comment]
@pablocarmu I think we can use the existing `.strings` files as there will be some overlap between UI and accessibility hint strings, which would then have to localize twice.

**Comment by michaelstingl** [comment]
In the iOS Files app for example, the "New folder" button says "New folder, button" with VoiceOver.
