### ISSUE TITLE
[UX] Navigationbar Button for Uploading 

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#198]
The “Dot” button has for me an unclear meaningfulness. At the moment it has only two entries for uploading files or photos. 
In my opinion we should use a “Plus” button, because the user will so easier see what this action will do. 

<hr /><div align="center"><img alt="Screenshot uploaded with GitShot" src="https://i.imgur.com/j5FfGB7.png" width="300.0" height="650.1779359430604" align="center" /><br><br>Documented with <a href="https://goo.gl/oZUi2a">GitShot</a></div><hr />

**Comment by michaelstingl** [comment]
I played a little bit with prototyping in Figma

![owncloud_ios_12](https://user-images.githubusercontent.com/214010/51571128-83b8b900-1ea1-11e9-86e2-8948d6722dd3.png)

Here you can try it:
https://www.figma.com/proto/bQmS1FDEEuqeBR8K4mAfcBPD/ownCloud-iOS-12?node-id=64%3A1210&viewport=-65%2C340%2C0.835061&scaling=min-zoom

**Comment by jesmrec** [comment]
@michaelstingl you can open a new issue with the content of the menu when the  '+'  is clicked. The UX issue of changing the button is already developed in #206 and ready to merge.

**Comment by hosy** [comment]
I have also tried a draft who we can implement the '+' button and a multi selection with corresponding actions in the toolbar.
We have the space for the '+' button and it is leaned against Apples Files-App, also if there is the add folder button instead. A other solution would be to put the button on the right side.
Furthermore I moved the file icon and the file name, file date more on the left side, to be aligned with the '+' button and get more space for longer file names.

| ![filelist_select](https://user-images.githubusercontent.com/736109/51598664-4f271a80-1efe-11e9-8dc6-721db7e8314f.png) | ![filelist_selected](https://user-images.githubusercontent.com/736109/51598665-4f271a80-1efe-11e9-9f96-c9594f7c9e14.png) |
|------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------|

**Comment by jesmrec** [comment]
@hosy, i guess that @mneuwert will appreciate here -> #79 as well

**Comment by hosy** [comment]
@jesmrec I think the left place should be reserved for the `Back` title.

**Comment by jesmrec** [comment]
`Back `is on the top left of the screen. But in the top right you can put bot `Select` and `+`.

**Comment by hosy** [comment]
Maybe to much elements on this place, bcause we have the place below.

**Comment by jesmrec** [comment]
a draft with the option would be helpful ;)

**Comment by michaelstingl** [comment]
I really like the concept in https://github.com/owncloud/ios-app/issues/198#issuecomment-456743221 👍 

> `Back `is on the top left of the screen. But in the top right you can put both `Select` and `+`.

I don't like mixing a word-like button and a icon-like button side by side and the support for longer file names sounds very useful.

@jesmrec Do you see any disadvantages? @wuenschedesign What do you think?

**Comment by wuenschedesign** [comment]
My current drafts on this topic so far. To be discussed. (The footer is just demo here and not referring to real functions)

Overview List | List in Select Mode
-- | --
![select-01](https://user-images.githubusercontent.com/40062503/51632823-53bbf500-1f37-11e9-899a-56c633753c9e.png) | ![select-02](https://user-images.githubusercontent.com/40062503/51632824-53bbf500-1f37-11e9-819a-456fe6364ee5.png)

**Comment by wuenschedesign** [comment]
> I really like the concept in [#198 (comment)](https://github.com/owncloud/ios-app/issues/198#issuecomment-456743221) 👍
> 
> > `Back `is on the top left of the screen. But in the top right you can put both `Select` and `+`.
> 
> I don't like mixing a word-like button and a icon-like button side by side and the support for longer file names sounds very useful.
> 
> @jesmrec Do you see any disadvantages? @wuenschedesign What do you think?

I don’t recommend multiple actions on the top right along with a centered title in the navigation bar as it reduces dramatically the space for the title. iOS just offers multiple actions with navigation bars that don’t contain titles (e. g. calendar)

**Comment by michaelstingl** [comment]
> (The footer is just demo here and not referring to real functions)

Please discuss the footer bar ([`tab bar`](https://developer.apple.com/design/human-interface-guidelines/ios/bars/tab-bars/)) in https://github.com/owncloud/ios-app/issues/164 and the [`toolbar`](https://developer.apple.com/design/human-interface-guidelines/ios/bars/toolbars/) for multi-selection in https://github.com/owncloud/ios-app/issues/79 .

@wuenschedesign In the left draft in https://github.com/owncloud/ios-app/issues/198#issuecomment-456941989 you're mixing tab bar and toolbar which doesn't make sense.

**Comment by wuenschedesign** [comment]
> > (The footer is just demo here and not referring to real functions)
> 
> Please discuss the footer bar ([`tab bar`](https://developer.apple.com/design/human-interface-guidelines/ios/bars/tab-bars/)) in #164 and the [`toolbar`](https://developer.apple.com/design/human-interface-guidelines/ios/bars/toolbars/) for multi-selection in #79 .
> 
> @wuenschedesign In the left draft in [#198 (comment)](https://github.com/owncloud/ios-app/issues/198#issuecomment-456941989) you're mixing tab bar and toolbar which doesn't make sense.

I didn’t work yet on the tab bar. it’s just a: here could be your tab bar.

**Comment by michaelstingl** [comment]
Can the "Plus" button upload images and files AND create a new folder?

**Comment by wuenschedesign** [comment]
> Can the "Plus" button upload images and files AND create a new folder?

You mean uploading files and for those files creating a new folder at exactly that time?

**Comment by michaelstingl** [comment]
> You mean uploading files and for those files creating a new folder at exactly that time?

no

**Comment by michaelstingl** [comment]
> I would definitely go for a solution with just one Add (+) Icon that can operate different functions like you proposed above. (Upload file, Upload images, create folder)

Cool, thanks for four your feedback 👍

**Comment by michaelstingl** [comment]
I opened a new issue for the discussed improvements:
https://github.com/owncloud/ios-app/issues/252
