### ISSUE TITLE
File list: Create a new folder

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#20]
_As user, i want to create a new folder in the file list, so that i can store files on it_

AC:

- [ ] Set the option in the files list
- [ ] Create a dialog to let user put a name
- [ ] Send the operation, and handle the response
- [ ] Handle issues 
- [ ] Refresh the list view to show the new status
- [ ] If the user remove the name the `Done button` should appear disabled
- [ ] QA

Mockups:
![create folder v2](https://user-images.githubusercontent.com/1815050/42268377-97649b1a-7f7b-11e8-81a7-eb52059d93bc.png)

Figma design:
https://www.figma.com/file/Ui4YzD3oQcxJSbzBEr80O9eU/Working-Draft-UI?node-id=1816%3A2373

**Comment by javiergonzper** [comment]
Added a mockup about how it should looks like based on the Apple File App:
@michaelstingl @jesmrec

**Comment by jesmrec** [comment]
Works for me.

**Comment by michaelstingl** [comment]
Apple Files app provides a super clear interface. Good idea to get inspiration from it…

**Comment by michaelstingl** [comment]
Align behaviour to Files app:

- `New folder` on top-middle
- `Done` on top-right

**Comment by javiergonzper** [comment]
Updated the mockup 👍 and also the AC

**Comment by jesmrec** [comment]
Done
