### ISSUE TITLE
[TX] Transifex job is pushing more languages that we supported

### ISSUE THREAD

**Issue by javiergonzper** [owncloud/ios-app#202]
Transifex is pushing to our project several languages that are not supported yet like:

- cs_CZ.lproj
- de.lproj
- de_DE.lproj
- en_GB.lproj
- ko.lproj
- mk.lproj
- nb_NO.lproj
- nn_NO.lproj
- pt_BR.lproj
- pt_PT.lproj
- ru.lproj
- sq.lproj
- th_TH.lproj
- zh_CN.lproj

Right now we only support English and Spanish. And Spanish is not being updating.

AC:
- Support all the languages that TX Job is pushing to GitHub
- ~Add Spanish to the TX Job~

**Comment by michaelstingl** [comment]
Tx pushes all languages that have a minimal percentage. This value is defined in the drone job

**Comment by javiergonzper** [comment]
> Tx pushes all languages that have a minimal percentage. This value is defined in the drone job

Ok. Then the second AC is not necessary will be automatically pushed when it have enough percentage of translation.
