### ISSUE TITLE
[Files app] Can't create new folder in root

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#203]
### Steps to reproduce
1. Install ownCloud
2. Add account `https://test:test@demo.owncloud.com/`
3. Open test@demo.owncloud.com in Files app ==> Button "New folder" is deactivated
4. Open subfolder "Photos"
5. Create folder "Test"
6. Go back to root folder ==> Button "New folder" now activated

Step 3. | Step 5. | Step 6.
-- | -- | --
![2019-01-13 15 54 57](https://user-images.githubusercontent.com/214010/51087323-2068b180-1752-11e9-8c42-7a7b2d7b1235.png) | ![2019-01-13 15 55 21](https://user-images.githubusercontent.com/214010/51087324-21014800-1752-11e9-93f9-31c373c6b736.png) | ![2019-01-13 15 55 33](https://user-images.githubusercontent.com/214010/51087325-21014800-1752-11e9-85c0-c29d84276cca.png)

### Expected behaviour
Button "New folder" should be activated when first opening the account in the iOS Files app

### Actual behaviour
 Button "New folder" is deactivated when entering the root directory the first time

### Client
**iOS version:**
iOS 12.1.2 (16C101)

**ownCloud app version:**
ownCloud beta version 1.0 build 96 (https://github.com/owncloud/ios-app/commit/c5c74efd5850c2279ee42b057ca0332696da1569, not shown in the app??)

**Device model:**
Model: iPhone XS Max

**Comment by michaelstingl** [comment]
@felix-schwarz please ping when the SDK related fixes are done

**Comment by felix-schwarz** [comment]
Fixed as of https://github.com/owncloud/ios-app/commit/96342c5363889e71679ecba051d9b390183525d3.

**Comment by jesmrec** [comment]
Fixed in `features/fp-series-2`
