### ISSUE TITLE
[Save to Files] New account not available as upload target

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#205]
### Steps to reproduce
1. Add account `https://test:test@demo.owncloud.org/` (don't open it)
2. Select multiple images in "Photos" app
3. Choose "Save to Files" in the share sheet ==> test @ demo.owncloud.org grey

![2019-01-14 10 01 25](https://user-images.githubusercontent.com/214010/51103931-c95fec80-17e4-11e9-8c89-f2fa3f5bb666.png) | ![2019-01-14 10 01 37](https://user-images.githubusercontent.com/214010/51103932-c95fec80-17e4-11e9-9a03-8b25e6b8ba12.png)
-- | --

### Expected behaviour
New account should be available as upload target

### Actual behaviour
New account not available as upload target

### Client
**iOS version:**
iOS 12.1.2 (16C101)

**ownCloud app version:**
ownCloud beta version 1.0 build 96 (https://github.com/owncloud/ios-app/commit/c5c74efd5850c2279ee42b057ca0332696da1569, not shown in the app??)

**Device model:**
Model: iPhone XS Max

**Comment by felix-schwarz** [comment]
Fixed as of https://github.com/owncloud/ios-app/commit/96342c5363889e71679ecba051d9b390183525d3.

**Comment by jesmrec** [comment]
Fixed in `feature/fp-series-2`
