### ISSUE TITLE
[UI] First status message after connecting is "Offline mode"

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#208]
When a bookmark is opened, first status message is "Offline mode": 

![jan-11-2019 14-09-32](https://user-images.githubusercontent.com/14894746/51112881-7e53d280-1800-11e9-919e-5351c8d1d14d.gif)

**Comment by felix-schwarz** [comment]
Fixed in 
https://github.com/owncloud/ios-app/pull/167/commits/f115932c5b3878474dcf4b36562a55a965a97f86

**Comment by jesmrec** [comment]
Correctly fixed
