### ISSUE TITLE
Files: Rename a file or folder

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#21]
_As a user, i want the possibility to rename a file, so that i can set a different name to my files or folders_

AC:

- [ ] Set the option to rename in the file list
- [ ] Set a dialog in order to let the user choose a new name for the item
- [ ] The user can cancel the operation
- [ ] Send the request and get the response
- [ ] Handle issues
- [ ] Refresh the list view to show the new status
- [ ] If the user remove the name the `Done` button should appear disabled
- [ ] QA

Mockups:
![rename document pdf v2](https://user-images.githubusercontent.com/1815050/42267611-b96fd3de-7f79-11e8-899f-c9c48ebb396b.png)
![rename image v2](https://user-images.githubusercontent.com/1815050/42267612-b9920616-7f79-11e8-98bc-90cf0cbb0945.png)
![rename video v2](https://user-images.githubusercontent.com/1815050/42267613-b9b52ba0-7f79-11e8-91d3-cec8f3532761.png)

Figma design:
https://www.figma.com/file/Ui4YzD3oQcxJSbzBEr80O9eU/Working-Draft-UI?node-id=1816%3A3862

**Comment by javiergonzper** [comment]
Added some mockups for rename files and folders.
IMHO we should use:

The default icons for:
- Documents (PDF, TXT...)
- Folders

Thumbnails for:
- Images
- Videos

What do you think? @jesmrec @michaelstingl

**Comment by michaelstingl** [comment]
Do we have support for Videos thumbnails already? Or do we need a full player in the rename screen?

**Comment by javiergonzper** [comment]
> Do we have support for Videos thumbnails already? Or do we need a full player in the rename screen?

Looks like not yet. For not preview files we have to use the design of the "PDF" but using the right SVG image but in the future for videos we should use that design.

**Comment by michaelstingl** [comment]
@cdamken has a special hack for video previews: https://github.com/owncloud/ios-app/issues/31#issuecomment-385337698

**Comment by javiergonzper** [comment]
Updated issue with V2 mockups (Done instead accept) also updated the AC with: " If the user remove the name the `Done` button should appear disabled"

**Comment by jesmrec** [comment]
Done
