### ISSUE TITLE
iOS account list top bar has no clear description

### ISSUE THREAD

**Issue by wuenschedesign** [owncloud/ios-app#210]
### Steps to reproduce
1. Start ownCloud Application
2. Watch first screen

### Expected behaviour
Top bar should always tell the user where in the app he is located, e.g.: list of my accounts

### Actual behaviour
Description in top bar is not specified, it just says »ownCloud«

### Client
**iOS version:**
12.0.1

**ownCloud app version:**
1.0 build 85

**Device model:**
iPhone 7

### Screenshot:
Current Screen | Possible Solution 1 | Possible Solution 2
-- | -- | --
![bildschirmfoto-2019-01-14-um-17 47 07-a](https://user-images.githubusercontent.com/40062503/51136937-f55b8c00-183d-11e9-8c9b-e39944519d79.png) | ![bildschirmfoto-2019-01-14-um-17 47 07-solution](https://user-images.githubusercontent.com/40062503/51208456-0247b080-190e-11e9-88ef-498e9bc88326.png) | ![bildschirmfoto-2019-01-14-um-17 47 07-solution-2](https://user-images.githubusercontent.com/40062503/51208538-4044d480-190e-11e9-9987-3eb39b66e137.png)

**Comment by wuenschedesign** [comment]
I updated solution screens in the description of the issue.

**Comment by hosy** [comment]
I would keep the **ownCloud** Branding in the Header. Instead I would use the table header to explain the user this view.

_Originally posted by @hosy in https://github.com/owncloud/ios-app/issues/223#issuecomment-456449500_

**Comment by michaelstingl** [comment]
This is the latest version. (included in 1.0.0 release)

![2019-04-08_10_31_48](https://user-images.githubusercontent.com/214010/55709953-c5112d00-59e9-11e9-92a3-17b96670b6f1.png)
