### ISSUE TITLE
iOS file list DISCONNECT link

### ISSUE THREAD

**Issue by wuenschedesign** [owncloud/ios-app#211]
### Steps to reproduce
1. Start ownCloud App
2. Watch list of ownCloud accounts

### Expected behaviour
The »Disconnect« link should be called for example: »back« or »all accounts« or »my accounts«

### Actual behaviour
The current Button says »disconnect« which is technically right but misleads the user. he doesn’t understand that by clicking »disconnect« he will be led to the overview of all his ownCloud accounts

### Client
**iOS version:**
12.0.1

**ownCloud app version:**
1.0 build 85

**Device model:**
iPhone 7

### Screenshot:
![bildschirmfoto-2019-01-14-um-17 47 38-a](https://user-images.githubusercontent.com/40062503/51138196-bbd85000-1840-11e9-98da-50a0fb7e61b8.png)

**Comment by michaelstingl** [comment]
Duplicate for 
https://github.com/owncloud/ios-app/issues/49

Please comment in the original issue.
