### ISSUE TITLE
Files: Delete a file or folder from my structure.

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#22]
_As a user, i want the posibility to delete a file, so that i can get rid of it if i am not interested anymore_

AC:

- [ ] Set the option to delete in the file list
- [ ] Set the option to delete in the preview of the files
- [ ] Set a dialog in order to let the user choose between removing locally or from server
- [ ] Remove the file locally in case the user chose that option
- [ ] Send the request and get the response in case the user deletes from server
- [ ] Handle issues
- [ ] On delete from file list: Refresh the list view to show the new status
- [ ] On delete from file preview: leave the preview automatically once the file is delete on the server like "back"
- [ ] If the user tap on "Delete" all the files inside that folder should be deleted locally and on the server (destructive)

- [ ] QA

Mockups:
Delete file from the list
![delete file list - file v2](https://user-images.githubusercontent.com/1815050/41846422-eb68ab9a-7876-11e8-8e80-cda26e9578ba.png)

Delete folder
![delete file list - folder v2](https://user-images.githubusercontent.com/1815050/41846423-eb824d34-7876-11e8-85c4-6cc034355212.png)

Delete multiselection
![delete multiselection v2](https://user-images.githubusercontent.com/1815050/41846424-eb9cae40-7876-11e8-9cc6-e544daf20dd0.png)

Delete preview
![delete preview v2](https://user-images.githubusercontent.com/1815050/41846426-ebb5f846-7876-11e8-97ae-40f9e74df97e.png)

**Comment by javiergonzper** [comment]
Updated the mockups taking adding a title in order to know witch file or folder we are deleting.
It helps a lot on files or folder with `Extremely long filenames` https://github.com/owncloud/ios-app/issues/88

**Comment by jesmrec** [comment]
Works for me

**Comment by pablocarmu** [comment]
A couple of things to comment here:

> On delete from file list: Refresh the list view to show the new status

This is automatically done via `OCQueryDelegate` at the time the `delete` command call in `OCCore` finished if you have one `OCQuery` running involving the file you are deleting. (See implementation of the delegate [here](https://github.com/owncloud/ios-app/blob/master/ownCloud/Client/ClientQueryViewController.swift#L413))  



> Handle issues.

Currently, there are no mockups about how to present the possible issues that the SDK provide us in case of any error. We have some options:

- Use `IssuesViewController` class like in the `BookmarkViewController` authentication issues.
- Use a native `UIAlertView` with the issue message.



> Set a dialog in order to let the user choose between removing locally or from server
> Remove the file locally in case the user chose that option

For what we talked about in some calls, there is not going to be a `remove locally` option (at least at early stages). I think we talked about download the files temporarily for preview in the temp folder and let the system manage it. 

In recent additions to the `ownCloudSDK` there are some mechanisms led by [OCFile.h](https://github.com/owncloud/ios-sdk/blob/feature/sync/ownCloudSDK/File%20Handling/OCFile.h) that makes the possibility to have a retainer and, in the future, create files that last on disk only a fixed amount of time (a few hours, one day, one week...). About this topic, @felix-schwarz can correct me if I'm saying something wrong here.

I'm about to push one pull request with the delete feature working for single and multiple items. There are still some things pending to discuss (See [here](https://github.com/owncloud/ios-app/issues/79#issuecomment-400333553))

**Comment by jesmrec** [comment]
Issues from SDK should be handled in the same way in the whole app, i think. As you posted before,  in authentication feature, was used an specific ViewController. It should be the same in other features, unless any technical issue does not allow it.

**Comment by jesmrec** [comment]
Done
