### ISSUE TITLE
[UI] Refresh Passcode UI

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#222]
The passcode UI should get a more iOS like UI.

The current passcode has in my opinion some problems:

* Square Button not really iOS like
* Font size to small, not so easy to read
* Button Background Color to dark

I have two design suggestions which can you see below.

* Increased the font size
* Round Button, also used in iOS for passcodes

I added two different designs, please vote which one to you prefer or give suggestions, what we can do better.

Important for the development should be, to test it with:

* External keyboard connected
* Accessibility enabled (use accessibility label)
* Check iPad UI (use `viewController.modalPresentationStyle = UIModalPresentationFormSheet;`)

Draft 1: | Draft 2:
-- | --
![passcode draft 1](https://user-images.githubusercontent.com/736109/51236502-93507300-1972-11e9-8727-6fbcad2eed2d.png) | ![passcode draft 2](https://user-images.githubusercontent.com/736109/51236514-9b101780-1972-11e9-9cb7-1c2ad3efcade.png)

**Comment by haukman** [comment]
I prefer Draft 1 as it looks a bit "lighter" and not so heavy as Draft 2.
