### ISSUE TITLE
[UI] Refresh Serverlist View

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#223]
**Reorder/Remove Buttons**

The `+` Button should be removed if the view is not in Edit mode. It should be only visible, if the user sets the view in Edit mode. I think this button is not so often needed and so we should not show rarely needed elements.

The `Edit` button should be on the right side. This can also be seen in the Files App and this does better match the UI guidelines.

**Large Title, Header**

The title `ownCloud` should be displayed as large title. This is a UI concept which was introduced in iOS 11 and is a better welcome for the user.

Set a header title `Locations` above the server list. This is analog to the Files app. Wording can be changed, to match more the ownCloud wording.

**Select Server from List:**

If a Server is selected by the user, the File list should not be shown as modal transition. A better behavoir would be to use a Push transition on the `UINavigationViewController`.

Account list today | Account list in edit mode  | draft&nbsp;of&nbsp;the&nbsp;suggestions&nbsp;above&nbsp;&nbsp;&nbsp;
-- | -- | --
![2019-01-16 19 07 07](https://user-images.githubusercontent.com/214010/51269189-1c42cb00-19c2-11e9-9756-0023afeb79fc.png) | ![2019-01-16 19 07 20](https://user-images.githubusercontent.com/214010/51269190-1c42cb00-19c2-11e9-8d0f-bbb65abd0e83.png) | ![serverlist draft](https://user-images.githubusercontent.com/736109/51238178-9cdbda00-1976-11e9-8e95-55c7ba63362a.png)
(Build 96) | (Build 96) |

**Comment by jesmrec** [comment]
>The + Button should be removed if the view is not in Edit mode. It should be only visible, if the user sets the view in Edit mode. I think this button is not so often needed and so we should not show rarely needed elements.

I think that the '+' button is needed to add new bookmarks to the list, so, it is not needed in `Edit` mode. But it you are not in `Edit`, we'd have to think in a different option to create bookmarks.

> Set a header title Locations above the server list. This is analog to the Files app. Wording can be changed, to match more the ownCloud wording.

i think ' Bookmarks` or `Servers` fits better than `Locations` inside the ownCloud words.

@wuenschedesign opened this related one: https://github.com/owncloud/ios-app/issues/210

**Comment by michaelstingl** [comment]
What about `Accounts`? I don't like `Bookmarks` and `Servers` is also not perfect, because you can have multiple accounts on one ownCloud server.

**Comment by michaelstingl** [comment]
I added the screenshots of the current state (beta version 1.0 build 96 (https://github.com/owncloud/ios-app/commit/c5c74efd5850c2279ee42b057ca0332696da1569, not shown in the app??)) to the initial post.

I don't have a problem with showing the "`+`" while not being in "Edit" mode. I think it's easier to discover for unexperienced people…

**Comment by hosy** [comment]
Please look at this video, how the transition could like like, if you select a bookmark. This could be changed with two lines of code.

![ezgif-3-b097200ce698](https://user-images.githubusercontent.com/736109/51537794-cc478680-1e4f-11e9-9fc9-650ce250015e.gif)

**Comment by hosy** [comment]
Last comment would also fix Issue #49

**Comment by michaelstingl** [comment]
FYI also check @wuenschedesign 's headache with the header text: https://github.com/owncloud/ios-app/issues/210

**Comment by hosy** [comment]
Thank you , but I do not really like this solution. I would keep the **ownCloud** Branding in the Header. Instead I would use the table header to explain the user this view.

**Comment by wuenschedesign** [comment]
my current draft on this topic so far:

Screen Normal | Screen Edit Mode
-- | --
![owncloud-accounts-01](https://user-images.githubusercontent.com/40062503/51632094-a1376280-1f35-11e9-9322-8e07be82aa63.png) | ![owncloud-accounts-02](https://user-images.githubusercontent.com/40062503/51632110-a694ad00-1f35-11e9-8606-99e62dc34bfd.png)

**Comment by michaelstingl** [comment]
@wuenschedesign thanks for your input! @hosy is working on a 1st version… (can be tested soon)

**Comment by jesmrec** [comment]
Done and merged
