### ISSUE TITLE
[FR] Show the used quota inside the app

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios-app#228]
### Expected behaviour
In our Android app we have the possibility to display the used quota. In my opinion, this useful feature should also be available in the new iOS app.

![image](https://user-images.githubusercontent.com/33026403/51485622-dcebf400-1d9e-11e9-84ad-bf4298613153.png) | 
![reflector_screenshot](https://user-images.githubusercontent.com/214010/51489091-9c44a880-1da7-11e9-8556-bfabfb94a7e2.png)
-- | --

**Comment by mneuwert** [comment]
@jesmrec In the server list we have no active connection yet, so of course we could try to connect, just to get the quota but not sure.. Alternatively we could e.g. show it in the prompt of navigation bar:
<img width="503" alt="Screenshot 2019-03-27 at 07 47 42" src="https://user-images.githubusercontent.com/228537/55055862-afece380-5064-11e9-977e-e162c1638e42.png">

**Comment by jesmrec** [comment]
Ok, other option is setting on the bottom (just above the options)
