### ISSUE TITLE
Fileprovider support for importing bundle documents (Pages/Keynote)

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/ios-app#235]
### Steps to reproduce
1. Create Pages document on iCloud Drive
2. Open Files app
3. Move Pages document from iCloud Drive to ownCloud File Provider

### Expected behaviour
The document is a single file and gets imported.

### Actual behaviour
The document is a folder and importing fails (even crashes in older versions).

### Observation
- copying folders from iCloud Drive to OC FP via drag and drop leads to Files app sending createDir/import commands for all folders and files (=> worked without issue)
- unlike on iCloud Drive, Pages itself creates a flat file on third-party File Providers, which is really a zip file of the folder on iCloud Drive (using a Mac, compressing a bundle Pages document as zip and removing the zip file allows one to open and preview it)
- other file providers (like Working Copy) seem to compress the bundle documents transparently as zip files and therefore work fine with the steps above

### Recommended solution
Detect bundle-style documents on import and transparently produce a zip file for upload to the OC server.

**Comment by felix-schwarz** [comment]
Implemented as of 
https://github.com/owncloud/ios-app/commit/f6afc6d026d2d79dd0b9cd8c5157f171846582b8

**Comment by jesmrec** [comment]
Importing the files via Files App works correctly. I've also checked it using MS Word documents and this is OK.

With the current latest commit 966eddfda1968d62369e1ffd62f610744b3bc34a, i noticed that the steps mentioned here https://github.com/owncloud/ios-app/pull/167#issuecomment-456078153 -> bullet (1) are again reproducible. I mean:

- Open MSWord, create document
- Select as target the attached ownCloud app and save the document there

Current: file appears in the list with 0 KB

**Comment by jesmrec** [comment]
Fixed in #253

**Comment by michaelstingl** [comment]
@felix-schwarz FYI Doesn't work with GarageBand projects. (created on the iOs device)

![2019-03-01_02_51_50](https://user-images.githubusercontent.com/214010/53611017-51e7f000-3bcd-11e9-8bbd-b9570a43addb.png)

Related:
https://twitter.com/palmin/status/1034730403305873408
