### ISSUE TITLE
[MDM] Create a simple MDM/AppConfig/specfile.xml

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#236]
As a first step, I'd propose a very simple `MDM/AppConfig/specfile.xml` with only 2 parameters:

- single-account
- fixed server URL

We also need quick guide, how to use this in MDM's like MobileIron for example.

(belongs to EPIC: https://github.com/owncloud/ios-app/issues/2)

**Comment by michaelstingl** [comment]
BTW here is an example doc from another app:
https://www.stratospherix.com/products/guides/RemoteConfiguration.pdf

**Comment by felix-schwarz** [comment]
AppConfig.org spec creator:
- URL: https://github.com/jamf/AppConfigSpecCreator
- Javascript based, must be served from a web server

Testing the specfile:
- https://appconfig.jamfresearch.com
- upload specfile.xml to see it rendered
