### ISSUE TITLE
Files: Move to another place (Drag & Drop)

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#24]
_As a user, i want the posibility to move a file, so that i can set an item in another place in my structure (Drag & Drop posibility)_

AC:

- [ ] Set the option to move in the file list (optional?, maybe enough with drag and drop)
- [ ] Set a dialog/folder picker in order to let the user choose the target folder for the copy  (optional?, maybe enough with drag and drop)
- [ ] Send the request and handle the response 
- [ ] Handle issues (for example, a folder can not by moved in itself)
- [ ] Refresh the list view to show the new status
- [ ] QA

**Comment by javiergonzper** [comment]
I have been testing the `Move` of the `Files App`. It is really cool but have issues:

- You can not create a folder while you are moving
- The first time it is not so intuitive. Take into account that this app it is used not only by geeks it is used by normal users, companies... 
- You need to use 2 hands to move a file/folder to an upper level (or two fingers having the device over a table)

IMHO we should implement first a normal move view to have the functionality on the app. And later iterate and add a move with Drag & Drop.

What do you think @michaelstingl ?

Here is a mockup of move:

![move](https://user-images.githubusercontent.com/1815050/41896968-4cf1a06a-7926-11e8-9cfa-f1327dd32e40.png)

Remember that this view appears from the `More UI` and the `Multiselection`

**Comment by jesmrec** [comment]
Done.

**Comment by michaelstingl** [comment]
More fun with Drag & Drop in https://github.com/owncloud/ios-app/issues/250 …
