### ISSUE TITLE
Multiselection II

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#246]
Will continue the work after https://github.com/owncloud/ios-app/issues/79

Actually, Move and Delete are done.

Suggestion for new options to include:

- [ ] Open In (as included in Files app)
- [ ] Open In > Save multiple images or videos to Photos app (from #79 (comment))
- [ ] Duplicate
- [ ] Copy

Also, a `Select All` and `Select inverse` will make the feature more usable.

Other suggestions, welcome.

**Comment by michaelstingl** [comment]
- Open In > Save multiple images or videos to Photos app (from https://github.com/owncloud/ios-app/issues/79#issuecomment-457217958)
- Favorites (oC favorites and/or iOS favorites)
