### ISSUE TITLE
Clean up before release

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#247]
Some clean up to be done before a release inside the app:

- [x] Beta warning: i guess with a non-beta ipa will not appear.
- [x] Settings: Instant uploads not implemented, we should hide them
- [X] Logging: Will remain for official release or only betas? -> KEEP
- [x] Suggestion (Feedback) mail: now `ios-beta@owncloud.com`, it should become `apps@owncloud.com` and the subject also to be changed
- [x] Recommend to a friend mail should point to everywhere, currently to the old app.
- [x] Footer title in Settings contains beta. Not suitable for release version. Switching beta for release.

**Comment by michaelstingl** [comment]
> * Logging: Will remain for official release or only betas?

I think it's useful – keep it

**Comment by michaelstingl** [comment]
> * 
> * [ ]  Suggestion (Feedback) mail: now `ios-beta@owncloud.com`, it should become `apps@owncloud.com` and the subject also to be changed

`ios-beta@owncloud.com` is wrong, but I'd like to have different mail for iOS and Android.

Move to?
- `ios-app@owncloud.com`
- `android-app@owncloud.com`

**Comment by jesmrec** [comment]
sounds very good. i will create a tiny issue to change also in Android. But before, this email addresses must be created. Who can take care of this?

**Comment by michaelstingl** [comment]
> this email addresses must be created. Who can take care of this?

I can take care with the admin team.

**Comment by michaelstingl** [comment]
E-Mail not done yet – please keep open

**Comment by michaelstingl** [comment]
Mail created
