### ISSUE TITLE
Drag & Drop II

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#250]
Will continue the work after #79

Suggestion for new options to include:

- [ ] Drag & Drop between Apps (iPad Split View)
- [ ] Start Drag & Drop with the currently multi-selected files?

And an idea from @felix-schwarz : 

> wouldn't it be great if - as soon as one starts a drag and drop operation in the app, the tab bar turns into a toolbar with drop targets for actions like delete. So one could just start a drag, add additional items by tapping on them and then trigger an action by ending the drag on the action's drop target.
> 
> . o O (could also be a very natural, simple way to create a zip file from items in different locations)

**Comment by jesmrec** [comment]
> Start Drag & Drop with the currently multi-selected files?

in any case we should remove the regular multiselection mechanism, so there are users that do not feel comfortable by dragging and dropping.

**Comment by hosy** [comment]
If we drag items out of the App, the dragged items should not appear as table row cells.

**Comment by michaelstingl** [comment]
> If we drag items outside the App, the dragged items should not appear as table row cells.

I don't get it? Screenshot? GIF?

**Comment by michaelstingl** [comment]
I checked the behaviour in some other apps, and they all drag & drop the stacked table cells across the split-view-border. Fine for me to do it the same way…

**Comment by hosy** [comment]
What I mean is, only use the preview images, instead of the table row cell:

![img_0019](https://user-images.githubusercontent.com/736109/52850224-413a7300-3113-11e9-864f-1df8a9665e42.PNG)
