### ISSUE TITLE
A color scheme for the new ownCloud iOS app

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#251]
The new ownCloud iOS app comes with different preconfigured  themes, and there will be options to define own colors…

- Branding
- MDM (via appconfig.org)
- Maybe an option for the end user (select file)
- Maybe with a configuration that gets pulled from the oC server…

To support this, the we need kind of a color scheme, like a set of defined parameters, a common language for the colors we use. (needs to be documented)

In https://github.com/owncloud/ios-app/pull/206#issuecomment-458316736 , I played with Figma.com and built a quick example with some `text-styles` and `color-styles`:

![branding-test](https://user-images.githubusercontent.com/214010/51868594-ae49bc80-234e-11e9-97d4-9a92b5c9284a.png)

My example is not about the actual colors I choose. It is also not about the color names I choose. It's just a rough sketch that we need something similar… On scheme should allow to build dark themes, light themes, very colorful schemes or very desaturated themes. (Maybe also a [Night Vision Mode for Astronomers](https://www.atm-workshop.com/win10-red-mode.html))

The example shows 2 different color sets. One set of colors related to a foreground color, and another set of color related to a background color. If someone prefers to a have a dark foreground color, they should choose lighter colors for the elements on top. Same or reverse for the background color and the related colors.

`background-color` and `foreground-color` are probably the wrong terms. you often read about `brand-color`, `secondary-color` etc

Another example is the [Salesforce Lightning Design System (Design Tokens)](https://www.lightningdesignsystem.com/design-tokens/).

@wuenschedesign Please propose a useful structure of `text-styles` and `color-styles`. It seems [Figma.com's Styles feature](https://help.figma.com/category/221-styles) is the right tool for the job.

BTW: Here you can play with my quick and dirty example:
https://www.figma.com/file/UZQsKEvz78nbysqyMgATVzzK/Branding-Test?node-id=1%3A3

**Comment by wuenschedesign** [comment]
A first draft of how theming, branding and customized use of icons could look like:

The first screen is based on the current colours @felixheidecke used for the Web Design Manual, the second screen uses a brighter shade of the ownCloud corporate blue.

ownCloud Theme 01 | ownCloud Theme 01 Dark
-- | --
![Theming ownCloud 01](https://user-images.githubusercontent.com/40062503/54315588-46c59480-45bd-11e9-909a-80ae2081514a.png) | ![Theming ownCloud 01 Dark](https://user-images.githubusercontent.com/40062503/54315336-90fa4600-45bc-11e9-9c22-e33d3ac5fc71.png)

ownCloud Theme 02 | ownCloud Theme 02 Dark
-- | --
![Theming ownCloud 02](https://user-images.githubusercontent.com/40062503/54315639-63fa6300-45bd-11e9-9dd4-70dd263d36ca.png) | ![Theming ownCloud 02 Dark](https://user-images.githubusercontent.com/40062503/54315374-a4a5ac80-45bc-11e9-8f11-abe425dec7fd.png)

DB Theme | Daimler Theme
-- | --
![Theming Deutsche Bahn](https://user-images.githubusercontent.com/40062503/54315662-7aa0ba00-45bd-11e9-934d-bb60fd155c60.png) | ![Theming Daimler](https://user-images.githubusercontent.com/40062503/54315407-bf782100-45bc-11e9-882a-32d8172eec76.png)

**Comment by michaelstingl** [comment]
> current colours @felixheidecke used for the Web Design Manual

Which ones? Do you have a link?

**Comment by wuenschedesign** [comment]
The manual you showed me yesterday: https://owncloud.github.io/owncloud-design-system/

**Comment by wuenschedesign** [comment]
A current list of neccessary color parameters for branding and styling: https://gist.github.com/wuenschedesign/179f61ae638dd3431eec14afe9c61f60

**Comment by michaelstingl** [comment]
@felixheidecke Can we compare this with the Phoenix color parameters?

**Comment by michaelstingl** [comment]
> The manual you showed me yesterday: https://owncloud.github.io/owncloud-design-system/

The [current state](https://github.com/owncloud/owncloud-design-system/blob/master/src/tokens/color.yml) is based on the UIkit Sass parameters:
- https://github.com/uikit/uikit/blob/develop/src/scss/components/variables.scss
- https://getuikit.com/docs/sass#create-a-uikit-theme

We can try to extend this, or create our own color scheme.

Some of the current colours come the the ownCloud corporate design.

**Comment by wuenschedesign** [comment]
For documentation colors and synchronizing colors with iOS and other frameworks, the following Figma File is in progress:
https://www.figma.com/file/zCY4UXsVjNgzAoihb1bCyM/ownCloud-iOS-Bibliothek?node-id=340%3A618
![Color-Examples](https://user-images.githubusercontent.com/40062503/58184019-9e186d00-7cb0-11e9-8b15-20d1775e4cf1.png)

**Comment by gennaios** [comment]
Hello,

Not sure if such has been mentioned. Any chance the app could adopt a scheme more in keeping with iOS/ipadOS such as pure white including titlebar in light mode and pure black in dark? Perhaps there is another way to brand the app such an icon in the titlebar. I very strongly feel colored titlebars no longer match the aesthetic of iOS and many apps have abandoned such. Perhaps merely as a an optional sidebar background on iPad or iPhone landscape if there is a sidebar or someday. I think such would go a long way to making the app more elegant and perhaps has a strong as they say je ne sais quoi influence on perception and overall feel.

**Comment by michaelstingl** [comment]
I think this issue is super outdated. I'll close, and we can continue in new issues…

**Comment by gennaios** [comment]
> @gennaios did you check the latest 12.0 version?

looked and it seems fine. Sorry for not checking. I'd prefer black as true dark mode with some blue for a logo perhaps. Such would save battery life. :)
