### ISSUE TITLE
[UX] Unite "+" upload button and Create Folder button?

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#252]
I wanted to open a new issue about uniting "+" upload button and Create Folder button? (see previous https://github.com/owncloud/ios-app/issues/198#issuecomment-456743221)

![2019-02-03 23 32 32](https://user-images.githubusercontent.com/214010/52184019-4bed3200-280e-11e9-96f0-e19d75fb4be4.png) | ![2019-02-03 23 32 17](https://user-images.githubusercontent.com/214010/52184020-4bed3200-280e-11e9-92b5-8942ecc5683a.png)
-- | --

To sum it up:
- I don't like "+" and "Select" side-by-side (mixing a word-like button and a icon-like button)
- I think we don't need the "+" upload button and the Create Folder button. Both actions are very similar and can be united in the "+" button.
- Accessibility description for the new "+" button could be "Add item"
- The new menu should have 3 entries:
  - Create folder
  - Upload photos/videos
  - Upload file

I have no strong opinion about the exact wording of the menu items, also no strong opinion about the order of the menu items. I also have no preference to put the button on the left side of the sort-UI or on the right side of the sort UI.

@owncloud/ios-core-developers @wuenschedesign any opinions? "Add" button left or right?

**Comment by pablocarmu** [comment]
This is what other apps are doing. I'd prefer this way, a plus button along a multiselection button in the navigation bar. Then when you tap in the multiselection icon, the table changes to edit mode, the botom toolbar appears and the navigation buttons are changed with a cancel one.

| ![img_dc56db194c39-1](https://user-images.githubusercontent.com/8929738/52195244-6ac3e680-2857-11e9-9e28-7615b972f43f.jpeg) | ![img_dc56db194c39-2](https://user-images.githubusercontent.com/8929738/52195257-76afa880-2857-11e9-876c-66cb3b2b16ea.jpeg) |
|-----------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------|

**Comment by wuenschedesign** [comment]
I put the Upload »+« on the top right. The Select Action goes to the right next to the funnel/tab navigation of the list. Screens 1 and 2 could look like this:

View List | Action Sheet Activated
-- | --
![upload-01](https://user-images.githubusercontent.com/40062503/52210129-39eeac00-286d-11e9-8b06-39b04a382157.png) | ![upload-02](https://user-images.githubusercontent.com/40062503/52210131-39eeac00-286d-11e9-9fe9-878e2da538f0.png)

**Comment by mneuwert** [comment]
@wuenschedesign the problem is when you scroll the table-view header which currently contains "sorting" button and "create folder", it is not sticky and is not visible, so that you won't be able to access "Select" button.

**Comment by michaelstingl** [comment]
Okay, then I'd vote for to put a "select"-icon AND "+"-icon in the top bar.

@wuenschedesign Putting icons in the menu isn't natively supported in iOS. It's very much work to achieve this – we can do it later…

**Comment by wuenschedesign** [comment]
> Okay, then I'd vote for to put a "select"-icon AND "+"-icon in the top bar.
> 
> @wuenschedesign Putting icons in the menu isn't natively supported in iOS. It's very much work to achieve this – we can do it later…

You mean the Icons in the Action Sheet in the screen on the right?

**Comment by michaelstingl** [comment]
> You mean the Icons in the Action Sheet in the screen on the right?

yes

**Comment by wuenschedesign** [comment]
Instead of »Select« we could use an icon, but I have not yet seen, iOS implementing an icon instead of »select«.

**Comment by wuenschedesign** [comment]
The following Screens could show the Select Mode for the list:

Nothing is selected | Some items are selected | All items are selected
-- | -- | --
![select-01](https://user-images.githubusercontent.com/40062503/52211633-8b009f00-2871-11e9-933c-a654bdd26091.png) | ![select-02](https://user-images.githubusercontent.com/40062503/52211634-8b009f00-2871-11e9-9a0d-f68df9fddcab.png) | ![select-03](https://user-images.githubusercontent.com/40062503/52211636-8b009f00-2871-11e9-992b-3cf701bf22bc.png)

In the second row instead of using »Cancel« I changed the top-right Action to »Done«. This is what iOS has implemented. But I recommend Cancel to make clear that the selection process will be canceled without a change.

Nothing is selected | Some items are selected | All items are selected
-- | -- | --
![select-b-01](https://user-images.githubusercontent.com/40062503/52212062-c059bc80-2872-11e9-8acf-da414010c554.png) | ![select-b-02](https://user-images.githubusercontent.com/40062503/52212063-c0f25300-2872-11e9-93d4-8c5b9724de28.png) | ![select-b-03](https://user-images.githubusercontent.com/40062503/52212064-c0f25300-2872-11e9-929c-2c41d0ace65d.png)

**Comment by jesmrec** [comment]
@wuenschedesign there are some apps using two icons, like here the example that @pablocarmu posted: https://github.com/owncloud/ios-app/issues/252#issuecomment-460155201 (only to take an example, that one comes from another popular sharing environment)

**Comment by wuenschedesign** [comment]
@jesmrec Just with an icon like @pablocarmu suggested above, could work with a small header:

Large Header | Small header | Small header swapped position of icons
-- | -- | --
![upload-c-01](https://user-images.githubusercontent.com/40062503/52213883-758e7380-2877-11e9-8554-fd826ee02775.png) | ![upload-d-01](https://user-images.githubusercontent.com/40062503/52213884-76270a00-2877-11e9-961c-68aebda467e5.png) | ![upload-e-01](https://user-images.githubusercontent.com/40062503/52214022-d28a2980-2877-11e9-9384-cd1f7ab5e889.png)

**Comment by hosy** [comment]
I think "Select" should not be replaced by an Icon. It is also a system item, which changes the title, if it is in editing mode. The icon is not self explaining in my opinion.
@wuenschedesign the large title concept is already implemented in #223 

I more like the first draft of @michaelstingl  with the Plus button on the right side of the sort button.

**Comment by wuenschedesign** [comment]
> I think "Select" should not be replaced by an Icon. It is also a system item, which changes the title, if it is in editing mode. The icon is not self explaining in my opinion.
> @wuenschedesign the large title concept is already implemented in #223
> 
> I more like the first draft of @michaelstingl with the Plus button on the right side of the sort button.

An icon is not self explaining, that’s right, but users can learn to understand it, like users learned to identify a »+« icon as an action for adding new content, file, comment, etc. The tool bar in iOS uses just icons (not that I find all of them understandable).

**Comment by michaelstingl** [comment]
@wuenschedesign is it okay for you that the lower icon/button scrolls away with the files list?

**Comment by wuenschedesign** [comment]
> @wuenschedesign is it okay for you that the lower icon/button scrolls away with the files list?

iOS puts »Select« in the top bar and »add folder« under the top bar (which will be scrolled away). We can do the same.

**Comment by michaelstingl** [comment]
> iOS puts »Select« in the top bar and »add folder« under the top bar (which will be scrolled away). We can do the same.

Sure, we can try this. No problem to change later (wait for first user feedback/research)

**Comment by hosy** [comment]
If we do not put Select in the top bar, replace Select with an Icon. 
@wuenschedesign please can you post a draft with + in top and the checkbox Icon below?

**Comment by wuenschedesign** [comment]
It could look like this then, I guess:
![upload-g-01](https://user-images.githubusercontent.com/40062503/52237507-d2f2e680-28b0-11e9-8028-f5c41b048355.png)

**Comment by pablocarmu** [comment]
The option that I like is _Small header swapped position of icons_ from https://github.com/owncloud/ios-app/issues/252#issuecomment-460267319

**Comment by hosy** [comment]
In a previous comment @pablocarmu posted a screenshot, which has also a solution for us. @ChrisEdS had also the same idea.
Why we don't put the add button in the center of the UITabBar? This is also a solution other apps, like Dropbox, have the same implementation. It does solve all the problems mentioned above. It it is a common UI behavior.

It could looks like this: (look at the add button in the TabBar)

| ![img_7330](https://user-images.githubusercontent.com/736109/52347617-a7900900-2a22-11e9-8b19-c4fe8cbed6df.PNG) | ![img_e839110adf66-1](https://user-images.githubusercontent.com/736109/52347568-8b8c6780-2a22-11e9-9265-3de281a7a9fb.jpeg) |
|-----------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------|

**Comment by michaelstingl** [comment]
Is it a easy thing to add something in the bottom bar? (I wanted to avoid custom UI for now)

**Comment by mneuwert** [comment]
@hosy I don't think this is how Apple encourages to use the tab bar. I find it confusing to mix different paradigms in one UI element.

**Comment by hosy** [comment]
@michaelstingl it is not such a problem to implement it.
@mneuwert I know. I also prefer the Apple solution. But in some cases it makes sense to differ or think about it.

**Comment by felix-schwarz** [comment]
Following a discussion around the 1.0.0 release on RocketChat, I made a change in this direction:

More detailed description: https://github.com/owncloud/ios-app/issues/237#issuecomment-481285829

Visual result:
![Bildschirmfoto 2019-04-09 um 16 50 59](https://user-images.githubusercontent.com/639669/55810319-a85b1f00-5ae7-11e9-983d-0aa9769832eb.png)

**Comment by hosy** [comment]
Maybe we should remove the `Add Folder` button on the left of the sort menu to cleanup the UI?

**Comment by michaelstingl** [comment]
> Maybe we should remove the `Add Folder` button on the left of the sort menu to cleanup the UI?

Sure 👍

**Comment by felix-schwarz** [comment]
Good idea. Done as of 28067c2c3a2437ae7e4b87bdc601bfd5f25590fc and used the opportunity to clean up `SortBar` in general. Now looks like this:

<img width="598" alt="Bildschirmfoto 2019-04-10 um 11 15 23" src="https://user-images.githubusercontent.com/639669/55867110-28ce5e00-5b82-11e9-982b-bcc08d6e2af6.png">

**Comment by mneuwert** [comment]
@felix-schwarz the only thing we should also consider if the folder creation should be possible in `ClientDirectoryPickerViewController` which doesn't have a plus button and if I just add it now, it will add the upload stuff as well I guess

**Comment by jesmrec** [comment]
Done, it will be available in 1.0.0
