### ISSUE TITLE
AppSettings: Biometrical lock

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#26]
_As an user i want to lock the app, so that i will be sure that only me can unlock_

AC:

- [ ] Set option to fingerprint if the device supports it
- [ ] Set option to Face ID if the device supports it
- [ ] Only available if passcode was previously set
- [ ] Set branding option to force the passcode
- [ ] Option to cancel the input
- [ ] Always asked when the app is opened
- [ ] The biometric can be cancelled, and then, the passcode is asked
- [ ] Set a time after asking the biometrical, in which the biometrical will not be asked
- [ ] QA

**Comment by javiergonzper** [comment]
I have a question about this user story:
If the user kill the app and open it again we try to make login with biometrical before to insert the numbers
Should we allow the biometrical unlock during the "Brute force protection"?

I mean if the user have to wait 1 hour enter the digits after fail several times the number... should we allow to use the biometrical before that time has passed?

What do you think @michaelstingl ?

**Comment by michaelstingl** [comment]
Wrong Touch ID and Face ID attempts normally are blocked earlier than passcode. Making biometrical unlock work while passcode entry is delayed feels wrong.

**Comment by javiergonzper** [comment]
I agree 👍

**Comment by jesmrec** [comment]
Done
