### ISSUE TITLE
Clear storage

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#260]
Check the following scenario:

1. I have a huge file in the server
2. I download the file, because i want to preview it
3a. I have seen the file, so i do not want it to use my storage anymore
3b. I want to keep the file in the device, because tomorrow i want to view it again avoiding wasting time and bandwidth to download.

So, a new option to clear internal storage is useful, as well as an available offline for files (https://github.com/owncloud/ios-app/issues/134) and(or folders (https://github.com/owncloud/ios-app/issues/135)

**Comment by michaelstingl** [comment]
In the first iteration, I think about a one-time action.

- This should only delete implicit downloaded files
- This should NOT delete files a user selected for "available offline"
- New option for every account
  - Show used space on the device
  - Show available space on the device??
  - Button to delete downloaded data
- Also show used space in Settings (across all accounts)
- New file action for every file

**Comment by jesmrec** [comment]
First step will be removing everything downloaded in a specific bookmark. To remove, we can use:

- Info row action 
- Swipe left in bookmark list

SDK is involved

**Comment by jesmrec** [comment]
Done!
