### ISSUE TITLE
Feedback: Remove spaces from account@host name

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#261]
Feedback from @hodyroff : please remove spaces from account@host name

![2019-02-07_01_10_06](https://user-images.githubusercontent.com/214010/52382528-ebf8c480-2a75-11e9-8ca4-6c6b0fa0bda7.png) | ![2019-02-07_01_10_29](https://user-images.githubusercontent.com/214010/52382529-ec915b00-2a75-11e9-8db7-e0e1937a5299.png)
-- | --

**Comment by jesmrec** [comment]
Done
