### ISSUE TITLE
Term "bookmark" shouldn't be user facing ==> "account"

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#266]
https://github.com/owncloud/ios-app/blob/1116722b386fb20bf892aef4e0a182eb6e8625c2/ownCloud/Resources/en.lproj/Localizable.strings#L19-L21

![2019-02-10 11 32 49](https://user-images.githubusercontent.com/214010/52532677-348bd880-2d29-11e9-82f5-5f0b224ec056.png) | ![2019-02-10 11 32 58](https://user-images.githubusercontent.com/214010/52532678-348bd880-2d29-11e9-8087-92eb48aed5a6.png)
-- | --

**Comment by jesmrec** [comment]
Done
