### ISSUE TITLE
Differentiate new iOS app in App Store and Homescreen while legacy app is still in use

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#268]
New ownCloud iOS app will be released while the legacy ownCloud iOS app is still available in the App Store. I was thinking about a different name ("ownCloud Access") and a modified icon (see mockup). In Q2/Q3, the new iOS app will fully replace the legacy one…

![image](https://user-images.githubusercontent.com/214010/52533487-c51be600-2d34-11e9-9530-701a6165769b.png)

Maybe users could choose to use the regular ownCloud icon instead…

Any other ideas?

@felix-schwarz we discussed this… Could the name in the App Store be "ownCloud Access" "ownCloud File Access" or something different, while on the Homescreen it's only "ownCloud"?

@ChrisEdS we'd need a nice icon…

@hodyroff @pmaier1 FYI…

**Comment by ChrisEdS** [comment]
@michaelstingl Your icon is not nice enough? Or do you want me to use the suggestion you've made?

**Comment by michaelstingl** [comment]
> Your icon is not nice enough?

It would need some more love for the details. But let's wait for a decision first…

**Comment by michaelstingl** [comment]
ChrisEdS Please create us a nice icon with "NEW" in the lower-thirds

**Comment by felix-schwarz** [comment]
> @felix-schwarz we discussed this… Could the name in the App Store be "ownCloud Access" "ownCloud File Access" or something different, while on the Homescreen it's only "ownCloud"?

Yes, you can pick different names for the App Store and the home screen. There is a limit of 30 characters for the App Store name. Regarding the icon, I have a quick idea to contribute:

![Bildschirmfoto 2019-03-29 um 09 34 00](https://user-images.githubusercontent.com/639669/55219696-dd24c780-5205-11e9-831e-c8c2ea07d883.png)

**Comment by michaelstingl** [comment]
solved with https://github.com/owncloud/ios-app/pull/313/commits/563a3674bb713e15fdc07bb984929e3c9c3f68e5
