### ISSUE TITLE
Share public

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#275]
_As an user, i want to generate a public link to any of the items in my list, so i can share my content with other people_

AC (already defined in epic):

* User can create as many public links as he/she wants. It was available from 10.0.4, pending to check if it was backported in any way. For older versions, only one public link per item is allowed.
* Public links have several attributes:

   - Link name
   - Permissions: like in web, it will depend on the kind of item (file, folder):
      - Download / View: files & folders
      - Download / View / Upload: folders
      - Upload only (file drop): folders
   - Password: will be mandatory depending capabilities
   - Expiration date: will be mandatory depending capabilities

Capabilities are also important to take in account. They apply to every account in the same server. The capabilities affecting public sharing are:

- "Allow apps to use the Share API" -> if false, Share View is not available from Files View
- "Allow users to share via link" -> If false, Public link UI is hidden
- "Allow resharing" -> If true and the file is shared privately, no public share available
- "Enforce password protection for..." -> Show in UI somehow, that the password is mandatory
- "Set Default Expiration Date" -> Set the date as default 
- "Enforce expiration date" -> only available if "Set Expiration Date is true". If true, link is not created with empty expiration date.

Some UI drafts will be welcome to discuss implementation.

**Comment by hosy** [comment]
#83
