### ISSUE TITLE
Rename "Add Server" to "Add Account"

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#276]
### Steps to reproduce
Currently the Add Button in ServerListTableView has accessibility label "Add Server". Analog #238 will implement a header view with the title "Accounts"

### Expected behaviour
Should be named as "Add Account"

### Client
**iOS version:**
12.2.4

**ownCloud app version:**
1.0 (1904)

**Device model:**
iPhone X

**Comment by hosy** [comment]
Be sure that UI tests in code are adopted to the changes.

**Comment by michaelstingl** [comment]
What is the visible button text? „Add Server“? This should work as accessibility label as well…

**Comment by hosy** [comment]
There is no text visible, because it is a system `+` button. This text is only for accessibility.

**Comment by michaelstingl** [comment]
On the initial screen, there is a visible button. What is the label there? Just do it same for the "+" button…

**Comment by hosy** [comment]
Yes in initial screen, it it labeled as `Add account`.

**Comment by hosy** [comment]
Already fixed in Master
