### ISSUE TITLE
Wrong spacing for Sort menu in file list

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#278]
### Steps to reproduce
1. Open the file list 

### Expected behaviour
Sort menu should be centered and should have the same spacing to left and right.

### Actual behaviour
Less spacing to the right side.

### Client
**iOS version:**
12.1.4

**ownCloud app version:**
1.0 (104)

**Device model:**
iPhone X, iPhone 8 

![img_cbb592f16bfc-1](https://user-images.githubusercontent.com/736109/53007975-a2768500-3438-11e9-82e6-95e839e934f7.jpeg)

**Comment by jesmrec** [comment]
Done and merged
