### ISSUE TITLE
Add keyboard shortcuts for all UI actions

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#282]
### Expected behaviour
Users should have the possibility to control the app completely with keyboard shortcuts. This is a feature for power users and will give our app a final touch.

e.g.
File list view:
`CMD` + `N` can show the "Upload file" menu

### Actual behaviour
Keyboard shortcuts are implemented only in the passcode view.

### Client
**ownCloud app version:**
1.0.0

**Device model:**
iPad

**Comment by jesmrec** [comment]
Already done
