### ISSUE TITLE
Long bookmark name overlaps "Back" button in root

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#290]
In the upper bar, the `Back` button does not appear. I guess the problem is the long bookmark name. By changing orientation to landscape, the `Back` word does not appear either

![screen shot 2019-02-27 at 11 22 57](https://user-images.githubusercontent.com/14894746/53483775-869b6080-3a82-11e9-89a9-62c41a610dc8.png)

![screen shot 2019-02-27 at 11 23 08](https://user-images.githubusercontent.com/14894746/53483779-8a2ee780-3a82-11e9-8848-31157043b3cb.png)

**Comment by hosy** [comment]
In my opinion this is a normal behavior in iOS.

**Comment by jesmrec** [comment]
ok, if it is the expected behaviour, can be closed.

**Comment by michaelstingl** [comment]
Yeah, long title make the text disappear, so only the arrow is left.
