### ISSUE TITLE
"No matches" label in file search is hidden by keyboard

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#292]
### Steps to reproduce
1. Open File list and type a search string into the search field, with non matching files

### Expected behaviour
Labels "No matches" and "There is no results for this search" should be completely visible for the user.

### Actual behaviour
Labels are currently hidden by the keyboard

![img_7544](https://user-images.githubusercontent.com/736109/53557555-7482f600-3b46-11e9-89e6-525d3f3a4af1.PNG)

### Client
**iOS version:**
12.1.4

**ownCloud app version:**
1.0.0 109 (ce6108d)

**Device model:**
iPhone X

**Comment by hosy** [comment]
Fixed in #358

**Comment by jesmrec** [comment]
Fixed in #358
