### ISSUE TITLE
Lack of title in "Lock application" View

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#294]
Every view inside `Settings` contains the big size title but the Lock Application:

![screen shot 2019-02-28 at 15 07 28](https://user-images.githubusercontent.com/14894746/53572043-9d1ce700-3b6a-11e9-9660-a021b49e5c69.png)

It should have title as the other ones

**Comment by hosy** [comment]
@jesmrec is it ok, to fix this bug in #284 ?

**Comment by jesmrec** [comment]
In my opinion, it is always better to address different issues in different PRs, so the QA and code controls are more accurate for a specific feature/fix. Only let me know where the fix is done and i will take care when the PR is on my side.

**Comment by hosy** [comment]
Ok, I will fix this and open an other PR.
