### ISSUE TITLE
Login: Support password managers 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/ios-app#30]
It's 2018 and I'm finally using password managers to decide and remember my passwords for me. 

It'd be great if the new ownCloud iOS app supported these extensions on its login view. Slack as a reference: 

| "Password Manager" badge | Extension |
|---------|-----|
| ![slack_pass_manager1](https://i.stack.imgur.com/oToJB.jpg) | ![slack_pass_manager2](https://i.stack.imgur.com/zKCfS.jpg)|

Found some inspiration for you guys:
- https://github.com/agilebits/onepassword-app-extension
- https://github.com/lastpass/generic-password-app-extension

**Comment by michaelstingl** [comment]
related: https://github.com/owncloud/ios/issues/818

**Comment by SamuAlfageme** [comment]
Forgot to report the results of testing this in beta build 31 together with Bitwarden. Works great: 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/40967137-9a49a102-68b2-11e8-857e-93f6de43d4b9.gif"/>
</p>

btw. yesterday Apple presented native support for this: https://twitter.com/1Password/status/1003824297725460481 🎉

**Comment by michaelstingl** [comment]
Keep it open for the new API or create a new issue?

**Comment by felix-schwarz** [comment]
@SamuAlfageme Thanks for testing!

@michaelstingl I think we can close this issue and create a new issue "iOS 12 refinements" to collect things to re-evaluate for iOS 12.

**Comment by michaelstingl** [comment]
done in https://github.com/owncloud/ios-app/issues/66
