### ISSUE TITLE
Files: Thumbnails

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#31]
__As an user, i want to see thumbnails, so i can check what the pic contains without downloading and opening it__

- [x] Thumbnails for non-dowloaded images / gifs
- [x] Thumbnails for dowloaded images / gifs
- [x] Thumbnails for videos, if the server supports it
- [x] QA

**Comment by felix-schwarz** [comment]
Work on this has started here: https://github.com/owncloud/ios-app/pull/32

Thumbnails for videos sounds interesting. Do you know which formats are supported by the server?

**Comment by michaelstingl** [comment]
For thumbnails of video files, you need to install ffmpeg on the server. It can create static images or short GIF's. @cdamken could you point us to your solution?

**Comment by cdamken** [comment]
@IljaN is the one helped me to configure on my server.

**Comment by felix-schwarz** [comment]
Ok, so I assume a lot of additional formats can be added through configuration / customization that aren't contained in the stock version I currently use for testing. Not just video files, but also PDF files, Office files, etc.

While I assume most users won't have this set up, some definitely will, so the app would have to request thumbnails for every file to find out.

For a folder filled with a 1000 files without previews, that's a lot of unnecessary overhead both locally and remote.

One solution I thought about is to make the app "smart" insofar as it learns which MIME-Types it didn't get back a thumbnail for, then no longer request thumbnails for objects of the same MIME-Type. However, in the (highly likely) case someone gave a file of a supported file format a wrong suffix (say, save a PDF with a .png file name) and preview generation fails for it, thumbnails would no longer be requested for all other PNG files, either. So, nope, not a solution, either, after all.

Right now, I can see only two ways to deal with this:
1) always request thumbnails for every file
2) implement https://github.com/owncloud/core/issues/31267 on the server and send requests out only for actually supported mime types 

Other/better suggestions welcome. ❤️

/cc @DeepDiver1975 @michaelstingl

**Comment by michaelstingl** [comment]
There is also [`ffmpegthumbnailer`](https://github.com/dirkvdb/ffmpegthumbnailer) that could help…
