### ISSUE TITLE
ClientDirectoryPickerViewController shows "Empty folder" when selecting target directory for Copy / Move

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#319]
### Steps to reproduce
1. Select a file and tap on "Copy" or "Move"
2. Select a directory which doesn't contain subdirectories

### Expected behaviour
Since as a user I know that the selected folder is not empty (e.g. it contains a lot of files which are just filtered out in this case), it is irritating that "empty folder" is shown. May be in this case nothing should be shown at all.

### Actual behaviour
Prominent "Empty Folder" message is shown in the middle of the screen

### Client
**iOS version:**
12.x

**ownCloud app version:**
master / 868097f150b66e1fd9b79d5996c4e06b4f0ae025

**Device model:**
any device

**Comment by michaelstingl** [comment]
How dos this look in other products with directory tree and files listing? iOS Files? 3rd party?

**Comment by mneuwert** [comment]
@michaelstingl When selecting target folder for copy / move operation, iOS Files app shows a tree structure in a single view and expands the folder when you tap it, so that the subfolders are shown. Dropbox opens every folder in a new view (similar to our app), but it is also showing files contained in that folder. The files are however greyed out since you can't open them.

**Comment by jesmrec** [comment]
Done!
