### ISSUE TITLE
Implement option for log rotation

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#334]
### Description

Would be great to have an option in app settings to enable / disable log rotation. This means that only the last 24 hours logged messages available in the log file. This will prevent to large log files and it is easier to read for developers.
SDK is also involved into this issue.

### Expected behaviour
Log file contains the log messages of the last 24 hours.

### Actual behaviour
Log file saves all log messages, if enabled

### Client
**ownCloud app version:**
1.0.0 build 113

**Comment by michaelstingl** [comment]
Check permanent logging feature in the desktop sync client:
https://doc.owncloud.org/desktop/troubleshooting.html#logging-to-a-temporary-directory
