### ISSUE TITLE
New app icon

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/ios-app#342]
This issue serves to discuss options for a new icon for the new app.

**Comment by felix-schwarz** [comment]
I have a quick idea to contribute:

![Bildschirmfoto 2019-03-29 um 09 35 10](https://user-images.githubusercontent.com/639669/55219732-f4fc4b80-5205-11e9-8904-ee5727d988de.png)

(without border, actually, making the cloud larger, moving it into focus)

![Bildschirmfoto 2019-03-29 um 09 36 31](https://user-images.githubusercontent.com/639669/55219815-25dc8080-5206-11e9-9f76-7460cc35fe6f.png)

**Comment by michaelstingl** [comment]
@hodyroff @pmaier1 @hurradieweltgehtunter @wuenschedesign @LukasHirt @ChrisEdS Is this something you could image for the new iOS app?

Here you can find the old one for comparison:
https://itunes.apple.com/app/owncloud/id543672169

**Comment by LukasHirt** [comment]
I'd leave it a little bit of space to breath. This feels that the cloud is too much pushed to the edge.

**Comment by hurradieweltgehtunter** [comment]
😱That's definitely a no go.
I pretty sure that in our CI guidelines it is not allowed place the logo in a way that it gets cut. I wouldn't recommend this, either.
Why even change it? The old one looks fine.

**Comment by wuenschedesign** [comment]
That’s a nogo. Sorry. Leave it to the current design. That’s way better.
