### ISSUE TITLE
Show error message in case file can't be opened due to damage

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#357]
## If you found a bug:
Right now if e.g. you open a corrupt image (PNG, JPEG etc), preview is opened but opening the file fails, therefore user sees just a black screen.

### Steps to reproduce
1. Upload corrupt image file to owncloud server
2. Navigate to the folder containing that file in the app
3. Try to open corrupt image

### Expected behaviour
If would be nice, if message would be displayed conveying that the file couldn't be opened.

### Actual behaviour
black screen is shown

<img width="545" alt="Screenshot 2019-04-12 at 12 54 04" src="https://user-images.githubusercontent.com/228537/56032353-476b5b00-5d22-11e9-8f34-fc8db548ae5d.png">

### Client
**iOS version: n/a**

**ownCloud app version: 1.0.0 RC**

**Comment by jesmrec** [comment]
Done!
