### ISSUE TITLE
Offline folder creation in Files App

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#362]
it comes from release 1.0.0

In Files App:

1. Remove connection (plane mode)
2. Create a new folder

Current: After clicking on `Done`, view is not dismissed (folder is not created because the lack of connection)

Expected: View dismissed and file list displayed with the folder pending to be created (feasible?)

@felix-schwarz describes the problem in the following way:

https://github.com/owncloud/ios-app/issues/237#issuecomment-481896627

**Comment by michaelstingl** [comment]
@felix-schwarz what needs to be done here?

**Comment by jesmrec** [comment]
Fixed in https://github.com/owncloud/ios-app/pull/662.
