### ISSUE TITLE
[Feature Request] Show cover/album art when playing music

### ISSUE THREAD

**Issue by mmattel** [owncloud/ios-app#374]
This FR references issue https://github.com/owncloud/ios/issues/935
As you can see, there is already a PR for it, see https://github.com/owncloud/ios/pull/1105
Written by https://github.com/andrevz
@jesmrec 

I am wondering if that could be reused / implemented in the new IOS app...

**Comment by jesmrec** [comment]
We will take it in account and check in which part of the roadmap fits better. Thanks for opening!!!

**Comment by mmattel** [comment]
Hi @jesmrec, I would be happy if that would find its way into the roadmap, not seen so far in it...

**Comment by jesmrec** [comment]
ok @mmattel, we will discuss about it 

CC @hosy @michaelstingl
