### ISSUE TITLE
Upload video from Albums

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#375]
### Steps to reproduce
1. Upload -> From Photo Gallery or Album
2. Select one or more videos

### Expected behaviour
Video or videos uploaded

### Actual behaviour
Anything uploaded

iPadAir2 v12.2
iPhone 6Plus v12.2
iPhoneX v12.2

**Comment by mneuwert** [comment]
@jesmrec nothing is uploaded?

**Comment by jesmrec** [comment]
Fixed!
