### ISSUE TITLE
Collisions in Album uploads

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#377]
Comes from: https://github.com/owncloud/ios-app/issues/365

By selecting multiple files from Albums to be uploaded, the number of name collisions grows up.

It can depend on several issues, like the photo library used in every device.

Errors are shown like:

![Screenshot 2019-05-14 at 10 52 21](https://user-images.githubusercontent.com/14894746/57684632-7719c580-7636-11e9-85f0-5d129ff989c1.png)

**Comment by hosy** [comment]
Should be fixed with https://github.com/owncloud/ios-app/pull/430

**Comment by jesmrec** [comment]
Fixed in #430
