### ISSUE TITLE
Background task manager

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/ios-app#386]
We have a couple of background features on our roadmap like f.ex.:
- background photo upload
- background available offline sync
- background file tree update

What they all share is the need to run code periodically while the app is in the background - and/or based on app state change events.

## Architecture

Since the above list will certainly grow in the future, I think it'd be great to take a modular approach to this, possibly structured like this:

- `BackgroundTaskExtension`s, based on the `OCExtension` mechanism:
    - leverage the `location` and `features` properties to find matching extensions
    - the `location.identifier` part could represent certain time events (like `launch`, `periodic`, `didBecomeBackgrounded`, `didComeToFront`, …)
    - the `features` part could be used to define restrictions (like `lowBattery`, `wifiAvailable`, `backgroundOnly`, …) on when the action the extension represents should or shouldn't be run
    - `provideObjectForContext` returns `BackgroundTaskAction` instances
    - `BackgroundTaskExtensionContext` (an `OCExtensionContext` subclass) could provide additional information for `BackgroundTaskExtension`s to make decisions on whether they want their action be run at a certain time
- `BackgroundTaskAction` encapsulates an action to run (f.ex. a block). It provides a method to indicate completion (possibly calling a completionHandler underneath), so it can run asynchronously. To the extent that result values are needed (I think this is the case for background tasks), they could be implemented as properties that the `BackgroundTaskManager` would then access on task completion. Main benefit of having these as properties rather than completion-method parameters would be: new ones can be added without breaking existing code + providing default values.
- a `BackgroundTaskManager` that ties all of this together
    - provides methods for the respective time events (like `launch`, `periodic`, `didBecomeBackgrounded`, `didComeToFront`, …)
    - creates a `BackgroundTaskExtensionContext` describing the respective event and then uses that to query `OCExtensionManager` for matching `BackgroundTaskExtension`s
    - asks the `BackgroundTaskExtension`s to provide `BackgroundTaskAction`s using the same context, then takes care of running these actions

## Modularity / Custom features for clients

Every background (or timed) feature could then be encapsulated into its own `BackgroundTaskExtension` and no worries be spent on adding calls to every such feature's implementation in the various places.

Like with the `OCExtension`-based `Action`s system we already have in the app, this would be especially useful when creating special features for clients that shouldn't find their way into the main/public code base.

**Comment by felix-schwarz** [comment]
Before I forget: the existing `OCBackgroundManager` and `OCBackgroundTask` (providing a convenient API around extending the time the app continues to run after being backgrounded) from the SDK might be of use in the implementation as well.

**Comment by felix-schwarz** [comment]
On another thought: maybe `BackgroundTask*` is a bad choice for a prefix for these classes, considering the existence of `OCBackgroundTask*`.

`ScheduledTask*` would likely be a better pick as a class name prefix for this.

**Comment by jesmrec** [comment]
done
