### ISSUE TITLE
Improve discoverability of the current path dropdown

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#387]
### Steps to reproduce
1.  Open file list
2. Open subfolder

### Expected behaviour
As a user I want to see, that the navigation title has an action and is touchable.

### Actual behaviour
Navigation title is touchable, but cannot easily discovered by the user.

![2019-05-17 16 58 22](https://user-images.githubusercontent.com/736109/58009832-8cd43280-7aef-11e9-889d-ea0b90209708.jpg)

### Client
**iOS version:**
12.3

**ownCloud app version:**
1.0.0 (119) a9b3a87

**Comment by hosy** [comment]
Was solved by adding a chevron beside the navigation title.

![Simulator Screen Shot - iPhone 8 - 2019-05-20 at 11 01 59](https://user-images.githubusercontent.com/736109/58009882-a5dce380-7aef-11e9-8dbb-11f4aacf4a6a.png)

**Comment by jesmrec** [comment]
Done
