### ISSUE TITLE
Add an activity indicator for "Delete Offline Copies" action

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#393]
As an user I want to see, that a job is running, if I execute the action "Delete Offline Copies". This is very important, if there are many offline copies available.
### Steps to reproduce
1. Swipe left on account
2. Select "Manage"
3. "Delete Offline Copies"

### Expected behaviour
In the action row "Delete Offline Copies" an activity indicator should be shown as accessory view.

### Actual behaviour
User cannot see that the job is running.

### Client
**iOS version:**
12.3

**ownCloud app version:**
1.0.0. (119) 55816fb

**Comment by jesmrec** [comment]
Done in #438
