### ISSUE TITLE
Implement media player using AVKit

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#395]
Right now media files are opened using `WKWebView` which facilitates some rudimentary media playback. It would be however much nice to have a proper media player used to play audio and video files and even showing album artwork as requested in #374.

This can be easily done with `AVPlayerViewController`:
https://developer.apple.com/documentation/avkit/avplayerviewcontroller

**Comment by hosy** [comment]
@mneuwert would be cool to have this. This would also have the advantage to directly stream the file, if the media file is locally not available!?

**Comment by michaelstingl** [comment]
Yeah, [MP4 Streaming](https://rigor.com/blog/optimizing-mp4-video-for-fast-streaming) should be supported if the media files has the correct format.

**Comment by mneuwert** [comment]
@hosy @michaelstingl yeah, should be possible!

**Comment by jesmrec** [comment]
Done in #429
