### ISSUE TITLE
[Feature Request] pre selectable default account for uploading media files

### ISSUE THREAD

**Issue by mmattel** [owncloud/ios-app#396]
### Tell us what could be improved:
I do not know if this is already impemented or considered, at least not found in any backlog.

If you want to (instant) autoupload media files, you might want to pre define the account used if multiple accounts are present.

Imagine having accounts on three different ownclouds. Lets say one private and two business.
Now you of course want to define which account will be the one defined as target for you automated media file upload. Independent of which account you currently have activated, the pictures should only go into the defined one and not the active one. Not waiting that the defined one gets activated, upload in the background to the defined while working with the activated !

Also referencing #116 (Instant uploads)

**Comment by michaelstingl** [comment]
In the settings, you can choose account and upload folder.

**Comment by mmattel** [comment]
You misunderstand the purpose of this issue.

Yes you can have eg three accounts.

But it uploads ALWAYS to the account which is currently active.
The request was, to add a functionality to predefine which account to be used independent which one is currently active! Else you switch upload target clouds and you have a distributed mess with your uploaded medias!

Default: no behaviour change, use the active one
Change: default or defined

**Comment by hosy** [comment]
@mmattel I do not agree. you can select the account in the settings and only this account will be used. 
If it is not working for you, please add a bug issue and send us log files please.

**Comment by mmattel** [comment]
@hosy yes you can select the account and that account will then be taken for uploading files - true.

Lets look at the "Media upload" setting. You can say, yes upload it or no.

Imagine the following. You have two (or more) accounts. One for private and one for business purposes. Having the media upload enabled, you do for sure not want to mix up uploads to the account that is just active, do you? You end up in a totally mess. What went where. Got the point?

This is this FR about. Being able to define a fixed account frm a list for uploads independent of the active one.

**Comment by hosy** [comment]
@mmattel sorry, I don ´t get it. I just tested it again. The account you select in the settings, will always be used for uploading, regardless which account is currently active.

Or what do you mean with _active_?

**Comment by michaelstingl** [comment]
@mmattel sounds like you're using the legacy ownCloud iOS app. Can you confirm you're using the new app? (https://apps.apple.com/app/id1359583808)

This is the user flow in the settings of the new app when you enable Media upload.

![IMG_0012](https://user-images.githubusercontent.com/214010/82726803-ca613200-9ce6-11ea-90d4-266beeebddc7.PNG) | ![IMG_0013](https://user-images.githubusercontent.com/214010/82726802-c9c89b80-9ce6-11ea-9579-dbedcc7b7a7c.PNG) | ![IMG_0014](https://user-images.githubusercontent.com/214010/82726801-c9c89b80-9ce6-11ea-9b1d-e74b12648ffd.PNG) | ![IMG_0015](https://user-images.githubusercontent.com/214010/82726799-c8976e80-9ce6-11ea-8cbc-6d23de43a20b.PNG)
-- | -- | -- | --
Select account | Navigate to folder | Choose folder | Settings

In case you encounter a bug, please open a new issue and provide the necessary information.

**Comment by mmattel** [comment]
@michaelstingl @hosy 
mea culpa :man_facepalming: I have the new app, but I completely missed this new feature I requested - shame on me.

I just gave it a try and it works.
I also identified bugs. I will file a bug report
