### ISSUE TITLE
Hide "Log files browsing" option if log files are disabled

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#397]
From: https://github.com/owncloud/ios-app/pull/382#issuecomment-493897390

In View Settings -> Logging -> disable the option "Log File"

Current: Browse log files is displayed, but no logs will be stored there anymore
Expected: Browse log option is hidden, because no file is generated.

The special case is keeping the option visible to check older logs. Not sure if this makes sense, since the logs are something that become outdated very fast

**Comment by michaelstingl** [comment]
@jesmrec Are there old files from previous logging sessions that could be accessed?

**Comment by jesmrec** [comment]
if the option is disabled, older logs are not accesible. But, logs get outdated very fast... not sure if this is realistic. When you disable the logs is because you are not interested in logs anymore (saving storage etc..). If we'd rather to keep older logs, we do not have to do anything.

**Comment by michaelstingl** [comment]
Log file list should be accessible when logging has been stopped. Make it a new section that stays there?

**Comment by jesmrec** [comment]
> Log file list should be accessible when logging has been stopped. Make it a new section that stays there?

+1

**Comment by jesmrec** [comment]
Done in #402
