### ISSUE TITLE
Login View

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#4]
First implementation / draft to implement the login view using the SDK authentication feature.

- [X] Welcome view
- [X] List of servers
- [X] Add basic auth server
- [X] Add OAuth2 server
- [ ] Edit view (edit credentials: server name, password) @jgonzalez [WIP] https://github.com/owncloud/ios-app/pull/12
- [x] Certificates view
- [x] Issues view (error handling)  
- [x] Branding options
- [ ] Accessibility tags
- [ ] Design test plan @jesmrec

**Comment by felix-schwarz** [comment]
Discussion produced this:
<img width="796" alt="bildschirmfoto 2018-03-07 um 15 39 29" src="https://user-images.githubusercontent.com/639669/37098669-be6f2136-221e-11e8-9a2a-049bebe6c7ab.png">
<img width="1224" alt="bildschirmfoto 2018-03-07 um 15 40 44" src="https://user-images.githubusercontent.com/639669/37098670-be8e5a06-221e-11e8-8fa8-10341001cb3c.png">

**Comment by pablocarmu** [comment]
We also need a couple view controllers to handle possible login warnings or errors.
Here are a couple sketches representing the UI for this:
![issue sheet](https://user-images.githubusercontent.com/8929738/37331325-f0d0a97c-26a3-11e8-874f-8375c1b55ae6.png)
![issue sheet 1](https://user-images.githubusercontent.com/8929738/37331365-03b4e5f8-26a4-11e8-8f01-3ec12b72e363.png)

@nasli could you take care of the coding of these two?

**Comment by nasli** [comment]
@pablocarmu You can update the tasks in the first comment so we have all listed together and with their progress, thanks

**Comment by jesmrec** [comment]
I have checked the incoming work, and thinking a bit in the UI tests and the accessibility labels. Tell me if i am wrong: for the `Add server` view, are the ids to use the following ones?:

https://github.com/owncloud/ios-app/blob/39be6f57507747347e572b26ba2d2c733e23805c/ownCloud/ownCloud/Bookmarks/BookmarkViewController.swift#L67

https://github.com/owncloud/ios-app/blob/39be6f57507747347e572b26ba2d2c733e23805c/ownCloud/ownCloud/Bookmarks/BookmarkViewController.swift#L127

**Comment by felix-schwarz** [comment]
@jesmrec These identifiers are only used to internally identify objects but are not exposed. It's a good idea to use it for that, too, though.

**Comment by jesmrec** [comment]
ok, it would be nice to have IDs in all UI componentes, to make easier and not-language-dependant the UI tests.

CC @pablocarmu @nasli

**Comment by javiergonzper** [comment]
I have some UI/UX questions on the Edit view:

This is the edit view:

<img width="246" alt="screen shot 2018-04-17 at 16 51 24" src="https://user-images.githubusercontent.com/1815050/38877724-a0c38512-425f-11e8-8dca-70295e41af5a.png">

- The password should appear always filled like the user name. In order if that the user just want to change the Name of the server he do not need to set the password again.

- The button should be a "Save" button not a "Connect" because we are in an edition.

- The "User name" and the "Server URL" should not be editable, because if you change the user name you are using a different account.

- Delete Authentication Data:
  - Basic auth: The password should disappear but the username still
  - Oauth: The token should disappear but if the user try to make login again the "User Name" must to be the same. So the SDK should store not just the token it also have to store the "User Name" or any other "id" that allow to the app check it.

@michaelstingl @felix-schwarz @pablocarmu @jesmrec what do you think about this?

**Comment by jesmrec** [comment]
> The password should appear always filled like the user name. In order if that the user just want to change the Name of the server he do not need to set the password again.

Absolutely agreed. 

> The button should be a "Save" button not a "Connect" because we are in an edition.

In such case, we are not saving new credentials, we are setting a connection with different credentials that were previously set in server side. So, from my side, `Connect` works. 

> The "User name" and the "Server URL" should not be editable, because if you change the user name you are using a different account.

I think that makes no sense to have two identical accounts in the same device (same pair account - user). In which case can be useful to have?  The current app behaviour is not allowing this scenario in any auth method (neither basic, nor oauth nor saml). Android does not allow it as well. But, it anyone considers any scenario, please let it know

> Delete Authentication Data:

> Basic auth: The password should disappear but the username still

Agreed.

> Oauth: The token should disappear but if the user try to make login again the "User Name" must to be the same. So the SDK should store not just the token it also have to store the "User Name" or any other "id" that allow to the app check it.

Which is right now the behaviour when a user deletes auth data in a OAuth2 session?

**Comment by javiergonzper** [comment]
> I think that makes no sense to have two identical accounts in the same device (same pair account - user). In which case can be useful to have? The current app behaviour is not allowing this scenario in any auth method (neither basic, nor oauth nor saml). Android does not allow it as well. But, it anyone considers any scenario, please let it know

Yes, that another thing to take into account: Not allow duplicate accounts.
 
> Which is right now the behaviour when a user deletes auth data in a OAuth2 session?

The credentials are deleted and if on the "Edit view" you tap over "connect" the app ask again for the credentials.

**Comment by felix-schwarz** [comment]
> - The password should appear always filled like the user name. In order if that the user just want to change the Name of the server he do not need to set the password again.

For passphrase-based Authentication Methods, you can get user name and password from the authentication method:

Class authMethodClass = [OCAuthenticationMethod registeredAuthenticationMethodForIdentifier:bookmark.authenticationMethodIdentifier];

```objc
if (authMethodClass.type == OCAuthenticationMethodTypePassphrase)
{
	NSString *userName = nil;
	NSString *password = nil;

	if (authMethodClass.usesUserName)
	{
		userName = [authMethodClass userNameFromAuthenticationData:bookmark.authenticationData];
	}

	password = [authMethodClass passPhraseFromAuthenticationData:bookmark.authenticationData];
}
```

I just added `-[OCAuthenticationMethod passPhraseFromAuthenticationData:]`, so please update to the latest SDK commit first.

> - The button should be a "Save" button not a "Connect" because we are in an edition.

It should be Save unless:
- the user changes the credentials (passphrase-based methods only)
- the user changes the server URL
- there is no authenticationData (== nil) in the bookmark

In those cases, it should be Connect to indicate to the user that the app will reach out to the server before applying the changes.

> - The "User name" and the "Server URL" should not be editable, because if you change the user name you are using a different account.

What if the server and account stayed the same, but the user name has been changed - or server URL changed?

I don't know if the OC server allows changing user names, but at least changing the server URL should be possible.

> - Delete Authentication Data:
>   - Basic auth: The password should disappear but the username still

Yeah, that would be a nice touch.

>   - Oauth: The token should disappear but if the user try to make login again the "User Name" must to be the same. So the SDK should store not just the token it also have to store the "User Name" or any other "id" that allow to the app check it.

Thanks for the additional info on this in the call. This is probably a good idea. Where can I find more info about passing a username to the OAuth2 method? I can't seem to find any mention of this in the https://github.com/owncloud/oauth2 readme.

And, I forgot to mention: when the user hits "Delete Authentication Data", you should also re-run the detection of authentication methods again and adapt the UI as needed. Imagine this scenario:

- user has existing Basic Auth login
- admins enable OAuth2 support on the server and want everybody to use OAuth2 only
- next, admins reset pass phrases to force this change
- user can't login unless the app provides an opportunity to change the authentication method (which we agreed a while back, shouldn't be a user choice – rather the app should always only offer the most preferred one (which one that is is determined by the SDK + MDM-configurable))

> I think that makes no sense to have two identical accounts in the same device (same pair account - user). In which case can be useful to have? The current app behaviour is not allowing this scenario in any auth method (neither basic, nor oauth nor saml). Android does not allow it as well. But, it anyone considers any scenario, please let it know

I have no preference here, neither for allowing two identical accounts, nor for allowing only one account per user.

**Comment by javiergonzper** [comment]
In order to follow the same approach that we have on Android and also on the old app we should not allow to edit the server URL.
Was decided time ago use this approach because for a small number of cases we are giving the possibility to change the server. If you want to edit the server URL: remove the account and add it again.

I think that we should follow the same approach that we have on the Android app.

About edit the user name:
It is not possible modify the user name on the ownCloud app. So this should not be editable.

**Comment by michaelstingl** [comment]
@javiergonzper related: https://github.com/owncloud/ios/issues/1026 - could you answer @konisolde there too?

**Comment by felix-schwarz** [comment]
> In order to follow the same approach that we have on Android and also on the old app we should not allow to edit the server URL.
> Was decided time ago use this approach because for a small number of cases we are giving the possibility to change the server. If you want to edit the server URL: remove the account and add it again.

The new iOS app is planned with a different feature set, especially with regards to sync. So what was determined for its predecessor once is IMO worthy of re-evaluation in that light.

Imagine someone made offline changes, wants to sync, but the server has moved to a new URL. In this case, the ability to simply change the URL could save the user a lot of time and grief.

Also, looking into the future, more server-specific user preferences (like f.ex. per-folder sort order & display options) and niceties (like f.ex. smart folders) could be tied to and saved in or alongside Bookmarks. Ideally, a new domain name for an existing server shouldn't require users to start over here, either.

So, unless there is a technical reason not to support it, users should be able to edit the URL.

> About edit the user name:
> It is not possible modify the user name on the ownCloud app. So this should not be editable.

Yeah, I also just had a look at the admin interface of a Docker-based ownCloud instance and it didn't allow editing the user name.

Can user names be edited if user accounts are managed through a directory service like LDAP?

**Comment by nasli** [comment]
Just to add some insights, and current user requests related the support of duplicate accounts and edit accounts to consider withstand them or not within the new app whether they are still valid:

**User case:** The admin changes the URL and wants it to be updated to all its users:
Migration of URL (through ownBrander it is possible to configure a new URL that will replace all the accounts previously existing in the device with this new URL)

**User case:** User wants to add different accounts, but all have the same domain and username but the authentication is through different idp 
Within new app it will be possible to distinguish these accounts due the new required account field NAME (what could be avoid is to have duplicate accounts with same NAME)

**User case**, edit any account data: 
 owncloud/ios#1026 , could be perform as a migration, so also agree to support them

**OC clients aligned:**  desktop client supports duplicate accounts and recently discussed support it on mobile clients as well.

All the changes related URL, username(id), password, should be reconnect, so the user can rely he has a valid account set up.

**Comment by konisolde** [comment]
As a totally normal, non-technical user, I can speak from experience when our url was changed & I had to update & sync the entire ownCloud folder again. It took ages and a day (well about a day or 2). ;) I travel a lot and rely on access to my ownCloud for business, so that was quite a lot of downtime for me. I'd certainly appreciate a way to update the url without having to remove & re-add.

**Comment by michaelstingl** [comment]
@konisolde ownCloud admins should have a way to provide a better experience for the end user. Normally it shouldn't be necessary to edit the server URL for end users.

@SamuAlfageme @jesmrec Does clients "learn" from permanent redirects? ([HTTP response status code 301](https://http.cat/301))

**Comment by michaelstingl** [comment]
> Yeah, I also just had a look at the admin interface of a Docker-based ownCloud instance and it didn't allow editing the user name.
> 
> Can user names be edited if user accounts are managed through a directory service like LDAP?

No editing of user names. But this is more technical dept due to poor db design than a feature.

**Comment by michaelstingl** [comment]
My doubts:
Is there a risk, that users will change the username unintentionally, and the full content of different accounts will be mixed up? Maybe user would like to switch accounts, but ends mixing them instead…

**Comment by javiergonzper** [comment]
> My doubts:
> Is there a risk, that users will change the username unintentionally, and the full content of different accounts will be mixed up? Maybe user would like to switch accounts, but ends mixing them instead…

@michaelstingl if we do not allow to modify the username that case will not happens except if the user change the URL.
About mix the data... I think that it is not a problem, the SDK should make a propfind of the root folder ( / ) and update everything showing the data of the new server (if it is a different one).

About something that @felix-schwarz said:
> Imagine someone made offline changes, wants to sync, but the server has moved to a new URL. In this case, the ability to simply change the URL could save the user a lot of time and grief.

For me it is a little bit scary that the user have a queue of operations without sync (delete "Documents" folder for example) and then update the URL to a different server and then execute the pending operations.
But maybe this is something that we should discuss in the future when we implement the operation queue.

Anyway I will made the changes requested until now and then show it. After that we can continue deciding things or just let it 👍

**Comment by jesmrec** [comment]
Will the URL editing keep all the local set up of the user account? i mean: available offline stuff, downloaded stuff... Will the process be total transparent to the user?

**Comment by felix-schwarz** [comment]
> > Yeah, I also just had a look at the admin interface of a Docker-based ownCloud instance and it didn't allow editing the user name.
> > 
> > Can user names be edited if user accounts are managed through a directory service like LDAP?
> 
> No editing of user names. But this is more technical dept due to poor db design than a feature.

Ok. If the user name can't change without also changing the account, there really is no need to allow editing the user name.

> For me it is a little bit scary that the user have a queue of operations without sync (delete "Documents" folder for example) and then update the URL to a different server and then execute the pending operations.
> But maybe this is something that we should discuss in the future when we implement the operation queue.

The [sync strategy](https://github.com/owncloud/ios-sdk/blob/master/doc/SYNC.md) has a safeguard in place for this, so the user would have to confirm the action again in that case:

```
*Delete (triggered locally by user)*
…
- Item changed on the server: Warn the user and ask for confirmation (changes suggest the user may want to keep the item). Include last modified date of the server item and timestamp of the action.
…

```

**Comment by SamuAlfageme** [comment]
> Does clients "learn" from permanent redirects? 

Yes, Desktop not only understands but also adapts to 301. After 2.4:
- https://github.com/owncloud/client/pull/6009
- https://github.com/owncloud/client/issues/5954
