### ISSUE TITLE
User Avatar

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#408]
In webUI, users are allowed to set an avatar

![Screenshot 2019-06-24 at 12 08 40](https://user-images.githubusercontent.com/14894746/60010820-dd075d00-9678-11e9-8352-5c332f8c2ba1.png)

the avatar is retrieved with a `GET` request on the following endpoint:

`index.php/avatar/<username>/<size-in-px>`

Where to place the avatar? My suggestion is set it in the list of accounts, instead of the cloud icon on the left.

more ideas welcome

**Comment by michaelstingl** [comment]
> My suggestion is set it in the list of accounts, instead of the cloud icon on the left.

I was also thinking about showing the website favicon instead of the cloud icon on the left.

**Comment by hosy** [comment]
I would like to bring up this issue. I think it could be implemented with a small effort and would look nice to have the avatar in the server list.
