### ISSUE TITLE
Show index bar in general file list

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#413]
In Recents, Favorites, Images and PDF Documents there is already the index bar implemented, to jump in a fast way to the first file name with the beginning letter.
This element is missing in the general file list and it would be handy, to have it too.

**Just noticed, that the index bar is missing in all views! Why it was removed?**

### Steps to reproduce
1. Open file list
2. There is no index bar on the right side

### Expected behaviour
1. Open Quick Access
2. Select Recents, Favorites, Images or PDF Documents
3. Index bar is available on the right side

### Client
**ownCloud app version:**
1.0.1 (124)

**Comment by michaelstingl** [comment]
Maybe only show this if scrolling is necessary

**Comment by hosy** [comment]
## Notes for Testing:

- Index bar is only visible, if sorting is "Sort by name"
- Index bar is only visible, if more than one different letters are available
- Index bar is only visible, if more items are available as visible
