### ISSUE TITLE
Add keyboard commands to all views and actions

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#414]
For a better user experience on the iPad it would be great to control the app completely with the keyboard.
For that all views should implement keyboard commands.

### Steps to reproduce
1. Connect a hardware keyboard to the iPad
2. Press the Command key 

### Expected behaviour
User can control all actions and list selections with the keyboard

### Actual behaviour
Keyboard commands are only available in the passcode view

## Accounts

- Add new Account
- Open Account 1-n
- Select Account
  - Manage
  - Edit
  - Delete
  - Open

## Tab Bar

- Select Files
- Select Quick Access
- Select Status

## File List

- Add Folder
- Add File
- Add Photo
- Toogle Selection Mode
- Show Sort Menu
- Select Rows (Up, Down)
  - Open Item
  - Show More Menu
  - Share File
  - Links
  - Open In
  - Move
  - Rename
  - Duplicate
  - Copy
  - Delete

## Quick Access

- Recents
- Favorties
- Images
- PDF Documents
- Shared Section Items

### Client
**ownCloud app version:**
1.0.1 (124)
**Device model:**
iPad

**Comment by jesmrec** [comment]
Done!!
