### ISSUE TITLE
[UX / PDF] Not possible to navigate between search results

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#418]
Right now if user searches in PDF, he will be presented list of search matches and as soon as he taps on one of the hits, PDF viewer navigates to the page where it is found and highlights the search hit. However all other matches are lost.

So, it would be nice to have some temporary overlay (as an idea) showing number of search matches as well as which match is currently being presented (e.g. 2 of 10) and may be to have "back" and "forth" buttons allowing to navigate between different matches.

See an example from PDF Pro 3 app:
![IMG_FABA22791795-1](https://user-images.githubusercontent.com/228537/60198904-fbb94f80-9842-11e9-942c-630c446217b8.jpeg)

**Comment by jesmrec** [comment]
Done!
