### ISSUE TITLE
iPhone help 

### ISSUE THREAD

**Issue by dlow3much** [owncloud/ios-app#420]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Client
**iOS version:**

**ownCloud app version:**

**Device model:**

### Server configuration
**Web server:**

**Database:**

**PHP version:**

**ownCloud version:**

**Storage backend (external storage):**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by michaelstingl** [comment]
@dlow3much Sorry, but you did not provide any information that could help fix a problem
