### ISSUE TITLE
[UX] Sort option to list folders on top

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#431]
Users have different preferences to have their files and folders sorted. Win user expect folders on top of the list, while Mac users normally have mixed files and folders. (Same behaviour in iOS Files app)

User feedback via OTRS:

> You have different possibilities to order the files/folder.
> If you order it to «Name (A-Z)» or « Name (Z-A)», there are folders and files mixed.
> Better is (like known in Windows Explorer) if you see first all folders and then all files. If you choose «Name (A-Z)», then ownCloud first should show all folders A-Z and then all files A-Z.

~~If we decide to support this, we should put this as an option in the settings, so it works this way in every account and in every folder.~~

### Proposal

- [x] Sort option "Type" should put folders on top (looks there's more to fix: https://github.com/owncloud/ios-app/issues/670)
- [ ] New option should be added to "Advanced Settings" (https://github.com/owncloud/ios-app/pull/643#issuecomment-598654785) to change behaviour for all folders in all accounts
- [ ] New MDM option to set default, can be overridden by user in settings

**Comment by steve3d** [comment]
please have this feature, the mixed folder and files are huge pain for me, 

and although I don't have much files app on mobile phone, it seems the owncloud is the only one which don't have this folder first option.

**Comment by michaelstingl** [comment]
Looks like sorting by "Type" in iOS Files app puts Folders on top.

**Comment by michaelstingl** [comment]
I just checked how others deal with it:

- iOS Files app: Mixed files and folders
- Box iOS app: Folders on top
- Adobe Creative Cloud iOS app: Mixed files and folders
- Google Drive iOS app: Folders on top
- Dropbox iOS app: Mixed files and folders
- OneDrive iOS app: Folders on top

They all don't have an option to change this behaviour.

**Comment by michaelstingl** [comment]
Okay, added my proposal to the top post…

**Comment by jesmrec** [comment]
Done!
