### ISSUE TITLE
Permission increasing UX in reshares

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#439]
### Steps to reproduce
1. User1 shares a folder with User2, granting "share" and "create"
2. User2 shares the folder with User3

### Actual behaviour
After selecting "User3", the permissions view is displayed. "Share" and "Create" are ticked, and "Update" and "Delete" are unticked. By ticking "Update" or "Delete", an alert is shown warning that permissions can not be increased.

### Expected behaviour
Permissions that can not be granted are greyed out or hidden.

**Comment by michaelstingl** [comment]
Check proposal in https://github.com/owncloud/client/issues/7275#issuecomment-508002223

**Comment by mneuwert** [comment]
Implementation note: 
we should check if the share is shared with the current user, if so, then the user should not be able to increase permissions.

See following API request for reference:
GET /ocs/v2.php/apps/files_sharing/api/v1/shares?state=all&shared_with_me=true

**Comment by jesmrec** [comment]
Done!
