### ISSUE TITLE
Make repo accessible for contributors

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#45]
- [x] README
- [x] CHANGELOG - It exist but it is empty. We have to start to fill it once we start to distribute the app to the App Store
- [x] [CONTRIBUTE](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)
     - Done by @nasli (https://github.com/owncloud/ios-app/blob/master/CONTRIBUTING.md)
- [x] [SUPPORT]
- [x] SETUP
     - Done by @nasli (https://github.com/owncloud/ios-app/blob/master/SETUP.md)
- [x] [Issue template](https://help.github.com/articles/about-issue-and-pull-request-templates/#issue-templates)
- [x] [Transifex](https://www.transifex.com/owncloud-org/)
     - We need to merge first the https://github.com/owncloud/ios-app/pull/54 in order to have the last strings file that we need to translate

**Comment by javiergonzper** [comment]
Ok @michaelstingl 👍

**Comment by pablocarmu** [comment]
The link pointing to `SETUP.md` in the `README` is broken and points to no file. Needs to be changed to point to [SETUP.md](https://github.com/owncloud/ios-app/blob/master/SETUP.md)
