### ISSUE TITLE
Autocomplete starts at 4 characters

### ISSUE THREAD

**Issue by pmaier1** [owncloud/ios-app#454]
- Version 1.0.2

**Actual behavior**
The user/group sharing autocomplete starts giving results after the user entered 4 characters, supposedly independent of the server settings.

**Expected behavior**
The user/group sharing autocomplete starts giving results after the user enters the configured number of characters on the server (default = 2).

See here for the config.php setting: https://github.com/owncloud/core/blob/master/config/config.sample.php#L302

**Comment by hosy** [comment]
@pmaier1 for search the capabilities are used and just tested it with demo.owncloud.com.
Search will start after I entered the 3 letter. What setting do we have for demo.owncloud.com?

**Comment by pmaier1** [comment]
> What setting do we have for demo.owncloud.com?

I don't know. Tried with my personal instance, that has the default value (2) and search started after I entered the 4th letter.

**Comment by pmaier1** [comment]
> I don't know.

Well, actually you can find that pretty easily :D the WebUI autocomplete starts searching when you enter 2 characters.

**Comment by pmaier1** [comment]
Just tried with Desktop client. That one starts searching after you enter one character. Looks like the API doesn't respect that setting or so :(

**Comment by michaelstingl** [comment]
Just check settings of demo.owncloud.com with admin:admin

**Comment by pmaier1** [comment]
> Just check settings of demo.owncloud.com with admin:admin

I did here ^^: https://github.com/owncloud/ios-app/issues/454#issuecomment-511873653

Presumably server issue: https://github.com/owncloud/enterprise/issues/3438

**Comment by hosy** [comment]
@pmaier1 @michaelstingl 
thank you for your help. Just fixed the problem.

**Comment by jesmrec** [comment]
Fixed in #455
