### ISSUE TITLE
[UX] Confirm bookmark edit action on top-right

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#47]
I was thinking about a button on the top-right to confirm bookmark edit action. This would also prevent the keyboard to cover the "Connect" button.

| Step 1 | Step 2 |
| --- | --- |
| ![img_3700](https://user-images.githubusercontent.com/214010/39971284-b57dc118-56f8-11e8-9ce5-5fb02329ef14.jpg) | ![img_3703](https://user-images.githubusercontent.com/214010/39971285-b5984c86-56f8-11e8-99d2-0d7655929967.jpg) |

(thanks @frankaellen for the feedback! 👍 )

**Comment by felix-schwarz** [comment]
I've looked at how other apps handle this.

One of my favorite approaches is to remove the blue "Continue" button from the table view entirely (so it no longer scrolls with it) and show it permanently at the bottom of the screen (moving up if the keyboard is shown, so it never gets hidden by it).

That - or the approach you suggested.

**Comment by michaelstingl** [comment]
@felix-schwarz How does the the floating button work in landscape mode? (above keyboard, with thethering and recording bar on top of the screen) . How mich vertical space remains?

**Comment by michaelstingl** [comment]
@mmodrow FYI

**Comment by michaelstingl** [comment]
We should put it on the top-right.

**Comment by michaelstingl** [comment]
Next TestFlight build will bring the button to the top-right:

![img_0519](https://user-images.githubusercontent.com/214010/52496762-8e2ebe80-2bd4-11e9-83ea-9107d9aa113b.PNG) | ![img_0520](https://user-images.githubusercontent.com/214010/52496763-8e2ebe80-2bd4-11e9-8de3-56afeb4156bc.PNG)
-- | --


Not everybody in the team is a fan, but we'd like to test-drive this…
