### ISSUE TITLE
Allow sorting asc/desc in sort menu for all sort methods

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#470]
## Description
At the moment it is only possible to change sorting asc/desc for sort method **name**. 
Look at the iOS 13 sort menu in Files.app. If you tap on the sort method again, it will change the sort direction and the arrow will show the sort direction.

### Steps to reproduce
1. Open file list
2. Open  sort menu

### Expected behaviour
As a user I want to sort asc and desc also for the other available sort methods.

### Actual behaviour
Only for sort method name sort direction can be changed

### Client
**iOS version:**
12.4

**ownCloud app version:**
1.0.3

### Screenshot of the iOS 13 sort menu in Files.app

![IMG_029B5CC31B31-1](https://user-images.githubusercontent.com/736109/62361550-903a6000-b51b-11e9-8fe1-91d34172e958.jpeg)

**Comment by jesmrec** [comment]
Done!
