### ISSUE TITLE
Reorganize Navigation Bar

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#477]
We got some feedback from usability tests, that the actions in the navigation bar can be not easily discovered. Furthermore it is to overloaded with `Back Button`, `Title`, `More Button` and `Select Button`.

### Steps to reproduce
1. Open File List
2. Navigation Bar UI

### Expected behaviour
Navigation Bar should contain the following buttons:
- `Add button`, with all create actions inside
- `More button` with the same actions, like in the more action menu, but for the top item. If it is the root item, the actions `Delete`, `Move`, `Copy`, `Duplicate`, `Rename` are not available.

The `Select button` should be moved to the sort bar on the right side. This button will have an icon instead of a title.

### Client
**iOS version:**
12.4

**ownCloud app version:**
1.0.4

**Comment by jesmrec** [comment]
Done
