### ISSUE TITLE
[UX] Field navigation in edit bookmark screen

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#48]
| any field | last field |
| --- | --- |
| ![img_3703-a](https://user-images.githubusercontent.com/214010/39971414-cdac2426-56fa-11e8-8ce8-aefd19d6b99f.jpg) | ![img_3703-b](https://user-images.githubusercontent.com/214010/39971415-cdc49c68-56fa-11e8-95dd-c74da1f28895.jpg) |

(thanks @frankaellen for the feedback! 👍 )

**Comment by michaelstingl** [comment]
> how about "Continue" + "Go"?

👍

**Comment by michaelstingl** [comment]
@mmodrow FYI

**Comment by michaelstingl** [comment]
I just found, when using OAuth 2.0 for login, we already have arrows and `Done` in the `SFAuthenticationSession` view. We should have the same buttons on both screens. Can we control what buttons to show in the `SFAuthenticationSession` too?

| edit bookmark screen | `SFAuthenticationSession` 1st field in focus | `SFAuthenticationSession` last field in focus |
|---|---|---|
| ![2018-08-21 19 06 57](https://user-images.githubusercontent.com/214010/44449111-8743cd80-a5ed-11e8-82ad-6887f9df46d1.png) | ![2018-08-21 19 07 53](https://user-images.githubusercontent.com/214010/44449112-8743cd80-a5ed-11e8-855f-b54e18be6427.png) | ![2018-08-21 19 08 22](https://user-images.githubusercontent.com/214010/44449214-cbcf6900-a5ed-11e8-95d9-93b592da3c93.png) |

(screenshots show iOS12 beta)

**Comment by michaelstingl** [comment]
Seems the arrows are Safari-only, nothing that can be used in own Apps 😞 

Seems, this has to do with [`inputAccessoryView`](https://developer.apple.com/documentation/uikit/uiresponder/1621119-inputaccessoryview) (attach an accessory view to the system-supplied keyboard ).

Of course, there are projects that try to mimic the Safari style:
https://github.com/danielinoa/TextFieldsTraversalController

**Comment by hosy** [comment]
I added a `inputAccessoryView` for rows username and password. `ReturnKeyType` will also be set.
@michaelstingl you can checkout this branch if this is working for you.

![Simulator Screen Shot - iPhone 8 - 2019-03-10 at 11 31 35](https://user-images.githubusercontent.com/736109/54083736-4bbde600-4328-11e9-8023-04f9a480a0ac.png)
