### ISSUE TITLE
New permission in public links since 10.2.1

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#480]
Public link folder has splitted up the `Download/View/Upload`permission in two:

- Download / View / Upload
- Download / View / Edit

This is the look in the web UI:

![Screenshot 2019-08-12 at 09 52 01](https://user-images.githubusercontent.com/14894746/62851840-cb8d1980-bce7-11e9-8acc-37d673ff7456.png)

Before, the  `Download / View / Upload` was a 15, now it is a 5.
`Download / View / Edit` is 15.

Other permissions did not change.

**Comment by michaelstingl** [comment]
I'd go directly for the roles API

**Comment by pmaier1** [comment]
https://github.com/owncloud/ios-app/issues/506
