### ISSUE TITLE
[iOS 13] Support Multiple Windows on iPad

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#488]
# Multiple Windows on iPad

On iPad OS 13 an app can have multiple windows, this should be supported.

Which action should open a new Window?
- Open Account
- Show Items Detail View

## Open Account

In the `Account View` it should be possible to open an account as a new window.
This makes it possible to have a `Midnight Commander` view side by side.

I would recommend to implement this action with the new `UIContextMenu` which will be shown on a long press on the account cell, because we already have so many table cell switch actions.

## Show Items Detail View

In the `More` context menu for every item, it should be possible to open this item or folder in a new window.

## State Restoration

If the app was quit by the system or user we have to implement iOS State Restoration to bring back the state after the app will be launched, before the app was terminated.

**Comment by jesmrec** [comment]
Ready for 1.2
