### ISSUE TITLE
[UX] File list > bookmarks: button "Disconnect" sounds wrong

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#49]
Currently bookmarks feel like folders. This also how they probably will show up in the Files app (https://github.com/owncloud/ios-app/issues/7#issuecomment-388300629).

For going back from the root folder of one account to the bookmarks screen, "Disconnect" is shown. It feels weird, because it won't be really disconnected in the future. New images might background-upload to this account… Or I upload files from other apps….

I'd propose to use the same arrow to go back to the parent screen. I also noticed, that the swipe from the edge of screen is not working to go from the root folder back to the account list.

Please check look and feel of the same action in the iOS Files app. (slightly different on iPad)

| bookmarks | root folder | sub folder |
| --- | --- | --- |
| ![img_3704](https://user-images.githubusercontent.com/214010/39971565-9a3b87f0-56fd-11e8-8658-5ece203681bf.png) | ![img_3705](https://user-images.githubusercontent.com/214010/39971566-9a6ffad0-56fd-11e8-8e5d-6dfb1f56e16a.jpg) | ![img_3706](https://user-images.githubusercontent.com/214010/39971567-9a87f856-56fd-11e8-94b6-c9512cccce88.png) |

**Comment by jesmrec** [comment]
The arrow back has the sense of browsing back in the folder structure.

I would use some wording to point the the server list. `Servers` or `Server list` sounds good for me.

**Comment by michaelstingl** [comment]
@jesmrec you are right. iOS Files app also don't use Arrow-only:

| Accounts | Files list |
| --- | --- |
| ![2018-05-15 18 34 49](https://user-images.githubusercontent.com/214010/40071164-530c4314-5870-11e8-85ca-11985e1625da.png) | ![2018-05-15 18 34 57](https://user-images.githubusercontent.com/214010/40071166-5327909c-5870-11e8-9601-6168d2985e34.png) |

**Comment by michaelstingl** [comment]
@wuenschedesign Could you have a look? Any ideas?

**Comment by michaelstingl** [comment]
fixed in #238
