### ISSUE TITLE
[File list] Local search

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#50]
__As i user i want to search in the current file list using patterns, so i can see easily only the files with any pattern in its file name__

AC:

- Bar in the upper side of the screen, between the top bar and the sorting options.
- Initially, by default, empty with a hint `Local search` 
- The user types there a string. The file list shown only the file names that match the string (posibility of using metacharacters -> * , ? )
- The filtered list will be displayed using the selected sorting mehod
- If any file matches, list will be shown empty

**Comment by SamuAlfageme** [comment]
@jesmrec I believe this FR should be renamed to "_local search_" as the AC match those of searching file names and extensions inside a folder. 

"_Filtering_" is rather used when starting from a preset list of alternatives (see ref: https://ux.stackexchange.com/a/4756) - e.g. these are the filters available in ownCloud's webUI as for today: 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/40644636-0fd82cf2-6324-11e8-830d-82ad2665b8a7.png"/>
</p>

Feel free to open a second issue if that's also desired (I believe it is) - the "favorite" filter is already part of https://github.com/owncloud/ios-app/issues/52

**Comment by jesmrec** [comment]
ok, i will change the wording to fit the one in web UI. The important issue here is not to confuse users with the scope of the feature. Thanks.

**Comment by jesmrec** [comment]
Done
