### ISSUE TITLE
Better Alert / Notification Handling

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#513]
For connection issues, server issues, app issues the App will show the standard iOS alert view.
The problem is, if there are more issues at the same time, the user will see to much alerts and sometimes it is no longer possible to use the app.
e.g.
- oC Account has a size limit
- Photo Upload is enabled
- Size limit was reached
- There are more items in the upload queue
- Result: to much alerts

We should check, if there is a better notification system, which will not block the UI and can be easily dismissed, grouped or a detection, that the user already has seen the main issue.

Maybe we could show an overview of the notifications in the `Status` tab.

### Expected behaviour
App will not blocked by alert views, user can use the app.

### Actual behaviour
To much alert views will block the UI

### Client
**ownCloud app version:**
1.1.0

**Comment by hosy** [comment]
## What the new notification system should handle:

- Show the same error or notice only one time to the user
- After the notification was shown, add it to the status view
- Give the user a possibility to interact with the message (Action, Remove Message)
- Add a button to clear all messages from the status view
- If the app is in foreground use a own notification class to show messages
- If the app is in background show important messages with local notifications

**Comment by hosy** [comment]
This is a very flexible notification class for iOS. Check if we should use this:
https://github.com/Daltron/NotificationBanner

**Comment by michaelstingl** [comment]
already released
