### ISSUE TITLE
NEW ownCloud Mobile app not accepting my login

### ISSUE THREAD

**Issue by jikometrix** [owncloud/ios-app#518]
Hello,

I went to login to ownCloud on my iPhone 8 with iOS 13.1 today. It prompted me to download a NEW ownCloud app. So I did.

I put in my ownCloud site URL and user & pass. It will not take the login. It just shacks like it is a bad login.

I have confirmed the username and passwords is the same one I use for my web interface.

Not sure what to try next if the OLD app is being phased out.

Original post here: https://central.owncloud.org/t/new-owncloud-mobile-app-not-accepting-my-login/22136

Server address is correct. It was able to confirm we had a valid SSL and we run ownCloud at the top level of the domain not in a subfolder.

Running ownCloud 10.1.04

App version looks like 1.1.0 build 142

Mike

**Comment by michaelstingl** [comment]
@jikometrix thank you very much for reporting this issue. Could you create a test account and send to ios-app@owncloud.com ?

**Comment by jikometrix** [comment]
Hello, 
Yes, I'll create the account now. 
- Mike

**Comment by jikometrix** [comment]
Hello 

I have created the test account. 
I have tested to make sure the test account can login to the web interface. 
I have sent the account data to the above mailbox, ios-app@owncloud.com. 

- Mike

**Comment by ChrisEdS** [comment]
I just uploaded an image to the account with my iPhone. Can you please try to connect to your provided test account and test it as well?

**Comment by jikometrix** [comment]
I'll try it now.

**Comment by jikometrix** [comment]
I tested with test account and test account does login. 

However, it does not have 2FA turned for the account. 

The account I was having trouble with has 2FA enabled. 

Maybe I should try to enable 2FA on the test account and try again?

I can send you the 2FA code to ios-app@owncloud.com when I do.

**Comment by jikometrix** [comment]
I have sent you the TOTP Second-factor Auth to  ios-app@owncloud.com .

Will test again now.

**Comment by jikometrix** [comment]
Now that TOTP Second-factor Auth is enabled it will not allow account login.

**Comment by michaelstingl** [comment]
@jikometrix to use 2FA in the desktop and mobile apps, you need to enable OAuth 2.0 app on the ownCloud server. You can find more information in @lefherz 's blogpost:
https://owncloud.org/news/how-to-use-two-factor-authentication-with-the-owncloud-desktop-client-or-mobile-apps/

**Comment by jikometrix** [comment]
Hello, 

Ooooh, okay. I had forgotten about the "App passwords / tokens" section for the mobile app and desktop. Ugh. 

I'll do that. Thanks. 

- Mike

**Comment by jikometrix** [comment]
Hello, 

Of course that worked as it is supposed to. 

This was user error. 

- Mike
