### ISSUE TITLE
In-App Editor for simple Text-Files

### ISSUE THREAD

**Issue by Grreg** [owncloud/ios-app#519]
Hey guys,

first of all thanks a lot for the new app it feels *much* more intuitive than the old one and seems to be much faster (even if its only a better user experience, great job!).

I used the old app in many cases to have my personal notes in my cloud available and also being able to add notes. As I want to have all my data (also my personal notes) in my cloud and not an different app this worked for me pretty well.

With the new app I cant edit my notes (txt-files).

This is obviously no bug, but a feature request.

### Steps to reproduce
1. Create a simple txt file on the cloud
2. Open the file txt file in the ios app
3. try to edit it

### Expected behaviour
A simple editor should be opened with Discard/save button. Thats it.

### Actual behaviour
The possible actions are generic like Share, open with other app, etc. but no "edit" as this is ofc only for txt files relevant.

### Client
**iOS version:** 12.4.1

**ownCloud app version:** 1.1.0

**Device model:** iPhone XR

### Server configuration, Logs, Web Server error log, owncloudlog
(i skip these, let me know if you need them)

### Tell us what could be improved:
Thanks so far for the effort!

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/ios-app/issues/317
