### ISSUE TITLE
[UI] Sharing: search for a user with blinking screen

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#524]
### Steps to reproduce
1. Open the card of any item -> Share this file/folder
2. Type to search the recipient

### Actual behaviour

Every character you type, the screen blinks (it is showing an empty view with "Searching" message):

![Oct-09-2019 14-39-27](https://user-images.githubusercontent.com/14894746/66482150-a1b36180-eaa2-11e9-8246-5d5426283313.gif)

### Expected behaviour

IMHO, not needed to display a "Searching" message/view for every typed character. Showing an spinner or similar in the same view should be enough. Showing two screens by switching them so fast is bothering.

### Client
**iOS version:** 13.1

**ownCloud app version:** 1.1.1

**Device model:** iPhoneX

### Server configuration
**ownCloud version:** 10.2.1

**Comment by hosy** [comment]
@jesmrec fixed in commit 18f7192

**Comment by jesmrec** [comment]
Fixed
