### ISSUE TITLE
Share sheet II

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#539]
Placeholder issue to collect information for the 2nd iteration of the share sheet…

- Works in iOS Photos app
- Needs own UI?? @hosy could you add some details

**Comment by hosy** [comment]
## Needed UI:
- If more than one account exists, show a account selector
- show folder picker to choose a folder
- Import / Cancel button

**Comment by jesmrec** [comment]
Done and merged. Ready to go
