### ISSUE TITLE
"Copy to ownCloud" possibility is missing

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios-app#559]
### Steps to reproduce
1. Open your Photos app
2. Open the share sheet (bottom left)
3. Try to copy to ownCloud

### Expected behaviour
ownCloud is offered in the list of apps. Copying to ownCloud is possible directly from the app.

### Actual behaviour
ownCloud is not offered on the list. However, the legacy app is available.

![IMG_6E6F84FEF16F-1](https://user-images.githubusercontent.com/33026403/68629996-2d773e00-04e6-11ea-9282-79db7c6cb989.jpeg)

### Client
**iOS version:**
13.2.2
**ownCloud app version:**
1.1.1
**Device model:**
iPhoneX

**Comment by michaelstingl** [comment]
> * Open your Photos app

New iOS app never had a Share Sheet that worked from Photos app. There was already a Share Sheet that worked from most other apps, but it disappeared in iOS 13 as well.

Workaround:
Share with Files app
https://doc.owncloud.org/ios-app/ios_files_integration.html#share-from-other-apps-via-ios-files-app

This is the issue we have for tracking:
https://github.com/owncloud/ios-app/issues/539
