### ISSUE TITLE
[FR] Add "Sync only when WIFI connection exists" setting

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios-app#560]
### Expected behaviour
If you take a lot of pictures on the way, you may not want them to be loaded into your ownCloud immediately, but only when you are back in a WLAN network. 

### Actual behaviour
The images or data are uploaded immediately regardless of the Internet connection used. This can lead to the data budget of the mobile connection being used up unnoticed.

**Comment by michaelstingl** [comment]
Tracked in https://github.com/owncloud/ios-app/issues/560

**Comment by ChrisEdS** [comment]
Tracked in this issue?

**Comment by michaelstingl** [comment]
> Tracked in this issue?

fixed
