### ISSUE TITLE
[FR / PDF] Allow open PDF in another app from PDF Viewer

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios-app#561]
### Steps to reproduce
1. Open a PDF
2. Try to open the PDF in another app like iAnnotate
3. Usually, you will use the arrow symbol on the top right

### Expected behaviour
I can open a PDF while viewing it in the PDF viewer in another app (e.g. iAnnotate or Word) without leaving the PDF viewer.

### Actual behaviour
The arrow symbol at the top right gives me the possibility to jump to a page but not the (expected) possibility to open the file in another program. The UX should also be rethought here.

![IMG_950D6B049616-1](https://user-images.githubusercontent.com/33026403/68631078-a4620600-04e9-11ea-842b-8b7038010085.jpeg)

### Client
**iOS version:**
13.2.2
**ownCloud app version:**
1.1.1
**Device model:**
iPhoneX

**Comment by michaelstingl** [comment]
> The arrow symbol at the top right gives me the possibility to jump to a page but not the (expected) possibility to open the file in another program. The UX should also be rethought here.

Yeah, we need to harmonize the UI of the different preview module and come up with a improved icon concept. Thanks for opening!

**Comment by hosy** [comment]
But you can open the PDF in another app, from the file list and by selecting `Open In`.
You are right, that we need all file actions in the detail view too.

**Comment by michaelstingl** [comment]
> we need all file actions in the detail view too.

File actions are in the PDF detail view now:

![2020-12-23 10 07 21](https://user-images.githubusercontent.com/214010/102979949-19827600-4507-11eb-9e13-e4e0fb268b02.png) | ![2020-12-23 10 07 29](https://user-images.githubusercontent.com/214010/102980000-2901bf00-4507-11eb-8eeb-26d59f662ee9.png)
-- | --
