### ISSUE TITLE
"Open in..." does not work for several file types

### ISSUE THREAD

**Issue by dercorn** [owncloud/ios-app#568]
It works for PDFs. However, it does not work for many other file types, like .numbers, .ods, .kdbx files. The app even freezes for a few seconds before becoming responsive again.

### Steps to reproduce
1. try to open a .kdbx file with the "Open in" command from the right-hand-side three dot menu

### Expected behaviour
The "open in" menu should appear.

### Actual behaviour
The app freezes briefly. Nothing else happens.

### Client
**iOS version:**
13.2.3
**ownCloud app version:**
1.1.2 Build 144 (App: de68a46, SDK: edc8c00)
**Device model:**
iPad Pro 11 Zoll, 2018

### Client Log
See attachment. Search for "mypass.kdbx".
[ownCloud_02.12.2019__14_56_31.log.txt](https://github.com/owncloud/ios-app/files/3911970/ownCloud_02.12.2019__14_56_31.log.txt)

**Comment by hosy** [comment]
Looks like this is a problem on iPad. Share sheet is attached on the wrong anchor point. This happens in a long file list, if you choose an item which needs to be scrolled.
Just working on a fix.
On iPhone everything is ok in my opinion.

**Comment by jesmrec** [comment]
Fixed. Will be available in 1.2. Thanks for reporting @dercorn !
