### ISSUE TITLE
[Settings > Advanced] Disable Drag & Drop (maybe only if initiated from inside the app)

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#581]
Feedback from App Store review:

> **Be Careful**
> Good app, it works a LOT better than the old app. However, be very careful when scrolling as it is far too easy to drag a folder into another one by accident. Either remove the feature or give me an option to disable it, I much prefer using the ellipse menu for moving folders anyway.

Example from the [forScore](https://forscore.co/) app:

> For some, though, Drag and Drop can get in the way. Users with mobility issues and others who simply find the gestures to be uncomfortable may prefer to disable them entirely. While iOS offers no help in this regard, our latest updates include a new accessibility setting that prevents forScore from offering drag targets in most views. You can still drop things like PDF files into forScore to import them, but other interactions will be more like they were in iOS 10 and earlier.

and…

> It’s surprising that Apple hasn’t included a system-wide option to disable them, but until they do we think this will really help.

(Source: https://forscore.co/accessibility-drag-and-drop/)

Human Interface Guidelines:
https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/drag-and-drop/

Related?
https://stackoverflow.com/questions/46059925/how-to-disable-ios-11-dragging-within-the-whole-app

Maybe such settings need an "Advanced" or "Accessibility" section…

**Comment by hosy** [comment]
Add a new setting section `Advanced` and add an option for this

**Comment by jesmrec** [comment]
Done!
