### ISSUE TITLE
Mobile app no asking for lock code 

### ISSUE THREAD

**Issue by soydepr** [owncloud/ios-app#582]
### Steps to reproduce
1.  Close back ground app after setting lock code 
2.open app 
3.

### Expected behaviour
Ask for lock code 

### Actual behaviour

App opens without asking for lock code 

### Client
**iOS version:**
13.3
**ownCloud app version:**
1.20
**Device model:**

### Server configuration
**Web server:**

**Database:**

**PHP version:**

**ownCloud version:**

**Storage backend (external storage):**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by michaelstingl** [comment]
Related report:
https://central.owncloud.org/t/bug-ios-client-1-2-0-build-148/23499

**Comment by user7743** [comment]
I can confirm I am suffering this bug.

**Comment by jesmrec** [comment]
Fixed!! will be available in 1.2.1

**Comment by michaelstingl** [comment]
1.2.1 release with fix available in App Store

**Comment by soydepr** [comment]
I confirm fix worked
