### ISSUE TITLE
Login doesn't work with correct credentials

### ISSUE THREAD

**Issue by oguzserbetci** [owncloud/ios-app#583]
### Steps to reproduce
1. On fresh install, enter server URL
2. Credential details passes, no issues found.
3. Credentials that work through webdav or linux app, are not accepted.
4. No error text is shown, only the screen wiggles

### Expected behaviour
App should login.

### Actual behaviour
App doesn't login.

### Client
**iOS version:** 13.3

**ownCloud app version:** 1.2.0

**Device model:** iPad Pro

### Server configuration
**Web server:** tubcloud.tu-berlin.de

I'm not sure if I'm missing something or whether our server is just incompatible with the app.

**Comment by michaelstingl** [comment]
> I'm not sure if I'm missing something or whether our server is just incompatible with the app.

This doesn't look like a supported ownCloud instance.
