### ISSUE TITLE
Share Sheet: Create new folder, after oauth token was expired

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#588]
### Steps to reproduce
1. Remove token session in web interface
2. Save a file via share sheet
3. Select an account 
4. Create a new folder in directory picker

### Expected behaviour
Create Folder or display error message, if not possible

### Actual behaviour
Folder will not be created, because of expired session, do not get an error message. After dismissing the directory picker, the folder was created, but in directory picker it was not visible.

### Client
**iOS version:**
iOS 13.3

**ownCloud app version:**
1.2

**Device model:**
iPhone

**Comment by jesmrec** [comment]
Fixed
