### ISSUE TITLE
[FR] Autoplay media files

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#59]
Feedback from @michaelchadwick :

> I reeeaaallly want a way for the iOS client to be able to just play multiple mp3 files in a row.

(Source: [Tweet](https://twitter.com/mjchadwick/status/1002061007823368192))

I like the idea and thought about a "Autoplay" feature for all kinds of media file types:

![image](https://user-images.githubusercontent.com/214010/40887320-76c1bfc4-6747-11e8-91ed-6a91ba8a8331.png)

I used Figma.com for this quick sketch. Here you can fork it to propose own ideas:
https://www.figma.com/file/PgTb3ADoPgv4uQVuet0xYxAy

**Comment by michaelchadwick** [comment]
@michaelstingl I like this idea!

So, if you listen to song1.mp3 in a folder, if "Include Audio Files" is selected, it will just automagically play song2.mp3 (downloading it first, if needed)? Will it loop back to song1.mp3 when song2.mp3 is done?

**Comment by felixboehm** [comment]
Little research on this, as I find it annoying to start every mp3 in a golder manually.
From AVPlayer docs:

> AVPlayer is for playing a single media asset at a time. You can reuse the player instance to play additional media assets using its replaceCurrentItem(with:) method, but it manages the playback of only a single media asset at a time. The framework also provides a subclass of AVPlayer, called AVQueuePlayer, you use to create and manage the queuing of media assets played sequentially.

A queue would be nice, yet a simple solution could make use of

var actionAtItemEnd: AVPlayer.ActionAtItemEnd
The action to perform when the current player item has finished playing
https://developer.apple.com/documentation/avfoundation/avplayer/actionatitemend
can be set to advance, but I can‘t see where it takes the next item form

If the item end action can be handled it is possible to advance via
func replaceCurrentItem(with: AVPlayerItem?)
Replaces the current player item with a new player item

**Comment by michaelstingl** [comment]
@mneuwert Could you provide a first estimation?

**Comment by mneuwert** [comment]
@michaelstingl I implemented possible quick solution and pushed it on branch `feature/continue_media_playback`. I think it is quite simple and is fitting current preview architecture. Using `AVQueuePlayer` etc. would need some refactoring which I think would be needed anyway at some point for the preview sub-system.
