### ISSUE TITLE
Sort menu is missing in Directory Picker

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#590]
### Steps to reproduce
1. Move an item
2. Directory Picker is shown
3. Sort menu is not available

### Expected behaviour
Sort menu should also be available in directory picker

### Actual behaviour
Sort menu not present

### Client
**iOS version:**
13.3

**ownCloud app version:**
1.2

**Comment by jesmrec** [comment]
Done. Ready to 1.3
