### ISSUE TITLE
App stucks in blank view

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#601]
## Steps to reproduce

- Open App on iOS 13 and navigate to a folder
- Bring App to background and open Safari
- Open web interface of oC account and delete the folder which you opened in iOS app
- Go back to home screen and open oC App again
- App shows folder was deleted
- Force quit oC iOS app
- Restart oC app

## Expected behaviour

If the folder or path was deleted, show the last possible folder in this path

## Actual behaviour

App stucks in blank screen, because app tries to restore last path location, which is not available

![IMG_AC31EAA5A24C-1](https://user-images.githubusercontent.com/736109/72818552-f6eb3b80-3c6b-11ea-8cf4-d26f95d0e49b.jpeg)

**Comment by jesmrec** [comment]
I can reproduce the problem, but i do not agree the app is unusable. You see the blank screen but by killing the app and reopening again, it works. It must be fixed, for sure, but it's a bug that does not make the app unusable

**Comment by hosy** [comment]
@jesmrec for me, if I kill the app and restart it, I have the same unusable state.

**Comment by jesmrec** [comment]
i do not reproduce this after the blank. Mi environment: iPhoneX iOS13.3 fresh install. Any difference with yours?
