### ISSUE TITLE
Sharing View for log files not fully visible (iPad)

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#606]
## If you found a bug:
Sharing View for log files not fully visible on the iPad. On the iPhone it works fine.

### Steps to reproduce
- Share a log file

### Expected behaviour
Sharing view is fully visible

### Actual behaviour
Only the top of the sharing view is visible and not the complete UI can be reached

<img width="718" alt="Bildschirmfoto 2020-01-22 um 16 20 04" src="https://user-images.githubusercontent.com/736109/72906983-68da8800-3d33-11ea-8467-69cde06220e8.png">

### Client
**iOS version:**
iOS 13

**ownCloud app version:**
1.2.1

**Device model:**
iPad

**Comment by jesmrec** [comment]
Checks performed:

- [X] Open in Dialog in Log Sharing, portrait
- [X] Open in Dialog in Log Sharing, landscape
- [X] Open in Dialog in Link Sharing , portrait
- [X] Open in Dialog in Link Sharing , landscape
- [X] Open in Dialog in "Open In" , portrait
- [X] Open in Dialog in "Open In" , landscape

Tested with iPadPro v13.3
