### ISSUE TITLE
Does the new IOS app supports handling file ids as string?

### ISSUE THREAD

**Issue by labkode** [owncloud/ios-app#611]
Related ticket for Android: https://github.com/owncloud/android/issues/2787

**Comment by felix-schwarz** [comment]
`FileID`s and `ETag`s are always handled as strings, with no assumptions being made about their length or composition.

**Comment by michaelstingl** [comment]
@labkode @TheOneRing clarify such things here?
https://github.com/cernbox/smashbox/blob/master/protocol/protocol.md
