### ISSUE TITLE
[BUG] Shortcuts: Save File not working when already exists

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#622]
### Steps to reproduce
1. Download the following Shortcut: https://www.icloud.com/shortcuts/75704f3703124382962a42c0412e27dd
2. Run it minimum two times
3. Error and original file was not overwritten with the new content

### Expected behaviour
Save file gets new content

### Actual behaviour
Error and new file with conflict file name 
An unknown error occurred 

### Client
**iOS version:**
13.3.2

**ownCloud app version:**
1.3

**Comment by hosy** [comment]
![IMG_0073](https://user-images.githubusercontent.com/736109/74870284-caedd380-5359-11ea-8623-9f4180652d62.jpeg)

**Comment by jesmrec** [comment]
Already done! Shipped in 1.3.1
