### ISSUE TITLE
[BUG] Update Content in Preview, when changed

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#630]
`DisplayViewController` should automatically update it's content, when the file was changed.

## Steps to reproduce
- open a txt file, photo, PDF in detail mode
- update the content in the Web-UI or via Shortcut Save-Action
- the detail view should update the content, when the file was updated by the core

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

**Comment by jesmrec** [comment]
Done! ready to 1.3.2
