### ISSUE TITLE
[FEATURE REQUEST] Auto convert file attributes

### ISSUE THREAD

**Issue by cemizm** [owncloud/ios-app#641]
When images are automatically converted from HEIC to JPEG, the current datetime is used for the newly created files. This leads to loosing the order of the images as well as the actual date and time the images were taken. 

The file attributes of the original image should be used for the newly created files in order to fix this issue.

**Comment by michaelstingl** [comment]
@mneuwert FYI

**Comment by felix-schwarz** [comment]
Thanks for the feature request!

There may still be potential to improve transfering metadata embedded inside the file.

However, changing the date of a file on the server is not supported by the server as far as I can tell.

**Comment by mneuwert** [comment]
I verified and we do preserve EXIF metadata when converting and uploading the photos. Unfortunately at the time of conversion we are essentially creating a new file. And then when uploaded also new file is created is created on the server. As @felix-schwarz already mentioned there is no way to influence the file creation date on oC server.

However, there is another feature request #676 which suggest to stick to the legacy photo naming scheme and derive the name from the EXIF metadata. This can be done and would also allow for some meaningful sorting.

**Comment by michaelstingl** [comment]
> However, changing the date of a file on the server is not supported by the server as far as I can tell.

I thought it's supported? `X-OC-MTime` is the http header which can be used in the `PUT` request. Value is an int based unix timestamp
https://github.com/owncloud/core/issues/33502

**Comment by mneuwert** [comment]
@michaelstingl @felix-schwarz Ok... seen that SDK is using `OCItem.lastModifiedDate` internally to feed `X-OC-MTime` which is set to current timestamp if lastModifiedDate is nil. However I don't see that we can influence it on `-[OCCore importFileNamed:parentItem:...]` API level which is used in the app.

**Comment by mneuwert** [comment]
this is going to be solved with PR 678

**Comment by jesmrec** [comment]
Ready to next release
