### ISSUE TITLE
[BUG] instant upload duplicates images 

### ISSUE THREAD

**Issue by cemizm** [owncloud/ios-app#647]
It's difficult to reproduce this bug as it occurs under different circumstances. but usually the images recently viewed via the ios photos app get somehow modified (without actually being changed), so the owncloud-app uploads them again. when using icloud for image backups the images get also modified after icloud upload is done. 

By modified I mean that the last modified date gets updated without any actual changes to the image.

### Expected behaviour
Even if the app is not able to distinguish whether an image is really modified or just somehow marked as modified, the owncloud app should overwrite the existing files (only with instant upload). This would solve the two issues described above and additionally allow to edit images on the smartphone and replace the edited images on owncloud instead of duplicating them. 

### Actual behaviour
The images get duplicated (see screenshot below).

### Client
**iOS version:** 13.3.1

**ownCloud app version:** 1.3.1 Build 153 (App: 88df01d, SDK: fcfb0aa)

**Device model:** MWC72ZD/A (iPhone 11 Pro)

### Screenshot

![IMG_3648](https://user-images.githubusercontent.com/12354700/76750125-fc519780-677d-11ea-9299-8a5481d0c1f9.jpg)

**Comment by hosy** [comment]
Thank you for reporting this problem. We will check what will trigger the upload again and fix it as soon as possible.

**Comment by cemizm** [comment]
> Thank you for reporting this problem. We will check what will trigger the upload again and fix it as soon as possible.

Thank you for your quick response. Is it a viable solution to overwrite existing images during instant upload? This would only be a workaround for the described problem, but it would also allow to edit images on the smartphone. Especially the artificial depth of field of some photos is often adjusted afterwards on the smartphone.

**Comment by cemizm** [comment]
Is it intentional that the Instant Upload will query the modification date instead of the creation date? 

https://github.com/owncloud/ios-app/blob/bf7c70b61b15daa03ce26b668d64392b8a8bcf1e/ownCloud/Tasks/InstantMediaUploadTaskExtension.swift#L127-L136

To fix the issue it should query the [creationDate](https://developer.apple.com/documentation/photokit/phasset/1624776-creationdate) instead of the modificationDate.

```swift
let creationDatePredicate = NSPredicate(format: "creationDate > %@", date as NSDate)

fetchOptions.predicate = NSCompoundPredicate(andPredicateWithSubpredicates: [mediaTypesPredicate, creationDatePredicate])
```

**Comment by hosy** [comment]
@mneuwert can you have a look? I think this could solve the problem.

**Comment by mneuwert** [comment]
@hosy I think I have already suggested to use `creationDate` this change when I analysed another issue

**Comment by jesmrec** [comment]
Fixed! to be release in the following Testflight betas and in the official 11.4

**Comment by cemizm** [comment]
thx
