### ISSUE TITLE
[BUG] Shortcuts Save File Intent Completion

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#651]
## If you found a bug:

In file `SaveFileIntentHandler.swift` the completion handler for the shortcut task needs to be moved to `placeholderCompletionHandler` instead of `resultHandler` for calling functions `reportLocalModification` and `importFileNamed`. Because the `resultHandler` is called, when the file was uploaded to the server. If the device is in flight mode or on bad network connections, this handler may not called.

### Steps to reproduce
1. Enable device flight mode
2. Run `Save File` action in Shortcuts
3. Action will be killed by Shortcuts app, because operation time was to long

### Expected behaviour
Finish Shortcut action, immediately when file was imported into app

### Actual behaviour
If file was not uploaded to the server, the action will fail.

### Note 
Fix this in `EditDocumentViewController.swift` too!

### Client
**iOS version:**
13.3

**ownCloud app version:**
1.3.1

**Comment by jesmrec** [comment]
Done
