### ISSUE TITLE
[FEATURE] Implement UIPointerInteraction for iPad

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#655]
With iOS 13.4 the iPad can connect with trackpad or a mouse.

Apple released new API to implement better support for this devices.
With UIPointerInteraction it is possible to enable support for effects on a view or to customize the pointer's appearance within a region of an app.

Most elements are working fine out of the box with our app, but there are some elements, which needs a custom implementation:

### Add effect to buttons
- More button
- (Multiple) select button
- Favorites button
- Passcode buttons
- Download button for item in detail view

### Add row hover for the following elements:
- File list
- More menu
- Account list
- Settings

### Add hover effect to cells
- Photo selection
- PDF thumbnail view

## QA

Test plan:

https://github.com/owncloud/QA/blob/master/Mobile/iOS-app/Version%201.3.2/Trackpad%20%26%20Mouse%20support%20iPad.md

**Comment by jesmrec** [comment]
After testing this, everything is working fine. But i want to comment with you some details:

- Swipe is not posible. Is this a restriction? 

- Same for scroll up/down, f. ex., in the file list

- Hover effect on Settings happens only in the rows with an expand arrow. The options with switch does not show the effect. Is it expected?

**Comment by jesmrec** [comment]
Done, and ready to 1.3.2
