### ISSUE TITLE
[FEATURE REQUEST] Better LOG name

### ISSUE THREAD

**Issue by cdamken** [owncloud/ios-app#657]
When trying to provide log files I go to the screen and I see this:

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/7264495/77557203-19bdea00-6e7f-11ea-937e-73e78116c9b4.png">

I try to upload more than one to different servers and its always overwrite.

It would be great to have the date and time in the log file to have a difference.

**Comment by michaelstingl** [comment]
> It would be great to have the date and time in the log file to have a difference.

Thanks a lot for your valuable feedback! This should be improved.

> and its always overwrite.

Sounds like a bug in the legacy iOS app?

**Comment by cdamken** [comment]
I saw the problem, the old iOS app had an error and because of that didn't upload the other logs.

**Comment by michaelstingl** [comment]
> It would be great to have the date and time in the log file to have a difference.

Feature request for timestamp in the log filename is valid, and important for support team I'd say.

**Comment by cdamken** [comment]
the files were uploaded with the timestamp now:
<img width="401" alt="Screenshot 2020-03-25 at 10 22 29" src="https://user-images.githubusercontent.com/7264495/77560112-9ef6ce00-6e82-11ea-8ad4-1582a2dd423e.png">

Probably would be good to upload all of them together instead each one.

**Comment by michaelstingl** [comment]
Okay, good. Thanks for the feedback!

**Comment by michaelstingl** [comment]
> Probably would be good to upload all of them together instead each one.

Yeah, this can be improved maybe…
