### ISSUE TITLE
[FEATURE REQUEST] Support changing the format of uploaded image file names 

### ISSUE THREAD

**Issue by hamiller** [owncloud/ios-app#676]
**Is your feature request related to a problem? Please describe.**
Please allow the definition of the file name for automatically uploaded (and from HEIFF converted) image file names.
Would be best if the EXIF information could be used for that.

**Describe the solution you'd like**
I'd like to have a text field in the configuration dialog to define the naming format of uploaded images based on their EXIF data.

**Describe alternatives you've considered**
Instead of a free input dialog, a checkbox could be used to decide if the new or the old file name format should be used:
Old:  "Photo-YEAR-MM-DD-HH-MM-S.jpg" (used by the legacy app)
New: "IMG_xxxx.jpg"

**Additional context**
I'd like to have all image file names in the style of "Photo-YEAR-MM-DD-HH-MM-S.jpg" - as it was in the legacy owncloud version.
That's because it's much easier to work with the upload folder on a file-name basis. Currently the upload folder contains files which where uploaded by the old legacy software as well as uploaded with this new one - causing bad sorting of all images.
Constantly renaming all images to the "old format" manually is not an option.

**Comment by jesmrec** [comment]
This will be available in the next release.
