### ISSUE TITLE
[FEATURE REQUEST] Display EXIF image metadata in iOS app

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#679]
**Is your feature request related to a problem? Please describe.**
Would be useful to be able to access and view EXIF metadata in the image viewer. 

**Describe the solution you'd like**
To get the metadata we just need to access `CGImage` properties dictionary in `ImageDisplayViewController.downsamleImage() `method which already creates `CGImageSource` instance from which we could query the meta-data by calling `CGImageSourceCopyPropertiesAtIndex(imageSource, 0, nil) `which returns nested dictionary with several sections which we could feed into some nice UI.

**Additional context**
Reference of property keys:
https://developer.apple.com/documentation/imageio/cgimageproperties

EXIF dictionary keys:
https://developer.apple.com/documentation/imageio/cgimageproperties/exif_dictionary_keys

Example of the dictionary returned by `CGImageSourceCopyPropertiesAtIndex()`:
{
    ColorModel = RGB;
    DPIHeight = 72;
    DPIWidth = 72;
    Depth = 8;
    Orientation = 6;
    PixelHeight = 3024;
    PixelWidth = 4032;
    "{Exif}" =     {
        ApertureValue = "1.69599381283836";
        BrightnessValue = "0.9302808772604848";
        ComponentsConfiguration =         (
            1,
            2,
            3,
            0
        );
        DateTimeDigitized = "2020:04:20 20:50:49";
        DateTimeOriginal = "2020:04:20 20:50:49";
        ExifVersion =         (
            2,
            3,
            1
        );
        ExposureBiasValue = 0;
        ExposureMode = 0;
        ExposureProgram = 2;
        ExposureTime = "0.01694915254237288";
        FNumber = "1.8";
        Flash = 16;
        FlashPixVersion =         (
            1,
            0
        );
        FocalLenIn35mmFilm = 26;
        FocalLength = "4.25";
        ISOSpeedRatings =         (
            400
        );
        LensMake = Apple;
        LensModel = "iPhone 11 Pro back triple camera 4.25mm f/1.8";
        LensSpecification =         (
            "1.54",
            6,
            "1.8",
            "2.4"
        );
        MeteringMode = 5;
        PixelXDimension = 4032;
        PixelYDimension = 3024;
        SceneCaptureType = 0;
        SceneType = 1;
        SensingMethod = 2;
        ShutterSpeedValue = "5.878660940580119";
        SubjectArea =         (
            2002,
            1505,
            2213,
            1324
        );
        SubsecTimeDigitized = 513;
        SubsecTimeOriginal = 513;
        WhiteBalance = 0;
    };
    "{GPS}" =     {
        Altitude = "306.0366799905948";
        AltitudeRef = 0;
        DestBearing = "228.1379547014413";
        DestBearingRef = T;
        HPositioningError = "38.94124659400545";
        ImgDirection = "228.1379547014413";
        ImgDirectionRef = T;
        Latitude = "49.45773666666667";
        LatitudeRef = N;
        Longitude = "10.9702";
        LongitudeRef = E;
        Speed = "0.2461407630551031";
        SpeedRef = K;
    };
    "{JFIF}" =     {
        DensityUnit = 0;
        JFIFVersion =         (
            1,
            0,
            1
        );
        XDensity = 72;
        YDensity = 72;
    };
    "{MakerApple}" =     {
        1 = 11;
        12 =         (
            "32.59375",
            "12.43359"
        );
        13 = 14;
        14 = 0;
        16 = 1;
        17 = "38390B28-5A6A-4038-A094-99B148CA7FFC";
        2 = <...>;
        20 = 12;
        23 = 38805504;
        25 = 8192;
        26 = q750n;
        3 =         {
            epoch = 0;
            flags = 1;
            timescale = 1000000000;
            value = 3467362277792083;
        };
        31 = 0;
        32 = "C6FB39E3-B387-471C-8226-6424D16BB95C";
        33 = "0.7844365";
        35 =         (
            25,
            268435512
        );
        37 = 5262;
        38 = 3;
        39 = "31.22804";
        4 = 0;
        43 = "109D5647-807B-4D9B-A8EF-059FA27B4674";
        5 = 172;
        6 = 167;
        7 = 1;
        8 =         (
            "0.04496446",
            "-0.434641",
            "-0.9062546"
        );
    };
    "{TIFF}" =     {
        DateTime = "2020:04:20 20:50:49";
        Make = Apple;
        Model = "iPhone 11 Pro";
        Orientation = 6;
        ResolutionUnit = 2;
        Software = "13.3.1";
        TileLength = 512;
        TileWidth = 512;
        XResolution = 72;
        YResolution = 72;
    };
}

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by mneuwert** [comment]
E.g. this is how it is looking in DropBox:

![IMG_4258](https://user-images.githubusercontent.com/228537/80588875-729e1680-8a19-11ea-8ff2-e189a5431de6.png)
![IMG_4257](https://user-images.githubusercontent.com/228537/80588892-7893f780-8a19-11ea-8cd5-5299e5269ab7.png)

**Comment by hosy** [comment]
Yes, this would be great and should be done with less effort by using our `StaticTableViewController` for showing the informations .  You could also show the location. 
@mneuwert  can you estimate it?

**Comment by mneuwert** [comment]
@hosy Yes, I think even you can use `MKMapView` to show location and such fancy stuff. I would say it is an M size T-shirt;-)

**Comment by mneuwert** [comment]
@hosy one thing which may make it an L is when we want to show all possible EXIF tags supported by iOS with values actually resolved to human readable text.. E.g. from the dictionary I posted as an example:

ExposureMode = 0;
ExposureProgram = 2;
WhiteBalance = 0;
MeteringMode = 5;
SensingMethod = 2;

vs.

ExposureMode = Auto exposure
ExposureProgram = Normal Program
WhiteBalance = Auto white balance
MeteringMode = Pattern
SensingMethod = One-chip color area sensor

But may be we can concentrate on more interesting and important EXIF tags at first..

**Comment by jesmrec** [comment]
Ready to 11.4.1
