### ISSUE TITLE
Swiping to next audio file doesn't stop playing previous file (2 files playing simultaneously)

### ISSUE THREAD

**Issue by yivo** [owncloud/ios-app#683]
### Steps to reproduce
1. Open audio file (file A).
2. Wait until it starts playing.
3. Swipe to next audio file (file B).
4. Wait until it starts playing.

### Expected behaviour
File A should stop playing. File B should start playing.

### Actual behaviour
File A playing, file B playing (2 files playing simultaneously).

### Video

https://youtu.be/YyyVSmwpMQc

### Client
**iOS version:** 13.3

**ownCloud app version:** 1.3.2 build 158

**Device model:** iPhone 8 Plus

**Comment by hosy** [comment]
Hi @yivo thank you for reporting this bug and for uploading a demo video. We will fix this soon! Thank you for using ownCloud!

**Comment by jesmrec** [comment]
Fixed! will be available in the next release. Thanks for reporting!
