### ISSUE TITLE
[FEATURE REQUEST] Allow uploading of RAW images

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#685]
**Is your feature request related to a problem? Please describe.**
There are apps on iOS allowing shooting RAW images (for example: _Halide_). Also, Apple provides developer documentation on how to capture and store such images in the photo library. So, when raw photo is shot typically an Asset with two resources is created: compressed image (_JPEG, HEIF_) and RAW image stored as `PHAssetResourceType.alternatePhoto`. As of now, we would only upload compressed image not giving the user an ability to upload the highest quality ones.

**Describe the solution you'd like**
We could have an option in settings, sth. like "Prefer RAW images" in the upload section.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
Ready to go in 11.4.1
