### ISSUE TITLE
[FEATURE REQUEST] Clarify uploading original assets vs edited assets

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#688]
**Is your feature request related to a problem? Please describe.**
iOS Library supports non-destructive editing of media assets. Thereby alongside with an original asset e.g. stored in _HEIC_ format, adjustment data is stored (as _PLIST_) and cached latest output stored as _JPEG_ image (which is basically original image data with operations described in Adjustments.plist applied).

**Describe the solution you'd like**
I think we need at least provide options to the user allowing him to choose what to upload: original, edited image or both.

**Describe alternatives you've considered**
Right now we just upload an original without providing any options

**Additional context**
Here is an example of Array of `PHAssetResouce` objects returned by `PHAssetResource.assetResources(for asset:PHAsset)`:

_[
{ type: photo, uni: public.heic, filename: IMG_3537.HEIC, isCurrent: NO},
{ type: adjustment, uni: com.apple.property-list, filename: Adjustments.plist, isCurrent: YES}
{ type: photo, uni: public.jpeg, filename: FullSizeRender.jpg, isCurrent: YES},
]_

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
Ready to go in 11.4.1
