### ISSUE TITLE
[FEATURE REQUEST] Support specifying Branding.plist parameters via MDM

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/ios-app#697]
Allow specifying `Branding.plist` parameters via MDM, as suggested in https://github.com/owncloud/enterprise/issues/4009

**Comment by felix-schwarz** [comment]
This feature is implemented in #797.

**Comment by jesmrec** [comment]
Approved on my side (cookie handling)

Added test plan to the PR #797

**Comment by felix-schwarz** [comment]
> This feature is implemented in #797.

Sorry, misread my own issue. 🤦‍♂️

#797 allows specifying MDM parameters via Branding.plist, not the other way round. So this issue remains unsolved.

**Comment by felix-schwarz** [comment]
Addressed in #873. More details there.
