### ISSUE TITLE
[BUG] More (3 dots) icon is not consistently shown in all document previews.

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#698]
### If you found a bug:
In some document previews more icon is shown in the top right corner allowing to take some actions on the current item (share, delete etc). E.g. it is available in image viewer but not in PDF viewer.

### Steps to reproduce
1. Open bookmark document
2. Open PDF document (we shall also check other document types)
### Expected behaviour
3 dots icon shall be in top right corner

### Actual behaviour
Not possible to share PDF for instance due to missing button item, so you have to go back to the file list which is annoying

### Client
**iOS version: 13.4**

**ownCloud app version: 1.3 **

**Comment by jesmrec** [comment]
Done! ready to 11.4
