### ISSUE TITLE
New app version does not respond to HTTP 401

### ISSUE THREAD

**Issue by apach3guy** [owncloud/ios-app#699]
My ownCloud installation is protected by Basic Auth. Both the current desktop client as well as the previous mobile app had no problems connecting. However, the latest version of the iOS app does not appear to respond to HTTP 401 with credentials.

**Comment by michaelstingl** [comment]
What is the ownCloud server version you are using? ==> oC 10+ is required

Do you use 2FA / TOTP login? ==> OAuth 2.0 app needs to be installed on the oC server.

**Comment by michaelstingl** [comment]
> My ownCloud installation is protected by Basic Auth.

What does this mean?

**Comment by apach3guy** [comment]
I’m using ownCloud 10.3.2 but I am confident the error has nothing to do with the server version. 

Basic Authentication is an authentication protocol that is initiated when the server sends an HTTP 401 header to the client. Please see the Apache documentation for more information:
https://httpd.apache.org/docs/2.4/howto/auth.html

**Comment by apach3guy** [comment]
Solved. Solution was to add a Basic Auth exception for status.php. I remember coding this into my Apache config a while back but somehow it must have been deleted.
