### ISSUE TITLE
Multi account in iOS 11 Files app

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#7]
It seems Onedrive (and maybe Dropbox) found a way to have multiple entries in the Files app.

| ![2018-03-12_22_49_19](https://user-images.githubusercontent.com/214010/37311730-bfcaa81a-2648-11e8-94d3-0a5918ca3dab.png) | ![2018-03-12_22_48_40](https://user-images.githubusercontent.com/214010/37311731-bfed5fa4-2648-11e8-8459-738f4c6da0ee.png) | ![2018-03-12 22 56 54](https://user-images.githubusercontent.com/214010/37311729-bfad2b5a-2648-11e8-8f4a-c6d99fd8782c.png) |
| -- | -- | -- |

**Comment by pablocarmu** [comment]
After some little research in the Apple's documentation about the file provider I found this:

[NSFileProviderDomain](https://developer.apple.com/documentation/fileprovider/nsfileproviderdomain)

The Overview says:

> You can use domains to partition a file provider's content. When you use domains, a single file provider can act as if multiple file providers were installed, and users can dynamically switch from one domain to another. You can use domains to represent different accounts or locations.

With the SDK support for multiple bookmarks, we can assume that each bookmark should have a domain.


I performed a little test and after adding these lines to create and add a new ```NSFileProviderDomain``` using the Bookmark name, and a dummy path when the bookmar has been created successfully:

```Swift

let domain =
	NSFileProviderDomain(identifier: NSFileProviderDomainIdentifier.init(rawValue: self.bookmarkToAdd!.name),
                         displayName: self.bookmarkToAdd!.name,
                         pathRelativeToDocumentStorage: "/")

	NSFileProviderManager.add(domain, completionHandler: { (error) in

		print("Error = \(error?.localizedDescription)")

	})
```

I was able to get this: 
![serverlist](https://user-images.githubusercontent.com/8929738/39914860-8dfd23a2-5506-11e8-8c43-8de233b2f22c.png)
![filesapp](https://user-images.githubusercontent.com/8929738/39914861-8e1f7254-5506-11e8-87b8-e2f6005eb9c7.png)

**Comment by michaelstingl** [comment]
@pablocarmu awesome, this sounds promising!

**Comment by michaelstingl** [comment]
II think this is solved
