### ISSUE TITLE
[FEATURE REQUEST] Prevent sleeping screen, in detail view

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#704]
**Is your feature request related to a problem? Please describe.**
When a file is open in detail view it often makes sense to prevent the screen to go in sleep mode.
Example:
I have a PDF file open, and I want to show a customer the file but the screen should not go in sleep mode, because I cannot touch the screen.

**Describe the solution you'd like**
Option in settings or always on, when file is in detail view
### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by michaelstingl** [comment]
> Option in settings

Yes, preferred 👍

**Comment by jesmrec** [comment]
Done.
