### ISSUE TITLE
[BUG] account for uploading media files can only be selected once

### ISSUE THREAD

**Issue by mmattel** [owncloud/ios-app#711]
### Steps to reproduce
1. have at least two accounts where you can select from
2. goto the app settings to the media upload section and enable photos
3. select an account and a target folder
4. exit the settings
5. disable media upload for photos and reenable it
6. you cant change the account/folder anymore, the slider just enables the functionality but no account/target settings are shown up.

(addon: after selecting the target upload for photos, you cant do that for videos)

### Expected behavior
After deselecting and reenable photo upload, the account and target should be re-definable.
Account and folder should be selectable independent for photos and videos.

### Actual behavior
Account and target cant be changed after first defining the setting.
Photo and video upload account/target cant be independently set up.

I cant do further tests because the account/target settings are "locked" and not shown anymore.

### Client
**iOS version:** 13.5

**ownCloud app version:** 1.3.2

**Device model:** iPhone SE

### Server configuration
**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.3

**ownCloud version:** 10.4.1

**Storage backend (external storage):** local, smb, gd

@michaelstingl @hosy

**Comment by hosy** [comment]
Thank you for reporting!

**Comment by jesmrec** [comment]
This is fixed and will be released in 11.4. Please, feel free to reopen if it is not fixes for you once the release is out. Thanks for reporting!
