### ISSUE TITLE
[FEATURE REQUEST] Adopt iOS13 multiple-selection gesture

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#725]
**Is your feature request related to a problem? Please describe.**
There is a new gesture introduced in iOS13: tap and pan with 2 fingers to select multiple items. This has been made an opt-in behaviour.

**Describe the solution you'd like**
For screens using `UITableView` / `UICollectionView` and allowing multiple-selection we just have to adopt 2x new delegate methods to take advantage of the new behaviour in iOS13.

**Describe alternatives you've considered**

**Additional context**
- See https://developer.apple.com/videos/play/wwdc2019/224/ video around 33m10s for reference
- Try to use new gesture in a Files or Notes app to get a feeling for it.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
Done! ready to 11.4
