### ISSUE TITLE
[FEATURE REQUEST] iOS13 context menu improvements

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#727]
**Is your feature request related to a problem? Please describe.**
- iOS13 uses pop and peek gesture to trigger `UIContextMenuInteraction`.
- So you tap and hold item and then the view is blurred and you see preview of the item and the hierarchical context menu. Compare to the screenshot from files app.
- We use this API.. BUT only on iPad and there we just display single menu item "Open in new Window"

**Describe the solution you'd like**
Using the new API would allow to get rid of the sliding card view and eventually more button and make the user experience more consistent and use of the app more efficient IMHO.

**Additional context**
Context menu in the Files app on iPhone

![IMG_925B6817168D-1](https://user-images.githubusercontent.com/228537/84029835-55068a00-a993-11ea-8fdf-4a7a3728f410.jpeg)

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by felix-schwarz** [comment]
Two quick thoughts:
- replacing the card view would require that the content and composition of the context menu can be changed dynamically (f.ex. sharing info in the current "more card" is loaded asynchronously right now - and the card then updated with the results)
- effect on user experience when long press is used for both starting drag & drop and opening the context menu?

**Comment by hosy** [comment]
This is already implemented here:

https://github.com/owncloud/ios-app/issues/717

**Comment by hosy** [comment]
I would keep both implementations. Card View and contextual menu. Card menu has additional informations and contextual menu is maybe only for pro users to discover.

**Comment by mneuwert** [comment]
@hosy But I think it only implemented for the iPad.. but could also be extended to iPhones

**Comment by mneuwert** [comment]
@felix-schwarz Files app dismisses the contextual menu, when you start moving the item thereby initiating drag and drop session.

**Comment by hosy** [comment]
@mneuwert  should be already available on iPhone in `milestone/1.4`

![image](https://user-images.githubusercontent.com/736109/84047709-d4a05300-a9ab-11ea-830e-79a20cd96e7e.png)

**Comment by mneuwert** [comment]
@hosy cool, missed this one. So, it was also merged last week...
