### ISSUE TITLE
[BUG] Markup selected from the file list doesn't work

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#729]
### Steps to reproduce
1. Make sure "document markup" feature is available (which is IAP product)
2. Open a folder containing .jpg or .pdf file
3. For this file tap "..." (more) icon and select Markup 

### Expected behavior
Document shall be opened in editing mode.

### Actual behavior
Normal preview is opened.

### Client
**iOS version: 13.5**

**ownCloud app version: 11.4 Branch Latest**

**Device model: iPhone 11 Pro**

**Comment by hosy** [comment]
This is the expected behaviour at the moment.  Unfortunately it does not work to open a file directly in edit mode. Hopefully Apple will change this in iOS 14.

**Comment by jesmrec** [comment]
Done! ready to 11.4
