### ISSUE TITLE
[BUG] Bad message after removing a file from preview mode

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#732]
Steps:

1. Open a PDF file in preview mode
2. Open "..."
3. Delete

Current: file is deleted, but it is still displayed. Tapping on back button, appears "Folder removed"
Expected: file deleted. options:
- Move to file list, so the file can not be displayed anymore
- File stays on screen, but after tapping back folder is correctly displayed with its content.

With images, the "Folder removed" screen appears during a while, and then, the list of files is correctly loaded.

![Jun-17-2020 10-01-36](https://user-images.githubusercontent.com/14894746/84872040-a0025a80-b081-11ea-87f7-70a81304157d.gif)

Iphone XR v13.4

**Comment by felix-schwarz** [comment]
This problem should be solved with the latest `milestone/1.4` commit now.

**Comment by jesmrec** [comment]
Fixed.
