### ISSUE TITLE
[FEATURE REQUEST] Some features are missing in collections accessible from Quick-Access

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#733]
**Is your feature request related to a problem? Please describe.**
When you select one of the collections in Quick Access tab (e.g. Favourites):
- You'll see familiar list of items BUT, following important features for instance are missing:
 - Multiple selection
 - Tap and hold to access actions menu

The reason for this problem is apparently that those features are implemented in `ClientQueryViewController` class and not in `FileListTableViewController` which `LibrarySharesTableViewController` is subclassing.

**Describe the solution you'd like**
I guess relevant functionality can be just moved up to `FileListTableViewController` in the class hierarchy.

**Comment by hosy** [comment]
Should be done in release 11.4 because the features you mentioned were implemented in this release.

**Comment by hosy** [comment]
@mneuwert good catch!
