### ISSUE TITLE
[BUG] Downloading of jpgs broken

### ISSUE THREAD

**Issue by spr2** [owncloud/ios-app#739]
Regression: In Client 11.4 Build 159 (App: 0ebefc4, SDK: 9b2527e) clicking on a jpg does not display the image full screen.

 
### Steps to reproduce
1. click on any jpg file that is not present on device
2.
3.

### Expected behavior
The jpg  image should be downloaded and displayed full screen. With png this behaviour works, also in current released client.

### Actual behavior
1. the thumbnail loading with the download progress bar (as expected)
2. the download seems to finish, but the thumbnail stays, so no fullscreen view of the downloaded jpg

### Client
**iOS version:**
13.5.1
**ownCloud app version:**
Build 159 (App: 0ebefc4, SDK: 9b2527e)
#
**Device model:**
ipad pro 12"

### Server configuration
**Web server:**
Apache

**Database:**

**PHP version:**

**ownCloud version:**
10.3.2
**Storage backend (external storage):**

**Comment by hosy** [comment]
@spr2 I cannot reproduce this bug with app commit https://github.com/owncloud/ios-app/commit/4289401e3c2ea78e5fd3bbe0ae9a0c7b9e8d0471 
and sdk commit https://github.com/owncloud/ios-sdk/commit/0b182890d954194ed0730b78cbf4fce08ec11310

Please can you attach log files if the problem still exists.

**Comment by spr2** [comment]
@hosy I did check the logs, however there is content that I do not want to post without anonymizing in the logs

It seems there is a 404 in the propfind in the app version mentionend, shared by @michaelstingl for testing. However I verify in the web interface that the file is there and downloads correctly.
The same file downloads perfectly with the app store version of ios oc client as well.

20:27:05 GMT</d:getlastmodified><d:getetag>&quot;5b89aeefd1936&quot;</d:getetag><oc:id>0171378652864420e9ca4</oc:id><oc:size>10002887</oc:size><oc:permissions>RDNVCK</oc:permissions><oc:favorite>0</oc:favorite><oc:share-types/><oc:owner-id>xxx</oc:owner-id><oc:owner-display-name>xxx</oc:owner-display-name></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/><d:getcontenttype/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/remote.php/dav/files/xxx/yyy.JPG</d:href><d:propstat><d:prop><d:resourcetype/><d:getlastmodified>Thu, 19 Mar 2009 23:19:16 GMT</d:getlastmodified><d:getcontentlength>1862279</d:getcontentlength><d:getcontenttype>image/jpeg</d:getcontenttype><d:getetag>&quot;057856f950d291fe364efff8e9a170e8&quot;</d:getetag><oc:id>0177536752864420e9ca4</oc:id><oc:size>1862279</oc:size><oc:permissions>RDNVW</oc:permissions><oc:favorite>0</oc:favorite><oc:share-types/><oc:owner-id>xxx</oc:owner-id><oc:owner-display-name>xxx</oc:owner-display-name></d:prop><d:status>HTTP/1.1 200 

I exchanged some sensitive data in the log with xxx & yyy manually, as I did not find an option to prepare logs for posting anonymized in the app.

**Comment by hosy** [comment]
@felix-schwarz please can you have a look to the log above?

**Comment by spr2** [comment]
issue is gone on build ownCloud Release version 11.4 build 160
(app: 84d0cb8e, sdk: 67cc87c)

I think this can be closed! (btw copying the hashes already implemented is awesome!)
