### ISSUE TITLE
[FEATURE REQUEST] Make Version Info in App Settings copyable

### ISSUE THREAD

**Issue by spr2** [owncloud/ios-app#740]
The version info (Build Number, Hashes) in the app settings should be selectable so they can be copied into an issue instead of having to type out git hashes etc.

**Comment by michaelstingl** [comment]
@hosy bring PR https://github.com/owncloud/ios-app/pull/741 to 11.4? Shouldn’t need big testing efforts?

**Comment by hosy** [comment]
@michaelstingl yes, QA does need minimal efforts. I would move it to 11.4.

**Comment by jesmrec** [comment]
Done! Ready to go in 11.4.
