### ISSUE TITLE
[FEATURE REQUEST] Enable crash logging in FileProvider

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#756]
**Is your feature request related to a problem? Please describe.**
We added PLCrashReporter which can add crash reports to the log when the main app's process has crashed. We would like to do the same in the FileProvider extension.

**Describe the solution you'd like**
- Link FileProvider extension again PLCrashReporter library and initialise it at startup.
### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
Done! ready to 11.4
