### ISSUE TITLE
Introductory Blog post topics (WIP)

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/ios-app#78]
Ideas for a blog post introducing the new ios-app and ios-sdk to the world:

## Intro
- @lefherz will you take care?

## Adopting new OS features
- File Provider / Files App support
- Themeable UI built with Auto Layout and TVG (themable SVG)
- Background Session transfers
- drag & drop (planned)
- flexible layout that supports split screen etc
- offline support (work in progress)

## Focus on security and performance
- powerful new certificate infrastructure
   - detailed information on certificates before transmitting data
   - in the future: certificate management in settings
- warning on redirects to safeguard against Man-In-The-Middle attacks
- concurrent, non-blocking design
- OAuth2 support using SFAuthenticationSession
- support for password managers
- support for passcode or biometric (Touch ID, Face ID) lock, blurring in app switcher
- user feedback let the user decide about, things like redirections, certificates

more…
https://github.com/owncloud/ios-app/blob/master/doc/SECURITY.md

## A modern foundation
- new, highly modular SDK (more: https://github.com/owncloud/ios-sdk/blob/master/README.md)
   - no external library dependencies
   - MDM support built-in
   - powerful logging designed to respect privacy
   - extendable authentication infrastructure
   - APIs for everyone
      - low-level OCConnection interface provides direct access to servers
      - high-level OCCore interface makes server interactions and implementing clients really simple
   - licensed under GPLv3, but third-party developers are welcome to reach out if they need it under a different license
   - high automated test coverage

## Call to action ==> Beta Testing Now!!
- Link to blog post or landing page where we explain how/what to test and where to provide feedback
- link to onboarding site: https://boarding.owncloud.com/ (@ChrisEdS need to check https://github.com/owncloud/ios-app/issues/97 first)

.. to be continued .. (WIP)

**Comment by pablocarmu** [comment]
I think the Theme support and TVG deserve its own tech blog post!. These things are super cool and I'm sure people would like to read about it.

We can add to the blog post that the app will add support for password managers. Also, could be a great idea to make a paragraph talking about all the actions that we're going let the user decide about, things like redirections, certificates, that if one item is modified in the server and you have changed it locally you are going to be able to choose and other things that are written [here](https://github.com/owncloud/ios-sdk/blob/master/doc/SYNC.md)

**Comment by lefherz** [comment]
When do we want this? If I am to write this, I need to know the deadline a bit in advance, so I can prioritize. Thanks :)

**Comment by michaelstingl** [comment]
Changes in top post:

- order changed after feedback from @lefherz 
- added password managers to security section
- added user feedback (redirections, certificates) to security section
- added drag & drop, layout and offline to OS feature sections (not sure about the last)
- added links to SDK readme and app security
