### ISSUE TITLE
[BUG] Markup a document does not start in edit mode

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#783]
With iOS app version 11.4 we introduced markup documents directly in edit mode. Unfortunately this is not working on iOS 14. Maybe this is also not working on iOS 13, but cannot check on a real device.

### Steps to reproduce
1. Show more option on a PDF or image file
2. Tap on "Markup"
3. Document opens in new window, but edit mode is not active
4. Needs a tap on Edit to active edit mode

### Expected behavior
Edit mode should be automatically enabled, after the document appears.

### Client
**iOS version:**
iOS 14 beta

**ownCloud app version:**
11.4

**Device model:**
iPhone, iPad

**Comment by michaelstingl** [comment]
==> part of bigger iOS 14 issue

- Problems with Xcode 12 build

@hosy quick fix possible?

**Comment by jesmrec** [comment]
Done. Ready to 11.4.1
