### ISSUE TITLE
[BUG] Settings: Photo / Video Upload Path not visible

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#784]
Enabling a photo or video upload does not show the row for selecting the upload path.

### Steps to reproduce
1. Open Settings
2. Select Media Upload
3. Enable Photo or Video Upload 

### Expected behavior
Row for selecting the upload path does appear immediately

### Actual behavior
The row for selecting the upload path does not appear. The user needs to push back and select Media Upload again until it appears.

### Client
**iOS version:**
iOS 14

**ownCloud app version:**
11.4

**Comment by mneuwert** [comment]
Can't reproduce with latest iOS 14 beta (Xcode 12b4) in simulator.. Requesting photo library permissions has been one of the fundamental changes in iOS14, so may be it was broken in earlier betas..

**Comment by jesmrec** [comment]
By building an archived ipa built with XCode11 and installing in iPhone with iOS14 (beta8), i can not reproduce it either. When the target folder is selected, it takes a little to show the path, but it is finally displayed.

**Comment by jesmrec** [comment]
Done. Ready to 11.4.1
