### ISSUE TITLE
[BUG] Opening Folder in Files.app - Response Time

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#787]
Opening a folder in Files.app for a larger oC account needs to much time. We should think about caching the files or showing a progress indicator to the user, if possible. But a better approach would be to decrease the opening time for folder browsing.
Is there a way to improve this @felix-schwarz ?

### Steps to reproduce
1. Add a large oC account (maybe from cloud.damken)
2. Open Files.app, select the oC account
3. Browse in the folder structure

### Expected behavior
Faster response

### Actual behavior
Large accounts have a long response time

### Client
**ownCloud app version:**
11.4

**Comment by felix-schwarz** [comment]
As far as I can see, SQLite and/or file locking seems to be a possible bottleneck here.

I added the size of the database files and a `Vacuum` diagnostic action in https://github.com/owncloud/ios-app/pull/778/commits/47d0dd8724458058930703e285a7c35914540c17 (in 11.4.1).

Here are the statistics of the account I use for testing this:
![Screen Shot 2020-08-31 at 22 56 05](https://user-images.githubusercontent.com/639669/91768220-98147a00-ebdd-11ea-923b-c259cb0c349e.png)

**Comment by hosy** [comment]
@felix-schwarz Possibly this is related to these issue: 
- Open a large account in the app
- Open a file in the detail view
- click the back button at the top

Result:
The previous view is displayed with a delay and not immediately as expected

**Comment by jesmrec** [comment]
Ready to 11.6
