### ISSUE TITLE
Upload via File Provider

### ISSUE THREAD

**Issue by sakthi-d** [owncloud/ios-app#794]
Do we support uploading/importing via Files App?
I would be really helpful to get the way of uploading.

Thanks in advance

**Comment by michaelstingl** [comment]
> To upload files or any time from your device to your ownCloud server, click Upload file. You will then be able to select or browse through files from any app that exposes data to the iOS files app.

Check “Upload” section in the docs:
https://doc.owncloud.com/ios-app/ios_files.html#folder-actions
