### ISSUE TITLE
[BUG] Create a public link over a federated share

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#803]
### Steps to reproduce
1. Create a federated share over a folder which contain files
2. Accept the share in the recipient user
3. In the recipient, open the folder and create a public link over a file inside

### Expected behavior
Link is correctly created

### Actual behavior
Nothing happens

### Client
**iOS version:** 13.7

**ownCloud app version:** 11.4

**Device model:** iPhoneXR

**Comment by felix-schwarz** [comment]
Fixed by #804.
