### ISSUE TITLE
[BUG] Show Notification for Expired Access Token in FileProvider

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#808]
## If you found a bug:

 If the token of an account is expired, open the Files.app and try to download a file. This will cause in `Waiting…` for this item, without a notification. Switching to the app will show the alert, that the token was expired and needs a re-authentication.

### Steps to reproduce
1. Remove access token in ownCloud server
2. Open Files.app and try to open a file inside this account
3. Item is in `Waiting…` state
4. Open ownCloud.app
5. App will show an alert

### Expected behavior
Show a notification from the FileProvider inside the Files.app with the same content from the main app alert.

### Actual behavior
Items stays in `Waiting…` state with no feedback to the user.

### Screenshots

| ![IMG_5002](https://user-images.githubusercontent.com/736109/94779318-0a3bd280-03c7-11eb-9317-a1af5c370bf1.PNG) | ![IMG_5001](https://user-images.githubusercontent.com/736109/94779330-0dcf5980-03c7-11eb-8207-a0bb4ba929a6.PNG) |
|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|

### Client
**ownCloud app version:**
11.4.1

**Comment by jesmrec** [comment]
Done.
