### ISSUE TITLE
[BUG] PDF Files will not be proper saved in Share Sheet (from Mail.app)

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#816]
## If you found a bug:

If I try to save an attachment from Mail.app, the file was uploaded with invalid content.

### Steps to reproduce

- Open Mail.app and a mail with an attachment 
- Long tap on the attachment and select `Share`
- Select ownCloud.app and choose a directory 
- Tap on `Save`

### Expected behavior
Correctly saved binary file

### Actual behavior
Invalid binary upload

[PDF-Dokument.pdf](https://github.com/owncloud/ios-app/files/5385346/PDF-Dokument.pdf)

### Client
**iOS version:**
14.0.1

**ownCloud app version:**
11.4.1

**Comment by jesmrec** [comment]
Done! Ready for 11.4.2
