### ISSUE TITLE
[UX] More view

### ISSUE THREAD

**Issue by javiergonzper** [owncloud/ios-app#82]
_As a user, i want interact with a file in order to do actions_

### AC:
- [ ] The more view should be shown when the user tap on the `More button` that should appear in:
    - [ ] "The Preview" of the file
    - [ ] The row of the file in the "File List"
- [ ] Take into account the `capabilities` to hide the `Share` if the API is not available
- [ ] Share:
    - [ ] Show all the current shares (by user, group, link)
    - [ ] Add a new share 
    - [ ] Edit an old share to change the properties 
- [ ] Actions
    - [ ] Open with (send the file to other app)
    - [ ] Rename the file
    - [ ] Move the file/folder to a different folder
    - [ ]  Delete https://github.com/owncloud/ios-app/issues/22
    - [ ] Unshare instead Delete in the case that the file is shared by other user

### Mockups:

Both mockups are the same `More view` one with text buttons and other with system buttons

Text buttons
![more view text buttons](https://user-images.githubusercontent.com/1815050/41536831-fe7b0446-7306-11e8-8534-f094bfbcce1b.png)

System buttons
![more view icon](https://user-images.githubusercontent.com/1815050/41536830-fe5bf7c2-7306-11e8-806d-d40bca280f71.png)

Taking into account `Extremely long filenames`:
![more view - extremely long filenames](https://user-images.githubusercontent.com/1815050/41838401-a400c97e-7860-11e8-8a0b-1d723db614c2.png)

- Figma design:
https://www.figma.com/file/Ui4YzD3oQcxJSbzBEr80O9eU/Working-Draft-UI?node-id=1657%3A1037

**Comment by michaelstingl** [comment]
@javiergonzper System buttons look good too 👍

**Comment by jesmrec** [comment]
system buttons much better. I guess the (+) button will include the options the create both public and private shares.

**Comment by javiergonzper** [comment]
Added a mockup with a `Extremely long filenames` related to the issue: https://github.com/owncloud/ios-app/issues/88

cc: @michaelstingl

**Comment by skwale** [comment]
i need owncloud to be integrated in Files app like Dropbox or box

**Comment by javiergonzper** [comment]
> i need owncloud to be integrated in Files app like Dropbox or box

Hi @skwale we are working on it 👍 
Here you have the issue: https://github.com/owncloud/ios-app/issues/11

**Comment by atwm** [comment]
Previews for RAW files (photos). Raw files normally include jpeg previews which can be extracted an shown

**Comment by michaelstingl** [comment]
@atwm cool idea, should be discussed in https://github.com/owncloud/ios-app/issues/85
