### ISSUE TITLE
Sharing features

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#83]
Sharing feature is one of the most important in the ownCloud ecosystem. Let's summarize the most important deals to take in account:

**API call**

`ocs/v1.php/apps/files_sharing/api/v1` 

Reference: https://doc.owncloud.org/server/10.0/developer_manual/core/ocs-share-api.html

**Private Sharing**

- An user can share an item (file/folder) with other user or group of users set in core admin dashboard. It will be needed a way to search for sharees.
- An user can share an item with a user in other server (federate sharing), using '@' notation `user@server`. Once the user types an '@', in the list of options will be displayed the option `user@remote`
- Once the item is already shared, permissions over the sharing can be set up. In case of a file the permissions will be sharing (_reshare_) and editing (named _change_ in the core). In case of a folder, permissions will be sharing, creating (add content to the folder), deleting (remove content from the folder) and editing (change the content of any file into the folder)
- Private shares can be deleted. Sharee will not see the item in his/her file list anymore
- Sharee will have the posibility of removing the shared item from the file list with the option `Unshare`
- Sharees will see the user who shared the content.
- In case of resharing, the owner of the share will be always who owns the item. The sharing user will handle shares and reshares over the content.

**Public Sharing**

- User can create as many public links as he/she wants. It was available from 10.0.4, pending to check if it was backported in any way. For older versions, only one public link per item is allowed.
- Public links have several attributes:

1.  Link name
2. Permissions Like in core, it will depend on the kind of item (file, folder):
 - Download / View: files & folders 
 - Download / View / Upload: folders
 - Upload only (file drop): folders
3. Password
4. Expiration date

to be included in the request body

All of them will be leaded by capabilities (see below)

**Capabilities**

Ref: https://doc.owncloud.org/server/latest/developer_manual/core/ocs-capabilities.html

Capabilities related with sharing, with  impact in the app

- "api_enabled" : true -> sharing allowed.  false -> Neither private nor public sharing allowed. Depending on the value, options to share will be displayed or not.

- "federation": two capabilities: "incoming", "outgoing" to determine if it is posible to perform/receive private shares with other server's users. Depending on the value, patterns with '@' will give the user to enter federated locations.

- "public": group of capabilities for public links: "enabled", "expire_date" ("enabled", "enforced" and "days"), "multiple" (if true, several public links on the same item allowed), "password" ("enforced" -> backwards compatible, and "enforced_for", depending on permissions "read_only", "read_write", "upload_only"). Depending on such values, options will be displayed or not, and user will be forced to input values or not. If "enabled" is false, nothing related with public links will be displayed.

- "resharing": true -> allows a sharee to share. If user is a sharee and capability is false, option will not be displayed for the item.

Discussion about capabilities: when should they be refreshed from server? in the current app, they are refreshed in the following two cases:

1. When the app is opened (after killed)
2. By switching account

NOTE: ownCloud Android app refreshes the capabilities every time the root folder is browsed.

**Comment by jesmrec** [comment]
As first step before start developing, i think it will be really helpful to research/discuss in which way are going to "speak" the app and the SDK. I mean, the SDK will get info from the server and the app will be fed from he SDK to display. This will allow as:

- Developing app and SDK in parallel
- Ease to define tests

**Comment by hosy** [comment]
#275

**Comment by hosy** [comment]
I just found this draft for implementing sharing in the UI and I like it:

![actionshare](https://user-images.githubusercontent.com/736109/53232048-8cf89980-368a-11e9-9a7a-0be9d119cc73.png)

**Comment by michaelstingl** [comment]
Yay, there are good ideas. But maybe too crowded in real world scenarios. I'd like to keep link sharing in the UI separate from user/group shares. There's currently some work going on in the Phoenix project. Results might be used in the mobile and desktop clients as well…

**Comment by hosy** [comment]
Sharing is implemented since version 1.0.0
