### ISSUE TITLE
[Previews] Video preview

### ISSUE THREAD

**Issue by javiergonzper** [owncloud/ios-app#84]
_As a user, i want the possibility to play a video file on the ownCloud iOS App_

### AC:
 - [ ] The file should be streamed (not downloaded).
 - [ ] This should not works in background
 - [ ] The video should be controlled also by the system controls (`MPRemoteCommandCenter `):
    - [ ] Play/Pause
    - [ ] Airplay from duplicate screen (should be automatic)
- [ ] The player should allow full screen with one tap on the screen and exit from background with one tap
- [ ] The video preview should provide Picture in Picture (PiP) playback on supported iPad models
- [ ] The video should allow portrait and landscape (see mockups)

### Mockups:
Portrait stopped (never tapped the play button). Preview image is a thumbnail of the video
<kbd>
![video portrait stopped](https://user-images.githubusercontent.com/1815050/41597915-156ab2be-73cf-11e8-919b-d6ec9bedc84a.png)
</kbd>

Video playing/pause after play started
<kbd>
![video portrait playing](https://user-images.githubusercontent.com/1815050/41597950-2d9d3596-73cf-11e8-915f-ea13febfe160.png)
</kbd>
<kbd>
![video portrait paused](https://user-images.githubusercontent.com/1815050/41598005-49f0447c-73cf-11e8-96d5-257966c7ee59.png)
</kbd>

Video in landscape not full screen
<kbd>
![video landscape playing](https://user-images.githubusercontent.com/1815050/41598028-5839a2bc-73cf-11e8-8045-4eb39ba4fa7d.png)
</kbd>

Figma design:
https://www.figma.com/file/Ui4YzD3oQcxJSbzBEr80O9eU/Working-Draft-UI?node-id=1710%3A0

**Comment by felix-schwarz** [comment]
iOS provides us with [`AVPlayerViewController`](https://developer.apple.com/documentation/avkit/avplayerviewcontroller). From Apple's documentation:

> … displays the video content from a player object along with **system-supplied playback controls**.

> AVPlayerViewController **automatically supports AirPlay** …

> Starting in iOS 9, you can use AVPlayerViewController to provide **Picture in Picture (PiP)** playback on supported iPad models.

I think it's reasonable to use this as basis for video playback support.

**Comment by michaelstingl** [comment]
Current webview based video player supports Picture in Picture (PiP) on iPads. Nice to have this with `AVPlayerViewController` too…

**Comment by hosy** [comment]
Implemented: https://github.com/owncloud/ios-app/pull/429
