### ISSUE TITLE
Check: Upload video files without re-conversion

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#847]
Related:
https://github.com/owncloud/ios-legacy/issues/1040

==> @mneuwert

**Comment by mneuwert** [comment]
@michaelstingl Shall we eventually add "Prefer original videos" as new upload option? Technically, slo-mo for instance is edited once: 120fps shot video + transformation applied. So if you upload original it is going to be a video shot at higher FPS but without any slo-mo effect.

**Comment by michaelstingl** [comment]
Yes, “prefer original video” would be perfect 👍

**Comment by michaelstingl** [comment]
> @michaelstingl Shall we eventually add "Prefer original videos" as new upload option?

Yes, sounds cool 👍

**Comment by jesmrec** [comment]
Done
