### ISSUE TITLE
Don't auto-guess /owncloud endpoint

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#849]
Hosting in /owncloud became less and less common. But auto-guessing additional endpoint can cause problems.

Overview-issue: https://github.com/owncloud/product/issues/294

**Comment by felix-schwarz** [comment]
The SDK branch belonging to #873 removes owncloud subfolder discovery support.

**Comment by jesmrec** [comment]
I have an instance in  a `localhost/owncloud`

If i type `localhost` -> instance not detected by the app
If i type `localhost/owncloud` -> instance detected by the app

so, it is not auto-guessing the `/owncloud` location any more.

**Comment by jesmrec** [comment]
Problem fixed
