### ISSUE TITLE
Deal with iOS 14 Photo permissions

### ISSUE THREAD

**Issue by mneuwert** [owncloud/ios-app#851]
See e.g.
https://www.andyibanez.com/posts/understanding-limited-photo-library-ios-14/

**Comment by fschade** [comment]
steps to reproduce

1.) Log into your app and connect it to a server
2.) hit the plus icon on the right top side and select „upload from your photo library“
3.) iOS asks you which collections or photos you wanna make available, select a few
4.) close overlay
5.) hit the plus icon on the right top side and select „upload from your photo library“ again
6.) only previously white listed photos or collections available, now try whitelist more photos or collections

expectations: a button or setting where I am able to select what parts are available for the OC iOS app

**Comment by michaelstingl** [comment]
Needs research if apps can ask for more permissions. 

Workaround:
1. Open iOS Settings
2. Search for ownCloud iOS app
3. Fix Photos permissions 

![DC68C790-A2EB-447A-BE1B-3262CE92F1B4](https://user-images.githubusercontent.com/214010/102484714-f1a69480-4066-11eb-8e70-41b922d2cc04.jpeg)

**Comment by jesmrec** [comment]
Done! Ready to 11.5
