### ISSUE TITLE
[BUG] Not all Class Settings represented in adoc file

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/ios-app#854]
Left over from #838, TL;DR: the `adoc` file generated from the `json` file is missing documentation for some settings:

> @jesmrec wrote:
>
> This is the product of the script. With testing purposes, i've rendered it to html5 by using the `asciidoctor` (just for an easier visualization and comparison)
> 
> Document is correctly generated, but not with all objects in the JSON file (this was already reported in the chats). The missing objects are:
> 
> - `connection-allowed-authentication-methods` in category `Security`
> - `connection.connection-preferred-authentication-methods`  in category `Security`
> - `allow-cellular`  in category `Connection`

**Comment by felix-schwarz** [comment]
@dschmidt found the issue:

> You introduced a new status type that was not specified in the requirement: `recommended` - you need to add it to the list of supported status values: https://github.com/owncloud/ios-app/blob/milestone/11.5/tools/GenerateDocs/templates/ios_mdm_tables.adoc.tmpl#L17

I fixed the issue by adding `recommended` in commit 7b204c8cea9e30cf8abbd36351804204309e1416.

**Comment by dschmidt** [comment]
🎉
