### ISSUE TITLE
Icons not clear (when using the light Theme)

### ISSUE THREAD

**Issue by Akidxx** [owncloud/ios-app#860]
Icons are not clear in the bottom of the page 

![issue3](https://user-images.githubusercontent.com/15052479/103931498-adb42600-5120-11eb-8391-e63a69db154a.PNG)

It would be better to increase the contrast

Sample

![issue3](https://user-images.githubusercontent.com/15052479/103935043-48fbca00-5126-11eb-8fab-671530c0e091.PNG)

**Client**
iOS version: 14.3

ownCloud app version: 11.4.4 build 179

Device model: iPhone 8s

**Comment by hosy** [comment]
Thank you! Yes this icon contrast could be improved!

**Comment by jesmrec** [comment]
Done. It will be released in 11.5
