### ISSUE TITLE
Three dots should be to the left side (when using Arabic language)

### ISSUE THREAD

**Issue by Akidxx** [owncloud/ios-app#861]
### Expected behavior

![issue4](https://user-images.githubusercontent.com/15052479/103941750-9f213b00-512f-11eb-813e-1423e87f2c4c.png)

### Actual behavior

![issue5](https://user-images.githubusercontent.com/15052479/103941699-8749b700-512f-11eb-8c4e-9551ac2ad74c.png)

### Client
iOS version: 14.3

ownCloud app version: 11.4.4 build 179

Device model: iPhone 8s

**Comment by hosy** [comment]
Hi @Akidxx, thank you for submitting this issue.
You are right, this UI element should be adopted to the left-to-right layout.
We will add this to our todo list.

**Comment by jesmrec** [comment]
Arabic language support done. Ready to 11.5
