### ISSUE TITLE
Photos stuck uploading

### ISSUE THREAD

**Issue by Akidxx** [owncloud/ios-app#862]
### Steps to reproduce
1.Connect to your owncloud account
2.Click on a folder 
3.Upload a photo
4.Notice the upload still loading untill you disconnect and reconnect again

### Expected behavior
The upload shouldn't take more than few seconds

### Actual behavior
The photo stucks uploading for hours..
You need to disconnect and reconnect again

![issue6](https://user-images.githubusercontent.com/15052479/103943205-f45e4c00-5131-11eb-8b1a-17dbd6cc5313.png)

**Client**
iOS version: 14.3

ownCloud app version: 11.4.4 build 179

Device model: iPhone 8s

**Comment by michaelstingl** [comment]
Thanks for reporting!

Should be solved with the 11.4.5 release planned for the next few days.

**Comment by michaelstingl** [comment]
11.4.5 was just released:
https://apps.apple.com/app/id1359583808

Please update
