### ISSUE TITLE
Account management missing features

### ISSUE THREAD

**Issue by Akidxx** [owncloud/ios-app#863]
Trying to manage my acount I couldn't find a way to make a photo for it

**Describe the solution you'd like**
It would be better to add the possibility to manage an account like making a profile photo...

![20210107_2155](https://user-images.githubusercontent.com/15052479/103944972-bd3d6a00-5134-11eb-8e76-7c81fd6e6355.png)

**Actual feature**
![20210107_215409](https://user-images.githubusercontent.com/15052479/103945023-d47c5780-5134-11eb-9355-46cc6b725152.png)

Client
iOS version: 14.3

ownCloud app version: 11.4.4 build 179

Device model: iPhone 8s

**Comment by hosy** [comment]
Thank you for testing our app in detail. User avatar will be added soon. There is already an issue: https://github.com/owncloud/ios-app/issues/408

**Comment by michaelstingl** [comment]
Managing the account information only in the web ui, not planned for mobile app. But future version of the app will display avatar icons.
