### ISSUE TITLE
Choose a display mode

### ISSUE THREAD

**Issue by Akidxx** [owncloud/ios-app#864]
Make it possible to choose a display mode 

**Describe the solution you'd like**
![_223351](https://user-images.githubusercontent.com/15052479/103948217-b6fdbc80-5139-11eb-8e97-79ca8a9efb8c.png)

![223343](https://user-images.githubusercontent.com/15052479/103948241-bfee8e00-5139-11eb-9f90-f70321e95eef.png)

**Comment by hosy** [comment]
This is also on our todo list and currently in development: https://github.com/owncloud/ios-app/issues/744
