### ISSUE TITLE
Not able to change the account username

### ISSUE THREAD

**Issue by Akidxx** [owncloud/ios-app#866]
### Steps to reproduce
1.Connect to your owncloud account from IOS device (using basic authentication)
2,Click the account URL 
3.Edit account
![20210111_122603](https://user-images.githubusercontent.com/15052479/104176994-5a83f100-5408-11eb-92d4-6df4e1fbe0b1.jpg)
4,Try to edit the username
5,Notice that it´s not possible to edit the username 

### Expected behavior
According to the documentation the username should be editable
![Edit_account_issue](https://user-images.githubusercontent.com/15052479/104177282-cf572b00-5408-11eb-821b-0cc9155a219b.PNG)

### Actual behavior
The username is not editable
![20210111_122232](https://user-images.githubusercontent.com/15052479/104177512-2eb53b00-5409-11eb-9ae7-93ffd5d14888.jpg)

### Client
**iOS version:**
14.3

**ownCloud app version:**
11.4.5 build 182

**Device model:**
iPhone 8s

### Server configuration

**ownCloud version:**
10,6

**Comment by hosy** [comment]
Hi @Akidxx !
It make sense, that editing the username is not possible, because some metadata is appended to the user. 
But you are right, the documentation should be changed here.

Please add a new user account inside the iOS app with the basic auth user login data you want to add. You can delete the other user account from the iOS app. This will only delete the account inside the iOS app.

**Comment by hosy** [comment]
Here is a workaround to copy non uploaded files to an other ownCloud account:
- Add a new account inside the iOS app
- Open the Files.app and enable both ownCloud accounts (if not visible tap on the `More …` button)
- Navigate inside the (outdated) account, which files are not uploaded to the server
- Select all files and tap on `Copy`
- Select the new account and the save folder
- Check if all files are imported correctly and uploaded to the server

Now all files are imported into the new account and the old account can be deleted inside the iOS app.

**Comment by michaelstingl** [comment]
@hosy New account is same as old account in this case (only credentials are different), but files are not cached/available offline. Copying all the files will result in massive duplicates/collisions. Needs testing before recommending this…

**Comment by hosy** [comment]
@michaelstingl it was not mentioned that the user is the same. This is a really special case, which maybe cannot handled by our app.

**Comment by michaelstingl** [comment]
> @michaelstingl it was not mentioned that the user is the same. This is a really special case, which maybe cannot handled by our app.

Exactly, not a supported use case.

**Comment by Akidxx** [comment]
> Exactly, not a supported use case. @felix-schwarz clarified it

@michaelstingl  You mean here https://doc.owncloud.com/ios-app/ios_accounts.html

**Comment by michaelstingl** [comment]
> @michaelstingl You mean here https://doc.owncloud.com/ios-app/ios_accounts.html

Yes, but seems the change wasn't deployed yet:
https://github.com/owncloud/ios-app/pull/867/files

**Comment by Akidxx** [comment]
> > @michaelstingl You mean here https://doc.owncloud.com/ios-app/ios_accounts.html
> 
> Yes, but seems the change wasn't deployed yet:
> https://github.com/owncloud/ios-app/pull/867/files

Yep not yet in the docu..still have the old
