### ISSUE TITLE
[BUG] Menu enhancements

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/ios-app#871]
### Expected behavior
The menu should have the same spacing everywhere (1). The folders are not completely hidden by the menu, the view that results is confusing (2).

### Actual behavior
The spaces of the first and last cell look truncated (1). The folders are still visible behind the menu which gives the impression that they are part of the entries (2).

![image](https://user-images.githubusercontent.com/33026403/104772621-fe0c3300-5773-11eb-9104-635f6d0654a6.png)

### Client
**iOS version:**
14.2
**ownCloud app version:**
11.4.5
**Device model:**
iPhone 11

**Comment by hosy** [comment]
@ChrisEdS Should be fixed with #870, please check this build

**Comment by ChrisEdS** [comment]
Thanks for taking care. From the screenshots in #870 everything looks nice now.
