### ISSUE TITLE
Extremely long filenames

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#88]
Pro-users often have many files, sometimes with extremely long names that are nearly identical. Only differentiation is in one part of the file name. This could be at the beginning, in the middle, or at the end.

@javiergonzper Could you propose something? How does other apps deal with this?

**Related from old iOS app:**
- https://github.com/owncloud/ios/issues/129 (💡 ➡️ show file info)
- https://github.com/owncloud/ios/issues/180
- https://github.com/owncloud/ios/issues/428
- https://github.com/owncloud/ios/issues/575 (💡 ➡️ decrease font size)

**Comment by michaelstingl** [comment]
Could also help? https://github.com/owncloud/ios-app/issues/50 (Local search)

**Comment by javiergonzper** [comment]
To show long string on iOS we have some different possibilities:
- Truncate (Do not show the full string and cut it at the end or in the middle) <- Not useful for pro users
- Make the font smaller when it have too many characters <- If the name it is so big at the end we will have to truncate it
- Use MarqueeLabel:
![GIF of MarqueeLabelDemo in action](https://raw.githubusercontent.com/cbpowell/MarqueeLabel/master/Metadata/MarqueeLabelDemo.gif)
​
Use a MarqueeLabel on many cells at the same time probably will be very ugly but maybe could be a solution on other views.

The approach selected on the old iOS app was to make the font smaller on the file list. And also show the full name on the `Action Sheet`:

![img_0236](https://cloud.githubusercontent.com/assets/1815050/13008813/00ced66c-d199-11e5-8579-fc6c8e3ba9c1.PNG)

![support for long names](https://cloud.githubusercontent.com/assets/2051473/9545208/9de49b30-4d87-11e5-824d-bc03f69f489e.png)

IMHO we should take that approach on the new `File list` and also on the `More` view. I will review those mockups

**Comment by michaelstingl** [comment]
I had an interesting discussion with some heavy iPad users today and the following ideas came up:

- Resize file-list-column (drag separator)
- Make single file table cell higher to let the file name wrap multiple lines
- Config/MDM option or button in top bar to disable iPad-style layout on iPad, so you see extra-long lines in landscape mode and full screen previews, like on a super-sized iPhone

**Comment by hosy** [comment]
Solved with #516
