### ISSUE TITLE
[BUG]  When opening a password-protected document the second time, no keyboard appears

### ISSUE THREAD

**Issue by Trylok** [owncloud/ios-app#885]
### Steps to reproduce
1. Upload a passwordprotected Word .docx or Excel .xlsx document.
2. Open it on the App on iPhone or iPad. First time keyboard appears, and password can be entered.
3. Close it, and open it again. no keyboard appears, no password can be entered. Only blinking cusor is shown.

### Client
**iOS version: **
14.4

**ownCloud app version:**
11.4.5

**Device model:**
iphone / ipad (all Versions, same results)

### Server configuration
**Web server:**
Apache 2.4

**Database:**
MySQL

**PHP version:**
7.4

**ownCloud version:**
10.6

**Comment by michaelstingl** [comment]
> * Upload a passwordprotected Word .docx or Excel .xlsx document.

Thanks for reporting! Could you provide an example file?

**Comment by Trylok** [comment]
[password.docx](https://github.com/owncloud/ios-app/files/5903527/password.docx)

Attached a testfile. Password is "password" without quotes.

**Comment by hosy** [comment]
@Trylok thank you for providing this test file. I can reproduce the problem. We will have a look!

**Comment by michaelstingl** [comment]
Did someone check with the new 11.6.1?

**Comment by Trylok** [comment]
I can confirm that it is working now. Problem solved.

**Comment by michaelstingl** [comment]
> I can confirm that it is working now. Problem solved.

Glad to hear 🎉 Thanks for the feedback!!
