### ISSUE TITLE
App not running

### ISSUE THREAD

**Issue by mibrahimovic** [owncloud/ios-app#89]
Hi, I downloaded the app and I'm trying to run in on xCode but I'm getting this error: No such module 'ownCloudSDK'. I'm stuck and I couldn't fix it.
Any suggestions?

Thanks

**Comment by pablocarmu** [comment]
Hi!

We're currently using `Git submodules` to manage our dependencies.
I think your problem might be that you are not setting up correctly that dependencies.
You could try to open the terminal, go to the repository folder and perform:

```Bash
$ git submodule init
$ git submodule update
```
This should fix your problems with the dependencies.

**Comment by pablocarmu** [comment]
I think we can close this. We can always reopen the issue if @mibrahimovic has more issues.
