### ISSUE TITLE
[BUG] Keyboard does not disappear (on jump to PDF Page)

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#894]
Keyboard does not disappear when using the jump to PDF page function on the iPad. 

### Steps to reproduce
1. Open PDF
2. Tap on Jump to Page
3. Enter Page or Cancel
4. Keyboard does not disappear 

### Expected behavior
Keyboard can be hidden

### Client
**iOS version:**
14.4

**ownCloud app version:**
11.5

**Device model:**
iPad

**Comment by jesmrec** [comment]
Done. Ready to 11.7.1
