### ISSUE TITLE
[BUG] Detail Text View not themed in dark mode

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#919]
The text detail view is now themed if dark mode theme was selected.
Text files are shown inside a web view. Not sure if it was possible to set the colors. Maybe possible by injecting CSS or JavaScript.

### Steps to reproduce
1. Open a text file in detail view

### Expected behavior
- Background color should be dark
- Text color should be white

Check #900 

### Actual behavior
- white (bright) background

### Client
**iOS version:**
14.4

**ownCloud app version:**
11.5.2

![Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2021-03-04 at 15 54 49](https://user-images.githubusercontent.com/736109/109982233-fd1e6900-7d01-11eb-9b54-0a05d3efd2c9.png)

**Comment by jesmrec** [comment]
Done!! Ready to 11.6
