### ISSUE TITLE
[BUG] Changed files in Preview not refreshing

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#935]
## If you found a bug:
Regression: If an item is opened in preview (Text, PDF, ...) the preview will not updated, if there is a change on the server.
After dismissing the preview, the updated item is available.

### Steps to reproduce
1. Open a text file in the iOS app
2. Change this text file on the server
3. Preview does not update with the newest content

### Expected behavior
Preview updates after the file was updated on the server

### Client
**iOS version:**
14.4

**ownCloud app version:**
11.5.2

**Device model:**
iPad, iPhone

**Comment by michaelstingl** [comment]
I'm worrying about big, multipage documents like PDF, Word, PowerPoint etc…

**Comment by jesmrec** [comment]
Done. Ready to 11.5
