### ISSUE TITLE
[BUG] Downloaded file could not be opened

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#942]
## If you found a bug:

In some cases a downloaded file could not be opened.
- File is already downloaded and was already opened in preview
- After trying to preview it again or markup the file it could not be opened

After checking in simulator the file url exists but the file is not stored.
Not sure if the SDK could check, if the file exists in the file system. If not, remove the locally available state.
I am also not sure, which action deleted the file from the file system.

### Steps to reproduce
Cannot provide steps to reproduce

### Expected behavior
File should be opened, when file url is set

### Actual behavior
No data available

### Client
**iOS version:**
14.4

**ownCloud app version:**
11.5.2

**Comment by felix-schwarz** [comment]
I could reproduce the issue of items not being shown in the viewer when swiping between images in the `Photos` folder. However, it seems that what I ran into is a viewer issue, while the image file is actually there.

To make it easier to see when a file gets deleted, I've added logging for almost all copy/move/delete file operations to the SDK. The relative path of an item's file is also logged now.

FileOp logging can be turned on and off in Settings > Logging > Log internal file operations with the latest SDK. I've already updated `feature/localsearch` with it.

@hosy Could you please turn that option on and then try to reproduce the issue with these changes in and send me the log? I can't seem to be able to provoke it to actually delete a file from under the viewer.

**Comment by felix-schwarz** [comment]
@hosy I noticed a lot of issues in the Display[Host]ViewController layer during debugging and decided to clean it up, which should hopefully also fix the issue you were seeing. I'm not completely through yet, but already can no longer reproduce the issue with the current state of https://github.com/owncloud/ios-app/pull/951. If you have some time, please test if it also addresses the issue for you.
