### ISSUE TITLE
[FEATURE REQUEST] Provide 6 digits Passcode Option

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#958]
Passcode setting should be expanded to 6 digits.

- it should be able to enforce this option by MDM
- keep option for 4 digit passcode

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by hosy** [comment]
@michaelstingl should the number of passcode digits only set by MDM or should this be configurable inside the app?

**Comment by michaelstingl** [comment]
If it's not a lot of extra work, user setting would be nice, but not super important.

**Comment by jesmrec** [comment]
Done!! Ready to go in 11.7
