### ISSUE TITLE
[BUG] owncloud online URL view with misplaced items

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#963]
Using the [ownCloud online Brandling.plist file](https://github.com/owncloud/customer-themes-tmp/blob/master/ownCloud.online/iOS/Theming/Branding.plist):

|Token|Credentials|
|:-:|:-:|
|![Screen Shot 2021-05-03 at 09 54 12](https://user-images.githubusercontent.com/14894746/116853120-cd062000-abf5-11eb-98ba-e6136ae19b94.png)|![Screen Shot 2021-05-03 at 09 54 44](https://user-images.githubusercontent.com/14894746/116853121-ce374d00-abf5-11eb-917b-36e0a1dda35b.png)|

The `Contacting server` message should not appear there before URL is checked

**Comment by hosy** [comment]
@jesmrec this bug is fixed in this commit:
https://github.com/owncloud/ios-app/pull/915/commits/bdfa35ee1830839522f8c06d1f234f6f0b21ad0b

**Comment by jesmrec** [comment]
glitch is already fixed
