### ISSUE TITLE
[BUG] ownCloud.online account duplication with basic auth

### ISSUE THREAD

**Issue by jesmrec** [owncloud/ios-app#965]
### Steps to reproduce
1. Install the app from scratch with [ownCloud.online branding](https://github.com/owncloud/customer-themes-tmp/blob/master/ownCloud.online/iOS/Theming/Branding.plist) 
2. Add a basic auth account 

### Expected behavior
Account is shown once in the list of accounts

### Actual behavior
Account is shown twice in the list of accounts

https://user-images.githubusercontent.com/14894746/116977389-acf06280-acc2-11eb-9c98-d1f61a0b0717.MP4

iPhoneXR v14.4
milestone/11.6 branch, commit `e440931fb`

**Comment by hosy** [comment]
@jesmrec thanks for testing.
Issue should be fixed in https://github.com/owncloud/ios-app/pull/915/commits/51786ec1828832e240b6b69ed0dc42480c4c8a3e

**Comment by jesmrec** [comment]
Fixed!! thanks!!
