### ISSUE TITLE
Public TestFlight Beta

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#97]
We plan to start the public TestFlight beta soon. @hurradieweltgehtunter anything that needs to be fixed on the registering website https://boarding.owncloud.com/ ?

We use a [3rd party tool](https://github.com/fastlane/boarding) here and we can't adjust everything. This is only a temporary solution. I expect Apple starts with a native process later this year…

![image](https://user-images.githubusercontent.com/214010/42761907-29ac5318-890f-11e8-8555-c80931ea97d2.png)

## User flow

- We link to post on the [blog](https://owncloud.org/news/) or [central](https://central.owncloud.org/) with all the relevant information with **call to action** to https://boarding.owncloud.com/
- Users enter data on https://boarding.owncloud.com/
- Users receivers mail from Apple with further instructions
- Users need to install the [TestFlight](https://itunes.apple.com/app/testflight/id899247664) app from public App Store
- Users can download beta app with TestFlight app
- Users can provide feedback inside the TestFlight app or inside the beta app

/cc @ChrisEdS

**Comment by hurradieweltgehtunter** [comment]
I would suggest setting up a landing page which links to the tool. This results in nearly the same workload as a blogpost or central post. But this way we can re-use it everywhere and promote it and even re-use it when building a permanent solution.
If you could give me all information you have about this. I'll set up a layout and content.
To when it should be online?

Feedback: The fields are labeled german while the bottom text is english. It should be all english i think.

**Comment by michaelstingl** [comment]
@hurradieweltgehtunter Landing page for testing projects sounds great! I'll collect all necessary information.

It seems the [boarding](https://github.com/fastlane/boarding) tool comes with some translated strings, but our own text isn't translated of course. My browser is configured for English, and in my screenshots, labels are English. Maybe @ChrisEdS can remove the language files in [`/config/locale`](https://github.com/fastlane/boarding/tree/master/config/locales) to have English-only.

**Comment by ChrisEdS** [comment]
@michaelstingl I'll talk to Thomas tomorrow. He published the container in which the boarding tool is running. Removing the translation shouldn't be a big deal.

**Comment by javiergonzper** [comment]
On the boarding page we should specify that it is for register to try the new iOS App beta through TestFlight because if not the user will not know for what it that boarding page.

**Comment by hurradieweltgehtunter** [comment]
Maybe add a link back to the future landing page?

**Comment by lefherz** [comment]
Hi :) afaik this is the last blocker for #78. Can we get this done soon?

**Comment by ChrisEdS** [comment]
@hurradieweltgehtunter What is the status for the landing page? 
@michaelstingl What's the status of collection the necessary information?

**Comment by michaelstingl** [comment]
> @hurradieweltgehtunter What is the status for the landing page?
> @michaelstingl What's the status of collection the necessary information?

no updates yet

**Comment by ChrisEdS** [comment]
https://boarding.owncloud.com is up and running again.

![image](https://user-images.githubusercontent.com/33026403/45363960-2ea69580-b5d9-11e8-848a-3689c9f76bc2.png)

**Comment by michaelstingl** [comment]
@ChrisEdS what about the languages? EN-only now?

**Comment by michaelstingl** [comment]
@ChrisEdS then please use the long link. We didn’t tell anybody about new iOS yet, so nobody will be confused by the dead link. Once we publish the blog post, everything will be ready …

**Comment by lefherz** [comment]
Perfect :) I just added the https://boarding.owncloud.com/ link to the "Join our Testflight Program!" button in the upcoming blog post. We can publish it any time :) let's see when we have the biggest impact.

**Comment by michaelstingl** [comment]
Okay, our own website is no longer necessary. We can now send volunteers directly to:
https://testflight.apple.com/join/Oktj0iKv

It seems we have zero control about the content of this page, so we need all information how to install and how to test in the blog post, and on the future landing page.

**Comment by michaelstingl** [comment]
@tboerger @ChrisEdS Could you shutdown https://boarding.owncloud.com/ and redirect to https://testflight.apple.com/join/Oktj0iKv ?

**Comment by tboerger** [comment]
Why do we need to keep a redirect? the boarding tool hasn't been publicly announced?

**Comment by michaelstingl** [comment]
> Why do we need to keep a redirect?

Blog posts etc are prepared, and we told some customers about the URL. We'll try to change everything to the new URL, but we might miss it somewhere… If it's too much effort, we don't need the redirect.

**Comment by michaelstingl** [comment]
okay, then please drop

**Comment by tboerger** [comment]
Done
