### ISSUE TITLE
[BUG] Duplicate files after "make offline"

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/ios-app#970]
Customer reported a bug: "I have been playing with the "make available offline" feature on the iPhone"

### Steps to reproduce
1. I made a folder available offline
2. Then turned off network
3. Files were available. Good.
4. Then I wanted to remove them from the device again (The menu item is now called "Offline Available". I wasn't sure if I was removing the folder from the device again by selecting it, but I tried. I pressed several times on this menu item even while the network was turned off (exact sequence to reproduce I can not give, but I'm not paid as a tester ;))
5. Then turn the network back on.

### Expected behavior
I expected the removed folder to stay removed

### Actual behavior
After a short time, an undesirable situation arose: I now have duplicates of the files. See screenshot from the app. These duplicated files also appear when I now access the cloud in the browser. See other screenshot.

![Datei_000](https://user-images.githubusercontent.com/16665512/117635162-d8ba8f00-b17f-11eb-8313-ce5f76263f59.png)
![duplicateFilesBrowser](https://user-images.githubusercontent.com/16665512/117635146-d6583500-b17f-11eb-981e-e68a4922b733.png)

### Client
**iOS version:**

**ownCloud app version:** 11.5.2

**Device model:** iPhone

**Comment by michaelstingl** [comment]
Can‘t reproduce. We can reopen in case we can reproduce or can check logs & screen recording.
