### ISSUE TITLE
[FEATURE REQUEST] Rename accounts without the login flow

### ISSUE THREAD

**Issue by fvdm** [owncloud/ios-app#972]
**Is your feature request related to a problem? Please describe.**
To simply rename an account you have to complete the login procedure all over again.

Steps:
1. Go to the Accounts list
2. Swipe left on one of the accounts
3. Tap the _Edit_ button
4. Alter the _Name_ field
5. Tap _Continue_ to save the new value

Instead of going back to the _Accounts_ list, you are asked to login at the server for the access permissions.

**Describe the solution you'd like**
Save the new account name without the login procedure.

**Describe alternatives you've considered**
Maybe move the account renaming to _Manage_ instead of _Edit_ if a save button is not possible there. And then relabel _Edit_ in the swipe menu to _Connection_.

**Additional context**

- ownCloud app v11.6.0
- The account is properly linked and working before the renaming.

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by jesmrec** [comment]
Done and released in 11.9.1
