### ISSUE TITLE
[FEATURE REQUEST] Additional URL Scheme

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#979]
There should be an additional URL scheme.

This is interesting, if more than one of this apps is installed on a device:

- regular iOS app
- EMM app
- ownCloud.online app

If the user wants to open a specific app via URL scheme, the system randomly decides which app will be opened.
By adding an additional URL scheme, the user can control which app should be opened.

This could be interesting when opening a ownCloud file id via Shortcuts.app.

**Comment by michaelstingl** [comment]
Affects OAuth 2.0 redirect URI too. See related https://github.com/owncloud/android/issues/2883
