### ISSUE TITLE
[BUG] Sharing dialog from Files App cannot be closed on iOS 12.5.3

### ISSUE THREAD

**Issue by D1eter** [owncloud/ios-app#986]
### Steps to reproduce
1. install ownCloud App 11.6.0 on iOS 12.5.3 from App Store
2. setup account e.g. on demo.owncloud.com
3. add ownCloud as location in Files App
4. go to any file and choose  "Share with user/group" or "Share link" dialog from context menu
5. try to close dialog using "Done" in order to get back to Files App

### Expected behavior
"Done" should close the sharing dialog and go back to Files App

### Actual behavior
Nothing happens when tapping "Done"

### Client
**iOS version:** 12.5.3

**ownCloud app version:** 11.6.0 build 194

**Device model:** iPhone 6+

### Server configuration
**Web server:** I used demo.owncloud.com but the server doesn't matter

**Comment by D1eter** [comment]
Thanks!

**Comment by jesmrec** [comment]
Fixed! Ready to 11.6.1
